### ISSUE TITLE
[Graphs Screen] Reset Button Does Not Reset Graph Or Track Type

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/energy-skate-park#100]
For https://github.com/phetsims/QA/issues/397 on the Graphs Screen when the reset button is hit the graph or track type does not reset. The best way to see the graph behavior in action is to switch the graph type to "Time" and put the skater on the track. Before the time runs out hit the reset button (not the eraser which resets the graph). Time will continue to pass on the graph. The graph will also fail to revert to the initial "Position" tracker. To see the track type behavior change the track to the non "U" shaped track and hit reset, the track will not change back to the initial "U" shape. It is my understanding that when the screen is reset that all aspects of the screen should revert to the initial state before anything is changed. I have checked the other screens and it seems that in every screen the track does not reset when the reset button is hit. If this is the intended behavior for the screen and the sim in general let me know.

**Comment by jessegreenberg** [comment]
Thank you @JRomero0613, definitely not intended.

**Comment by jessegreenberg** [comment]
> track type does not reset.

It looks liek this is actually true for all screens at the moment.

**Comment by jessegreenberg** [comment]
Thanks @JRomero0613, this has been fixed - reset is fully implemented on the graphs screen now.
