### ISSUE TITLE
Long Strings Mess Up Formatting

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/energy-skate-park#102]
For https://github.com/phetsims/QA/issues/397 longer string can mess up the formatting of all the screens due to the increase in size of all the strings. This is most evident with the ?stringTest=long query parameter on the "Graphs" screen. I have attached a screenshot to indicate the severity of the formatting issues that occur with the long strings. 
![Screen Shot 2019-08-08 at 12 44 10 PM](https://user-images.githubusercontent.com/30352536/62729557-6b426300-b9db-11e9-9141-eb2f17df0bfe.png)

**Comment by arouinfar** [comment]
Thanks @JRomero0613.

Looks like the sim is missing some `maxWidth` settings.

**Comment by jessegreenberg** [comment]
Thanks for pointing out, layout issues have been resolved. I went through and tested with stringTest=long and stringTest=double to verify.
