### ISSUE TITLE
Energy pointer gets lost when dragged out of the screen

### ISSUE THREAD

**Issue by jaspearias** [phetsims/energy-skate-park#107]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Internet Explorer

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/397
In the Measure screen when dragging the energy pointer out on the edges of the screen it gets lost. You have to refresh the sim in order to be able to use the energy pointer again. 

<b>Visuals</b>

https://drive.google.com/file/d/1GC1eyRbBW8ToDZ4Wgqlz6tJd56-ZOIAn/view?usp=sharing

**Comment by arouinfar** [comment]
@jessegreenberg is it possible to keep the ProbeNode within the visibleBounds of the sim?

**Comment by jessegreenberg** [comment]
Thanks for pointing out, that sounds good. Done in the above commit.
