### ISSUE TITLE
Energy graph overlaps with double strings

### ISSUE THREAD

**Issue by jaspearias** [phetsims/energy-skate-park#109]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Internet Explorer

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/397
When testing double strings in the "Lab" screen the energy graph overlaps into the ground and the "Grid and Reference Height" check box. 

<b>Visuals</b>

![Energy graph overlaps](https://user-images.githubusercontent.com/52931414/62963624-969fc600-bdbe-11e9-886d-085f8adc308a.png)

**Comment by jessegreenberg** [comment]
Thanks! Fixed in the above commit and the rest will be taken care of in #102
