### ISSUE TITLE
Custom Mass does not work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#111]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/397
On the Intro screen there is a combo box to select mass.  There is an option that says custom, but there is no slider or other means of setting mass that I am able to see.  The custom selection also remains if you hit reset.  This last part does not seem to be a problem with the functioning selections.
**Steps to reproduce**
1. Go to the intro screen
2. Select options in the mass combo box, including custom
3. Observe behavior of selections upon reset

**Visuals**
![custombroken](https://user-images.githubusercontent.com/41024075/63037671-c4e3db00-be7c-11e9-9d80-d8ba85cbe21b.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This same problem seems to occur with the gravity slider/combobox on the other screens.  If you switch to custom and don't move the slider, the above bug occurs.  If you switch to custom and do move the slider to a new position, the bug does not seem to occur.
![customwontreset](https://user-images.githubusercontent.com/41024075/63060901-bca59300-beb0-11e9-94ee-4f9159ec078d.gif)

**Comment by jessegreenberg** [comment]
I expect this to be mostly fixed with changes form #114 but I will verify.

**Comment by jessegreenberg** [comment]
Breaking up what was mentioned in this issue:
- [ ] Remove 'Custom' entry when the combo box is not accompanied with a slider.
- [ ] Reset should apply to the ComboBox item.

**Comment by jessegreenberg** [comment]
A couple of things fixed in the above commits but this was mostly resolved by #111 I verified that reset is working properly.
