### ISSUE TITLE
Indicator that speed is high?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#112]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/397
When speed of the skater gets past a certain point the red needle on the speedometer tool stops registering it.  The skater can still go faster, and if a number value is on the speedometer, it will record the higher speed.  I was wondering if it would be a good idea to have some indicator that the speed is higher even if the needle can't move more.  I'd be hesitant to move the needle past that point, but adding a crack in the "glass" of the speedometer when the needle would hbe further may be a good solution.  Feel free to close if this has already been discussed.

**Visuals**
![brokenspedometer](https://user-images.githubusercontent.com/41024075/63040440-b7315400-be82-11e9-9a71-b5669b182e96.gif)
![speedproposal](https://user-images.githubusercontent.com/41024075/63040546-e778f280-be82-11e9-9574-43151566c541.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
It's a bit hard to see, but the max speed in the gif in https://github.com/phetsims/energy-skate-park/issues/112#issue-480788430 is ~30 m/s, but the needle reaches the max at 20 m/s. I think the most direct solution would be to increase the max value on the speedometer.

With the narrowest possible aspect ratio on external monitor, max mass, max gravity, the largest speed I can create is 46.3 m/s.  However, I don't think this is a very realistic max speed, and would keep the needle looking pretty lame most of the time.
![Energy Skate Park screenshot](https://user-images.githubusercontent.com/8419308/64048672-9548fa00-cb2f-11e9-90ce-a75ad2115776.png)

I think a more realistic max speed would be based on the max release height on a portrait iPad. There, the max speed stays just below 30 m/s, so let's set the new max to to 30 m/s @jessegreenberg.

**Comment by jessegreenberg** [comment]
Sounds good, max speed for the speedometer was increased to 30 m/s. @arouinfar would you like to review and see how this feels?

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg, thanks!
