### ISSUE TITLE
Green Reset Skater button blocks graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#113]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/397
On the Graphs and Lab screens it is possible to drop the skater in such a way that the green reset button blocks part of the graph.
**Steps to reproduce**
1. Go to the Graphs screen (bit easier and more noticeable due to Lab layering issues at moment)
2. Lift the skater up and to one side above the track.  Keep over graph, but towards top of it
3. Drop skater and let it fly off screen

**Visuals**
![greenskatebutton](https://user-images.githubusercontent.com/41024075/63062356-d4cbe100-beb5-11e9-9e59-a280c2351023.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@KatieWoe @jessegreenberg I think this is the correct behavior, so I'm going to close.

The skater was released at a point above the graph, and this is the appropriate position for the green return button to appear.  In this case, I don't think occlusion of the graph is problematic -- the skater is off-screen and there isn't any data in the graph.
