### ISSUE TITLE
Jupiter appears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#114]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/397
It is possible to get Jupiter to appear in the gravity combo box by moving the slider, instead of by using the dropdown box.  This does not seem to be the behavior in other sims such as masses and springs.  Since Jupiter has a whole number, it seems to be the only option that exhibits this behavior that I can find.
**Steps to reproduce**
1. Go to a screen with a gravity slider and combo box
2. Move slider back and forth.  Notice when the word Custom changes to Jupiter

**Visuals**
![suddenlyjupiter](https://user-images.githubusercontent.com/41024075/63122642-7ad62480-bf64-11e9-8c29-e1cb9a0217b4.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Good catch @KatieWoe.

If the gravity is changed by using the slider thumb or tweaker buttons, the combobox should show "Custom", even if the value matches that of one of the benchmarks. Similar NumberControl/ComboBox controls can be found in `bending-light` (Index of Refraction), `pendulum-lab` (Gravity), and `masses-and-springs` (Gravity).

**Comment by jessegreenberg** [comment]
Thanks for catching @KatieWoe. And thanks for clarifying the behavior @arouinfar. This behavior is done as described in the above commit. This is now working for both the gravity and mass slider/combo box pairs.
