### ISSUE TITLE
Raising the fixed track

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#115]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/397
Similar to https://github.com/phetsims/energy-skate-park-basics/issues/417 but the tracks are not lost.  If you continue to position the red dots in the Graphs screen you can continue to push the track up.  This is very slow going, but does not take to long to become noticeable.
**Steps to reproduce**
1. Go to the Graphs screen
2. Select the track with bumps in it
3. Drag the middle and left red dots to the bottom of their areas, especially the left one) over and over

**Visuals**
Start:
![start](https://user-images.githubusercontent.com/41024075/63126240-ae1cb180-bf6c-11e9-87fc-040ecfb1e125.png)
After:
![raise the skatebar](https://user-images.githubusercontent.com/41024075/63126256-b7a61980-bf6c-11e9-8c13-6b414eed4f98.png)
![raiseskatebartwo](https://user-images.githubusercontent.com/41024075/63126262-bbd23700-bf6c-11e9-97bb-4690d4c9097c.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Good eye @KatieWoe. The shift is pretty subtle, and it took awhile for me to even notice what is going on. I think it's a bit easier to see in a .gif. Here, I move the middle control point down. This changes the curvature of the track near the left control point in such a way that a portion of the track is somewhat below ground. As a result, the entire track shifts up.
![trackshift](https://user-images.githubusercontent.com/8419308/64047595-785ef780-cb2c-11e9-814b-0ee4708f1e79.gif)

I do not think this is a bug, but I'll leave that determination up to @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks for pointing out. I think we decided not to address this. This is related to https://github.com/phetsims/energy-skate-park/issues/83 where we made sure that the contorl points remain within their draggable bounds when the track is pushed above ground like this. I think this can be closed.
