### ISSUE TITLE
Custom drop down bar gets cut off on Google Chrome in "Measure" screen

### ISSUE THREAD

**Issue by jaspearias** [phetsims/energy-skate-park#116]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Google Chrome

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/397
When playing around with the sim in the Measure screen to change the gravity the custom drop down bar gets cut off. The tool box to the right also looks much closer to the ground which could be the reason why the custom drop down bar gets cut off. On this device it only happened on Google Chrome.

<b>Visuals</b>

![Energy Skate Park Drop Down Bar Cuts Off](https://user-images.githubusercontent.com/52931414/63130019-61d66f00-bf76-11e9-9604-f50247ac80cc.png)

<summary><b>Troubleshooting Information</b></summary>

Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1282x598
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks for pointing out. I am really curious why this is happening only in Chrome, though I suspect we want that combobox to open up anyway.

**Comment by jessegreenberg** [comment]
OK, I am seeing it in Chrome, Firefox and Safari on macOS 10.14.5. That makes me more confortable that this is just a sim issue and not a rendering problem we need to worry about.

**Comment by jessegreenberg** [comment]
![image](https://user-images.githubusercontent.com/6396244/64050098-047d1900-cb45-11e9-9802-0ab143ff59b3.png)

The layout has since changed so the list no longer reaches the navigation bar. I think that looks better for now than having the list go up. If the menu gains vertical space in the future we can change.
