### ISSUE TITLE
Add TimerNode to all screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#135]
This was mentioned in passing during the 10/3 design meeting, and I later discussed it with @kathy-phet. There is a potential client who has expressed some interest in using ESP(B), and suggested the addition of a stopwatch. 

ESP has several quantitative learning goals, and I think the addition of the TimerNode would add some flexibility to the simulation. Regardless of whether or not we move forward with the prospective client, I think we should add the TimerNode. 

This would be for ESP only, though we may consider adding one to ESPB in the future. ESPB is more introductory and qualitative, so the addition of a TimerNode would need more design and discussion.

@jessegreenberg can you add a TimerNode to the toolbox to the left of the MeasuringTapeNode? The toolbox would have the same width as the panel above it.

![image](https://user-images.githubusercontent.com/8419308/66596187-b0a91b00-eb59-11e9-84d6-be392c2729fb.png)

**Comment by jessegreenberg** [comment]
@arouinfar a TimerNode has been added to all screens of this sim, over to you for review.

**Comment by arouinfar** [comment]
@jessegreenberg overall looking good, but the toolbox feels a bit cramped. Can you reduce the tool icons by 10%, but keep the panel the same size?

**Comment by jessegreenberg** [comment]
@arouinfar how is that?

**Comment by arouinfar** [comment]
Looks great, thanks @jessegreenberg.

FYI @kathy-phet, @jessegreenberg has added a TimerNode to ESP. You can see it in master.
