### ISSUE TITLE
CT did not finish

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#136]
CT did not finish tests the night between 10/9/19 and 10/10/19.  Making an issue per request of @jessegreenberg

**Comment by jessegreenberg** [comment]
I see what yo umean now, out of all sims in this time window ESP did not finish tests, though it didn't fail any either.
![image](https://user-images.githubusercontent.com/6396244/66608137-cc291b80-eb83-11e9-8c0e-91e8c8a34174.png)

**Comment by jessegreenberg** [comment]
I am not sure what to do about this, sim is passing local tests OK. Ill watch and close if it does complete a test soon.

**Comment by KatieWoe** [comment]
These are the specific tests that aren't being done:
![thesearetheproblems](https://user-images.githubusercontent.com/41024075/66666851-d7755900-ec0e-11e9-99d0-86ef69775488.png)

**Comment by jessegreenberg** [comment]
Thank you @KatieWoe I forget that it is collapsible. And the read showing htere will make it easier to track down.

**Comment by jessegreenberg** [comment]
Standalone sim launches OK. phet-io-wrapper tests throws
> Assertion failed: launchSimulation cannot be called in a sequence

**Comment by jessegreenberg** [comment]
I don't see anything obviously wrong with energy-skate-park-main.js or EnergySkateParkSim.js. @zepumph or @samreid or @chrisklus could you please provide guidance on where to look next for this?

**Comment by zepumph** [comment]
I'm not sure about this. I ran local wrapper testing and couldn't reproduce the bug. In fact there were no issues with the wrapper tests.

**Comment by jessegreenberg** [comment]
Hmm, thanks for checking. I am only seeing the error when the dev tools are open. Failing test is SimTests: energy-skate-park: test launchSimulation. Either way, we still hit the assertion but QUnit is not reporting it.
![image](https://user-images.githubusercontent.com/6396244/66677229-2df68d80-ec37-11e9-9432-b0f3113585b4.png)

Maybe this is related to why CT shows blank entries?

**Comment by zepumph** [comment]
Ahhh sorry I think I misunderstood this issue. This is actually a purposeful and, until just now, I thought unavoidable byproduct of the test we were doing. 

> Failing test is SimTests: energy-skate-park: test launchSimulation. 

The test wasn't actually failing. The test was meant to make sure that that assertion triggered.

To fix the uncaught error from being propagated to the console (and other default places), I added a line to the test.

I never thought that perhaps this was causing silent issues for CT, but perhaps it is. I'm excited to see if this fixes things.

**Comment by jessegreenberg** [comment]
Cool, thanks @zepumph - CT is showing that tests are completing and passing again. Can this be closed?

**Comment by zepumph** [comment]
Actually, I wonder if the following lines are too strict, and could potentially suppress more than we want:

```js

      // suppress any errors that come from the simulation, as we are expecting one from launchSimulation. Other tests
      // will test for other errors. This works because this will always be on the same domain for tests.
      iframe.onload = () => { iframe.contentWindow.onerror = () => true; };

```

Perhaps something more like

`      iframe.onload = () => { iframe.contentWindow.onerror = (error) => if( error.message.indexOf('launchSimulation') >=0){return true;}  };` 

I'll take a look

**Comment by zepumph** [comment]
More specific error message handled above. I will check back on CT in a round or two.

**Comment by zepumph** [comment]
Looks like ESP is testing and there are no errors

![image](https://user-images.githubusercontent.com/6856943/93500534-b0181900-f8c0-11ea-9f87-cd970f45972a.png)
