### ISSUE TITLE
' => { return ' is bad text

### ISSUE THREAD

**Issue by zepumph** [phetsims/energy-skate-park#140]
Because of work in https://github.com/phetsims/chipper/issues/791, this lint rule has been broken, but commits in https://github.com/phetsims/chipper/issues/808 fixed it, and I saw a few errors in this repo (and basics). 

@jessegreenberg assigning over to you to fix a few lint rules. You can do so by uncommenting the last rule in bad-text.js (the one marked with the todo pointing to this issue). Please fix lint rules and then commit that rule uncommented to master. Thanks!

**Comment by jessegreenberg** [comment]
Fixed in this sim, Ill un-comment rule and commit to master next.

**Comment by jessegreenberg** [comment]
OK, fixed in a few different places (energy-skate-park, molecules-and-light, mobius) and uncommented the rule. I think this can be closed.
