### ISSUE TITLE
[iPad Air 2] Performance while dragging anything other than the skater

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#143]
Sim slows down by about 30% while dragging the timer/measuring tape.

**Comment by jessegreenberg** [comment]
This does not happen for the skater, likely because of `rendere: canvas`.

**Comment by jessegreenberg** [comment]
@ariel-phet can you please take a look and determine if this is worth any time to improve? To see the issue just get the skater moving on the track and drag either the timer or the measuring tape around the screen.

**Comment by jessegreenberg** [comment]
Just realized it is anything other than the skater, not just toolbox items.

**Comment by KatieWoe** [comment]
@ariel-phet asked me to make a recording, but I'm having trouble reproducing this on either our iOS 12 or iOS 11 iPad Air 2 devices.  Was this found on master or a dev version? What OS? Any other information?

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - that may be good news. I am testing on an iPad Air 2 with iPad OS 13.1.2. Do you have access to a device with that?

**Comment by KatieWoe** [comment]
No. Our device running OS 13 is newer, and the iPad Air 2s are both dedicated to running the older OS. If it is still a problem though, I can walk you through how to make a recording on the device you have? It isn't too hard.

**Comment by jessegreenberg** [comment]
Yes it it still slower on my device, lets make a recording so we can review to see if it is worth any more time.

**Comment by jessegreenberg** [comment]
Here are a couple recordings of what I am seeing. What is captured here isn't as severe as I remembered when I first opened the issue, but it it still there.

https://drive.google.com/open?id=1YSSS7ueK7NBVPwBnib7o2NQxt5-o1zYX

https://drive.google.com/open?id=1eFlNBAp0YLh-ozXFqDSTJ-0r8PZNS0a4

**Comment by ariel-phet** [comment]
@jessegreenberg I think this issue is worthy of a bit of investigation.

Considering that it is unlikely students will be moving the timer all around while playing, I don't think it is a huge concern, but I do think it would be useful to spend 1-2 hours seeing if the slow down can be reduced/eliminated. We certainly prefer to be glitch free, but if such an investigation yields no improvement, feel free to mark as `wontfix`

**Comment by jessegreenberg** [comment]
OK sounds good.

**Comment by jessegreenberg** [comment]
Notes from investigation:

- I am not able to investigate with Safari performance tools because Safari and tethering crashes after recording. I have encountered this before. So ill keep trying with other methods.

**Comment by jessegreenberg** [comment]
Alright @ariel-phet, I am out of time for this unfortunately but see above notes. I was able to investigate just about all things I could think to try.

Closing as `wontfix` for now from https://github.com/phetsims/energy-skate-park/issues/143#issuecomment-558286596.
