### ISSUE TITLE
User request: save track

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#145]
> The biggest problem now is that students cannot save their work anymore!  With only 44 minute periods, it is virtually impossible to do a thorough energy study in one class period. If students can’t save, they have to take the time to totally recreate their coaster models the next day.

**Comment by arouinfar** [comment]
@oliver-phet unfortunately save and load is not something that the ESP (or CCK) sims will have anytime soon. My suggestion would be for students to take a screenshot of the sim at the end of the class period (with the grid on), as it may cut down on some of the time needed to remember/recreate their tracks from a sketch.

**Comment by oliver-phet** [comment]
replied to user, closing!
