### ISSUE TITLE
Energy Graph data removal behavior

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#148]
From https://github.com/phetsims/energy-skate-park/issues/129.

The energy graph data needs a change in behavior. Currently, all plotted data simply exists for a bit of time then fades away before removal. We need that data to behave more like the measurable points in the measure screen.

On the measure screen, all data is removed with fade away when the skater direction changes. Then, when the skater is dragged or the track changes, all samples are cleared immediately.

**Comment by jessegreenberg** [comment]
I think this was done through work in #149. Behavior is now
- IF plotting against position
  - All data is cleared if the skater is picked up
  - No data is plotted while the skater is being dragged.
  - All data is removed with fadeout when the skater changes directions
  - All data is cleared when the track changes.
- If plotting against time
  - Data remains and continues to be plotted during dragging.
  - Data persists when the skater changes directions
  - All data is cleared when the track changes.

I thought for the line plot, data should continue to plot against time, even when dragging the skater. @arouinfar can you please review these changes? The Energy v Position plot looks different now.

I also made the lines a bit thicker, I think they are easier to see. But let me know if that should be reverted.

**Comment by arouinfar** [comment]
@jessegreenberg this is all looking good in master, thanks!
