### ISSUE TITLE
EnergySkateParkTimerNode can get lost if dragged out of availableModelBounds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#153]
EnergySkateParkTimerNode can get lost off screen if `EnergySkateParkModel.availableModelBoundsProperty.value` is reduced while the timer is out of bounds.  When the available bounds change, we need to make sure that the timer is still within bounds.

Over slack @samreid said that he is doing common code that may touch this it may be resolved through that work. We can check in after that work and see if this is still an issue.

**Comment by samreid** [comment]
This was addressed as part of https://github.com/phetsims/gas-properties/issues/170 and https://github.com/phetsims/energy-skate-park/issues/154.  I think it can be closed but will defer to @jessegreenberg to double check.

**Comment by jessegreenberg** [comment]
Its working great, thanks!
