### ISSUE TITLE
Use SCENERY_PHET/Stopwatch and StopwatchNode

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#154]
From https://github.com/phetsims/gas-properties/issues/170, `EnergySkateParkTimerNode` and several model Properties in `EnergySkateParkModel` should be replaced with SCENERY_PHET/Stopwatch and StopwatchNode.

I've implemented this change, and created this issue primarily to facilitate review.  Committing shortly.

**Comment by samreid** [comment]
Please note there is one TODO in the commit above. It's unclear whether it's desirable for the StopwatchNode to always be above ground, but that's the previous and current implementation.

**Comment by samreid** [comment]
@jessegreenberg can you please review at your convenience?

**Comment by jessegreenberg** [comment]
> Please note there is one TODO in the commit above. It's unclear whether it's desirable for the StopwatchNode to always be above ground, but that's the previous and current implementation.

I checked in with @arouinfar about this, she said that keeping both tools above ground is reasonable since there isn't a need to measure below ground and that it seems best for both tools to have the same drag bounds.

**Comment by jessegreenberg** [comment]
The code changes to use StopWatch and StopWatchNode look very good, thanks! It is working well in the sim too.
