### ISSUE TITLE
Minor artifact on the pie chart

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#156]
Discovered during phetsims/energy-skate-park-basics#300 I saw when WebGL was disabled, the pie chart had these artifacts on Win8/Firefox and OSX/Chrome

![image](https://cloud.githubusercontent.com/assets/679486/4833437/c9070180-5fa4-11e4-982c-1d86221cdf06.png)

**Comment by jessegreenberg** [comment]
Transfering to energy-skate-park because it applies to both.

**Comment by jessegreenberg** [comment]
`lineJoin: round` for the kinetic and potential energy slices seems to remove all artifacts but I want to test a little more.

**Comment by jessegreenberg** [comment]
I tested more thoroughly and didn't notice any issues with adding  `lineJoin: 'round'` to energy slices. This has resolved  the issue. Closing.
