### ISSUE TITLE
Improve performance on Windows 7

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#162]
From phetsims/energy-skate-park-basics#336: the RC test matrix showed reduced performance on Windows 7 Browsers.  It is unclear whether this was (a) a slower machine (b) the browsers weren't set up to use WebGL or (c) something else causing this.

**Comment by jessegreenberg** [comment]
This can be closed, MS no longer supports Windows 7 and so the project decided to stop supporting Windows 7 as well.
