### ISSUE TITLE
Use EnergySkateParkBasicsModel.addTrack more broadly

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#165]
From a TODO:
```js
    /**
     * Add a track, called by phet-io in setState (to restore a state).
     * TODO: this code should be called by EnergySkateParkBasicsModel too.
     * @param {Tandem} tandem
     * @param {boolean} interactive - whether the track can be dragged.
     * @param controlPointTandemIDs
     */
    addTrack: function( tandem, interactive, controlPointTandemIDs ) {
```

@samreid do you still believe this TODO still applies?

**Comment by samreid** [comment]
`PhetioGroup` should be used for this part.  Are you preparing for phet-io and phet brand publication for the new sim, or only PhET-brand?

**Comment by jessegreenberg** [comment]
Only PhET brand - should this wait until a PhET-iO publication?

**Comment by samreid** [comment]
I think this sim should be changed to use `PhetioGroup` when it is time to instrument the sim, or when we eliminate the legacy pattern as part of https://github.com/phetsims/tandem/issues/87

**Comment by jessegreenberg** [comment]
OK thanks, in that case this issue can be picked up at that point.

**Comment by samreid** [comment]
I deleted this method, and we will continue with the pattern established in https://github.com/phetsims/energy-skate-park/issues/123
