### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#17]
From https://github.com/phetsims/energy-skate-park-basics/issues/402:

There are a few .ai assets that seem to be missing.

 - I do not see "cement-texture-dark.jpg" in assets/
 - "attach.png" and "detach.png" images are not the same as "stick-to-track-icon.ai" and "espb detach from track icon.ai", those ai files are the icon without the skateboard and the skater feet/legs.

@arouinfar do you know how we could track down these assets?

**Comment by arouinfar** [comment]
@jessegreenberg I found ESP(B)-relevant artwork on [Drive](https://drive.google.com/drive/folders/0B6CMwxdP0NGYcFVqVTYyTlRfVk0), but I'm not seeing the missing assets. Perhaps @samreid may know more about these assets.

**Comment by samreid** [comment]
> cement-texture-dark.jpg

listed in license.json

```json
  "cement-texture-dark.jpg": {
    "text": [
      "Public Domain"
    ],
    "projectURL": "http://www.public-domain-image.com/full-image/textures-and-patterns-public-domain-images-pictures/concrete-texture-public-domain-images-pictures/cement-texture.jpg-royalty-free-stock-image.html",
    "license": "Public Domain",
    "notes": ""
  },
```

Here's the paper trail for the legs: https://github.com/phetsims/energy-skate-park-basics/issues/118, when I received these files in 2014 they were PNG files and unaccompanied by AI files.

**Comment by arouinfar** [comment]
Thanks @samreid! Bryce's [.ai backup for ESPB](https://drive.google.com/drive/folders/0By7uUV0_IG4pVklDdkVQcXhpYkE) does not appear to include the stick-to-track icons.

**Comment by jessegreenberg** [comment]
OK, closing this issue - though I did add a note "attach.png" and "detach.png" referring to this issue and mentioning that we do not have access to the original artwork.
