### ISSUE TITLE
Total energy increase when reattaching to track

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#172]
While investigating #166 I noticed that there are times when the skater reattaches in an open loop track that total energy will noticeably increase.

Here is track in question (with testTrackIndex=16 param)
![image](https://user-images.githubusercontent.com/6396244/72016321-8edf3300-3231-11ea-8679-095569a2609e.png)

**Comment by jessegreenberg** [comment]
Fixed after the above commit, I tried several times to make this happen and cannot anymore.

**Comment by KatieWoe** [comment]
Did a quick second look in https://github.com/phetsims/QA/issues/470 and I'm not seeing this issue there.
