### ISSUE TITLE
Matt should be present for the next RC deploy

### ISSUE THREAD

**Issue by mattpen** [phetsims/energy-skate-park#173]
See phetsims/perennial#146 (comment).

I'd like to be present for the next RC deploy so I can investigate permissions issues on bayes if needed.

**Comment by jessegreenberg** [comment]
Assigning to myself to make sure we remember to coordinate when we do this.

**Comment by jessegreenberg** [comment]
There were no permissions issues during deploy of the 1.0 prototype version so we should be set. Closing this issue.
