### ISSUE TITLE
Clock Does Not Advance When Skip Forward Button is Pressed

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/energy-skate-park#177]
For https://github.com/phetsims/QA/issues/470 when testing I realized that the clock does not advance when the skip forward button is pressed. To replicate this grab the clock tool, press the play button for the overall sim, and press the clock play button to start recording time. Once time is being recorded hit the pause button for the overall sim to stop any motion in the sim. Now press the skip forward button, the clock does not change time when the skip forward button is pressed. In other sims with a clock the skip forward button advances the time by 2/10 of a second. This change is reflected in the clock. However this sim does not change the clock when the skip forward button is pressed. This issue is most visible when a skater is on the track and the skip forward button is pressed, where the skater is moving but the clock shows that no time has elapsed.

**Comment by jessegreenberg** [comment]
Thanks very much @JRomero0613, fixed in the above commit.
