### ISSUE TITLE
When playing back previously recorded actions Skater is leaning to the side

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/energy-skate-park#178]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470

When on the graphs screen and "Time" is selected, if the skater is manipulated it appears to be leaning to the side when played back.
**Steps to reproduce**
1. Enter the Graphs screen
2. Switch from Position to Time on the graph
3. Drop the skater onto the track
4. Lift up the skater and move it around
5. Manipulate the blue line to playback previous actions and observe
**Visuals**
![2020-02-04SktePrk](https://user-images.githubusercontent.com/54685448/73786395-69711680-4756-11ea-9012-3116ad538cb2.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html?showPointerAreas
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks @loganbraywork, I will take a look.

**Comment by jessegreenberg** [comment]
When the skater is dragged we zero the kinetic energy. I think we also need to reset the angle.

**Comment by jessegreenberg** [comment]
Hmm, it seems like we are already doing that.
