### ISSUE TITLE
Pointer Area for Measuring device strange shape

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/energy-skate-park#179]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470

The Pointer area for the movable portion of the measurement device on the Measurement screen is a strange shape, and will randomly change to either conform to the actual shape of the object and back.

**Steps to reproduce**
1. Use the query parameter ?showPointerAreas
2. Enter the Measurement screen
3. Manipulate the measurement device and observe

**Visuals**
![2020-02-04SktePrkPntrArea](https://user-images.githubusercontent.com/54685448/73787749-22d0eb80-4759-11ea-9f63-c1fed788bcd3.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html?showPointerAreas
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Same issue as in https://github.com/phetsims/scenery-phet/issues/488

**Comment by jessegreenberg** [comment]
Thanks for reporting. Indeed, this is the same as https://github.com/phetsims/scenery-phet/issues/488, and was determined to be an issue with our tool and not the actual pointer areas. Closing.
