### ISSUE TITLE
Total redundant on Energy Legend for Pie Chart

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/energy-skate-park#180]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10 
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470

The pie chart legend contains the key "Total", which is redundant for the pie chart since it never displays the Total energy, only thermal, potential, and kinetic, unless reference height is moved, wherein it shows a transparent version of the total energy. 
**Steps to reproduce**
1. Open the pie chart on either the Intro, Measure, or Lab screen.
2. Note that Total never appears in the pie chart, and on Measure the bar graph is removed so Total never appears at all on that screen.
**Visuals**
![2020-02-04SktePrkDsgn](https://user-images.githubusercontent.com/54685448/73793923-93c9d080-4764-11ea-864a-813a057036e0.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks for reporting @loganbraywork.
> unless reference height is moved, wherein it shows a transparent version of the total energy

In my opinion, this part makes the total energy important to display.

**Comment by arouinfar** [comment]
>> unless reference height is moved, wherein it shows a transparent version of the total energy
>
>In my opinion, this part makes the total energy important to display.

I completely agree @jessegreenberg. 

Pie charts are not designed to handle negative values, so it was a real challenge to decide what to do when the skater has negative potential energy (see #20). We could think of three options:
1. Hide the pie chart when PE < 0. This was the behavior in Java, which we felt looked really jarring.
2. Show only the total energy when PE < 0. This emphasizes that the total energy in the system doesn't change.
3. Find some novel way to represent negative values in a pie chart. 

I've made a note to mention this in the teacher tips, so closing.
