### ISSUE TITLE
Energy charts don't update when reference line is changed while paused

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#182]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470.
When the sim is paused, the energy representation in the bar and pie charts updates as you drag the skater up and down. However, it does not change as you move the reference height. You need to step forward for it to update

**Visuals**
![updatebargraph](https://user-images.githubusercontent.com/41024075/73878519-e9ab8080-4817-11ea-9169-c5cf71258aac.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by loganbraywork** [comment]
Pie chart and Energy graph also fail to update when paused if gravity is changed as well

**Comment by jessegreenberg** [comment]
Thanks @loganbraywork. It does however update while paused when mass changes. So I suspect that it should. I will go ahead and do that, but @arouinfar please let me know if you disagree.

**Comment by jessegreenberg** [comment]
Fixed in the above commit. Energies update when the sim is paused if mass, reference height, skater height, or gravity change. But @arouinfar can you still review? I have a memory of discussing this and I am afraid maybe I am forgetting a reason that they shouldn't.

**Comment by arouinfar** [comment]
Nice catch @KatieWoe.

@jessegreenberg I definitely think we should be updating the pie chart and bar graph whenever the reference line is moved, including when the sim is paused.

What gets tricky is how we handle the E(x) and E(t) graphs. In these graphs, moving the reference height will only affect the data drawn after the line was moved. Given the real-time nature of these graphs, that seems acceptable. However, handling the paused case is less straight-forward. Currently, pausing the sim clears the data from the E(x) and E(t) graphs. I don't think we should be doing that. Users may pause the sim to get a closer look at the graphs. 

That said, I don't really know what we should do about moving the reference height when the sim is paused. I can think of two options:

1. Do nothing. Only data drawn <i>after</i> moving the reference line would be affected. (Java behavior)
2. Clear the graph. 

I don't love either option, but I think (1) is likely the better choice here. @ariel-phet what would you recommend?

**Comment by jessegreenberg** [comment]
> Currently, pausing the sim clears the data from the E(x) and E(t) graphs.

Sorry, this is a bug in master after commit https://github.com/phetsims/energy-skate-park/commit/307889e030fe65ed938cae374797ee99b3f75276 and is not in https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html. That was not intended.

I also prefer (1).

**Comment by jessegreenberg** [comment]
> Sorry, this is a bug in master

Fixed in https://github.com/phetsims/energy-skate-park/commit/510893fe9af416b2adaea4a610489845cdd98cd3

**Comment by ariel-phet** [comment]
@arouinfar @jessegreenberg in reference to https://github.com/phetsims/energy-skate-park/issues/182#issuecomment-583172866 I think we should go with (1). That behavior seems correct to me. 
 
I think the graph should correspond to the reference height at the time of taking that data. So I see no problem with the graph not changing until after the pause, if the reference height is changed during a pause.

**Comment by jessegreenberg** [comment]
OK thanks - I belive that is the  behavior of master, @arouinfar can you confirm?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. Looks good in master.
