### ISSUE TITLE
Pie chart can obscure the skater if skater is upside down

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/energy-skate-park#184]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470

When the skater is upside down on a track the pie chart can obscure it. 
**Steps to reproduce**
1. Enter the Lab screen
2. Create a circular track
3. Use the gravity slider to turn gravity to max
4. Use the friction slider to turn friction to None
5. Ensure the Stick to Track checkbox is ticked
6. Tick the Pie Chart checkbox
7. Place skater at at the top of the track and release
<details><summary><b>Visuals</b></summary>
Apologies about the lag, recording software causes it, not indicative of the sim performance. </details>

![2020-02-05SktePrkDsgn](https://user-images.githubusercontent.com/54685448/73881322-5412ef80-481d-11ea-9e89-6dd90ede55ff.gif)

<details><summary><b>Troubleshooting information:</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {
</details>

**Comment by jessegreenberg** [comment]
Thanks @loganbraywork - the current behavior is to put the pie chart 50 view coordinates above the head, always. 

The reason for this is so that the pie chart looks good when on an angled track (like the porabola)
![image](https://user-images.githubusercontent.com/6396244/73886018-ca701b80-4836-11ea-8135-8b04f1d658f2.png)

We could try putting it 50 view coordinates below the skater when upsidown. The gif in this example shows that the pie chart would then be underground. @arouinfar is it worth exploring different behaviors?

**Comment by arouinfar** [comment]
Nice attention to detail @loganbraywork.

> We could try putting it 50 view coordinates below the skater when upsidown.

Originally I had a similar idea, but I think it would look pretty jarring to shift the position of the chart once the skater ends up upside down.

While it's true the pie chart can end up underground, I think it will generally remain visible throughout the skater's motion. 
![piechart](https://user-images.githubusercontent.com/8419308/73988862-315a0700-4901-11ea-8635-ada7d0872d9e.gif)

I think this is a bit of an edge case, and I'm happy with how the pie chart is generally positioned. I'm hesitant to do anything here. @jessegreenberg if you're okay with that, please feel free to close as `type:wontfix`.

**Comment by jessegreenberg** [comment]
OK  thanks @arouinfar.
