### ISSUE TITLE
Design Recommendation: Change 0 kg to <1 kg

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#185]
For https://github.com/phetsims/QA/issues/470 I noticed that, on screens with a mass slider, you can set the mass of the skater to 0 kg. However, skater still falls, has kinetic energy, and behaves as if it has mass. I think it would make more sense for that lower bound to be <1 kg or a more specific decimal value.
![zeromass](https://user-images.githubusercontent.com/41024075/73883235-d2bd5c00-4820-11ea-8046-8e321504a5dc.png)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe , Im not sure why current range allows it to go all the way to zero.

**Comment by arouinfar** [comment]
@jessegreenberg I think 1.0 kg would be an appropriate minimum for mass.

**Comment by jessegreenberg** [comment]
This is done as part of #81
