### ISSUE TITLE
Time moves forward when dragging the skater

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#186]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470.
On the Graphs screen, when looking at the time version of the energy graph, you can get time to behave as if it is moving even when paused. To do this you just drag the skater around, or even just hold down your mouse on the skater.
**Steps to reproduce**
1. Go to the Graph screen
2. Switch the graph to time
3. Pause the sim
4. Drag the skater around

**Visuals**
![timekeepsmovingforward](https://user-images.githubusercontent.com/41024075/73885540-347fc500-4825-11ea-9525-d0ebb1087cbc.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Definitely a but, thanks for reporting. Ill take a look.

**Comment by jessegreenberg** [comment]
Interesting it is only happening for the energy vs time graph.

**Comment by jessegreenberg** [comment]
@KatieWoe can you please make sure this is fixed in master?

**Comment by KatieWoe** [comment]
This looks fixed on master

**Comment by jessegreenberg** [comment]
Thank you, closing.

**Comment by jessegreenberg** [comment]
This fix made it so that all data is cleared on pause.

**Comment by jessegreenberg** [comment]
New fix in the above commit.
