### ISSUE TITLE
Raised tracks now cover graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#189]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470. Related to https://github.com/phetsims/energy-skate-park/issues/115, which involves extending the fixed track on the graphs screen by continually manipulating the three point track under the ground to push it up. This was decided to not be fixed. However, the tracks now layer on top of, instead of beneath, the graph. This looks much more odd and could pose more of a problem.
**Steps to reproduce**
Same as https://github.com/phetsims/energy-skate-park/issues/115

**Visuals**
![trackinfront](https://user-images.githubusercontent.com/41024075/73891052-93970700-4830-11ea-98ba-32eab242f95d.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, ill take a look.

**Comment by KatieWoe** [comment]
Interestingly it does stop going up at a certain point:
![stopsgoingup](https://user-images.githubusercontent.com/41024075/73892091-2769d280-4833-11ea-9dcb-5b2f3db2c6dd.png)

**Comment by jessegreenberg** [comment]
Thanks for verifying! We did decide to fix this, it is just that the limiting bounds are too large for the graphs screen. Can you please check to see if this is fixed in master?

**Comment by KatieWoe** [comment]
Looks fixed in master

**Comment by jessegreenberg** [comment]
Great, thanks for checking.
