### ISSUE TITLE
Still possible for track to be below ground

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/energy-skate-park#191]
**Test Device**

MacBook Air

**Operating System**

macOS 10.15.2

**Browser**

Firefox 72.0.2

**Problem Description**

For https://github.com/phetsims/QA/issues/470. I searched the ESP repo and the ESPB repo, but I didn't find this exact issue. If it exists, sorry for the duplicate.

That being said, see title and gif.

**Steps to Reproduce**

I don't think there's a sequence of steps that will guarantee reproduction of this bug. (Thus, it might be a rare bug.) You just have to fiddle with a track to get this to happen.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/73896008-c0eab180-483e-11ea-9e94-6cb815c0856d.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html?profiler
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0
Language: en-US
Window: 1440x826
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Found a track where this is happening: 
![image](https://user-images.githubusercontent.com/6396244/73904373-d88b5f80-4869-11ea-837e-ebe78bcebc1a.png)

Control points:
var controlPoints = [new ControlPoint(-1.5792371376866505,8.918939632639875),new ControlPoint(1.1724084337323326,8.904145784631758),new ControlPoint(3.495033259423506,8.297600273652469),new ControlPoint(3.9832288328454144,3.785493843497259),new ControlPoint(3.6281776093273646,1.1374054903042672),new ControlPoint(1.8233354887359692,0.20787218277436187),new ControlPoint(-3.0586162951145885,0.111797493183142),new ControlPoint(-5.1297468333445195,2.868167527719518),new ControlPoint(-5.4995919048706865,11.674398558758316)];

It seems like when this happens  there is a control point at the edge of the visible bounds. My guess is that we are trying to bump the track above ground, but then move control points back  in visible bounds, which produces a track that has a point slightly below ground.

**Comment by jessegreenberg** [comment]
That theory matches the order of bumpAboveGround
```js
    bumpAboveGround() {
      const lowestY = this.getLowestY();
      if ( lowestY < 0 ) {
        this.translate( 0, -lowestY );
      }

      // contain control points in limiting drag bounds (if control points have them specified) so that bumping above
      // ground doesn't push control points out of these bounds - do this without updating splines since we will
      // do that anyway in containControlPointsInAvailableBounds
      this.containControlPointsInLimitBounds( false );
      this.containControlPointsInAvailableBounds( this.availableModelBoundsProperty.get() );
    }
```

**Comment by jessegreenberg** [comment]
Another issue here seems to be precision. If the track has its lowestY at something like -1E-16, bumping above ground by that much will still produce a track with its lowestY at around -1E-16. Since thhis is still below zero,  the skater could hit ground in that case.

**Comment by jessegreenberg** [comment]
@lmulhall-phet the above commit should fix this, can you please confirm?

**Comment by jessegreenberg** [comment]
I am assuming this is fixed now, closing.
