### ISSUE TITLE
Points on energy graph exceed bounds of energy graph

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/energy-skate-park#194]
**Test Device**

MacBook Air

**Operating System**

macOS 10.15.2

**Browser**

Chrome 79.0.3945.130

**Problem Description**

The points on the energy graph can exceed the bounds of the energy graph if some conditions are met.

**Steps to Reproduce**

1. Graphs screen.
2. Increase mass to maximum value.
3. Place skater at the very top of the ramp.

There are other mass values that can produce this issue. This happens with the other types (colors) of points as well.

**Visuals**

![issue1](https://user-images.githubusercontent.com/31285590/74383066-bc2c7d00-4dab-11ea-9395-e3fec1418a86.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet - this is useful, but also part of #101 so I am going to close this and reference over there.
