### ISSUE TITLE
Total Energy Increases Over Time

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#2]
Unfuddle ticket [#1033](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/1033)

Reported by a user:
> When running the Energy skate park program with the display in the time mode
and monitoring the total energy as the skateboarder moves up and down, the
total energy very slowly increases after some ten or so cycles.  I did a
weak effort at suggesting that the computation might be "rounding up" and
that Colorado was not suggesting that the skateboarder was creating energy.
Thanks
p.s. possibly the skateboarder was converting some of his internal energy
into the total of those that you were monitoring

In the history I see
> Sam R. on Apr 22, 2009
Severity changed from <none> to Defect: Physics Bug.

@samreid looks like this is something to be on the lookout for when porting the model.

**Comment by jessegreenberg** [comment]
@arouinfar I don't think this is an issue in HTML5 version. I just tried with the "measure" screen and after many oscillations I could see that the total energy was conserved. Can this be closed?

**Comment by arouinfar** [comment]
I'm also unable to see this in the HTML5 version. Let's close.
