### ISSUE TITLE
Handling Negative PE in Pie Chart

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#20]
The issue of negative PE cropped up in https://github.com/phetsims/energy-skate-park-basics/issues/432, which lead me to review the discussion for ESP.

In the 3/1/18 design meeting, we discussed how to express negatives in the pie chart

> Team would be ok with displaying the total as a solid color (matching Total Energy) but with dashed stroke or reduced opacity to look a bit ethereal. If the pie chart has problems in interviews, it can be removed.
![image](https://user-images.githubusercontent.com/8419308/43108903-55d9848c-8ea1-11e8-8423-0fd69b51fafe.png)

Here's a rough video showing what that would look like in action. The zero point for GPE is at the local maximum between the troughs. (The skater was released from the right side of the track at 3m, but I didn't animate the entire motion.)

![totale](https://user-images.githubusercontent.com/8419308/43159788-9a1356e2-8f40-11e8-931f-34d42b46f2f0.gif)

After the 3/1 design meeting @samreid and I discussed an alternative representation. When the the PE is negative, the pie chart could continue to represent the relative proportions of energies, using abs(PE). Let's suppose that the total energy in the system is 3 units. When PE is -1 unit, the KE must be 4 units, so the pie chart would display 20% PE and 80% KE.
![image](https://user-images.githubusercontent.com/8419308/43168835-e861be9a-8f5b-11e8-90bb-86d8265f14bd.png)

Here's what it would look like in context:
![negativegpe](https://user-images.githubusercontent.com/8419308/43159789-9a29898a-8f40-11e8-9567-f3d356dccdb0.gif)

This representation would allow students to see the magnitude of the PE growing as it gets further from the zero-point. However, the bar graph could also achieve this goal. If analyzing the pie chart on its own, the KE appears to be maximum at 0 m because it is at 100%. Students may find it hard to explain why the KE appears to decrease when at the bottom of the trough, so I think that displaying the total energy is a better way to go.

Tagging for design meeting discussion when ESP meetings resume.

**Comment by jessegreenberg** [comment]
@arouinfar also said that for the yellow "total" energy display in the pie chart with negative values, we should include an entry in the Pie chart legend for total energy.

**Comment by jessegreenberg** [comment]
@arouinfar should the yellow "total energy" representation be used for cases like https://github.com/phetsims/energy-skate-park-basics/issues/189 in energy-skate-park-basics or should it be invisible?

**Comment by jessegreenberg** [comment]
This is done in master, I made it optional so that the pie chart can be invisible or show total energy distribution.

**Comment by jessegreenberg** [comment]
Done for PieChartNode, I still need to do this for PieChartWebGLNode.

**Comment by arouinfar** [comment]
@jessegreenberg I tested with `?webgl=false` and the behavior of the pie chart is looking good!

> @arouinfar should the yellow "total energy" representation be used for cases like phetsims/energy-skate-park-basics#189 in energy-skate-park-basics or should it be invisible?

I think the total energy representation would be more consistent, so let's go with that.

> I made it optional so that the pie chart can be invisible or show total energy distribution.

Sounds good! I imagine this could be useful for PhET-iO clients.

**Comment by jessegreenberg** [comment]
The negative energy circle is stroked with a dashed line, and I have been trying to get that to work with WebGLNode. I tried a new shader that discards fragments outside of the dashes, but I couldn't get it to work out and I don't think that is the right way to go about this now.

I tried a new Node using gl.TRIANGLES and it is working pretty good, but I am getting some psychedelic coloring effects.
![capture](https://user-images.githubusercontent.com/6396244/47157275-f91b5900-d2b6-11e8-92e4-c7019e5d1093.PNG)

**Comment by jessegreenberg** [comment]
I found the cause of the strange coloring, but realized that this method of drawing the dashes wont work because the pie chart needs to be semi-transparent when potential energy is negative. Ill try a different way with gl.TRIANGLE_STRIP.

**Comment by jessegreenberg** [comment]
That looks pretty nice and handles opacity.I found a bug where potential energy doesn't update the pie chart sometimes when dragging the skater.

**Comment by jessegreenberg** [comment]
I think this part has been added, @arouinfar are there follow up steps for this issue?

**Comment by jessegreenberg** [comment]
Good point, Ill take a look. I have a slight preference for the shorter dashes, Ill try making the webgl dashes look shorter.

**Comment by jessegreenberg** [comment]
Hmm, when I make the dashes shorter some of theme disappear.
![capture](https://user-images.githubusercontent.com/6396244/47169722-3d682280-d2d2-11e8-828e-582902664d76.PNG)

**Comment by jessegreenberg** [comment]
I added more dashes to the outline so it looks more similar to the non-webgl pie chart. @arouinfar back to you to review.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I think those are close enough. :)
