### ISSUE TITLE
Update author annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#203]
From https://github.com/phetsims/energy-skate-park/issues/202, it would be nice to add `@author` annotations as appropriate.

**Comment by samreid** [comment]
To be more specific, there are many files with probably should add `@author Jesse Greenberg (PhET Interactive Simulations)`

**Comment by jessegreenberg** [comment]
I added myself as author to many files which were touched by me in energy-skate-park.
