### ISSUE TITLE
GridNode should be common code

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#205]
Discovered during #202, Energy Skate Park has a GridNode.  We now have nearly 9 simulations with types named `GridNode` or similar.  Should this be factored out into common code?  I can see that Energy Skate Park has special customizations of the GridNode, but perhaps those could be options or decorations instead of a whole new reimplementation.

**Comment by jessegreenberg** [comment]
That sounds great, I started https://github.com/phetsims/scenery-phet/issues/580 for this.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/issues/580 is done and is ready for review. energy-skate-park GridNode was renamed to EnergySkateParkGridNode and is now using scenery-phet/GridNode.

GridNode and its usage is reassigned for review in https://github.com/phetsims/scenery-phet/issues/580 so I feel like this can be closed.
