### ISSUE TITLE
Performance problems when "Grid" is enabled

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#206]
On MacOS Catalina 10.15.3 (19D76) running Chrome Version 80.0.3987.122, performance is very smooth until the Grid is enabled.  When the grid is enabled, performance becomes stuttery/juddered/janky.  Is this a known problem?  Can it be improved?

**Comment by jessegreenberg** [comment]
Thanks, not a known problem. Ill take a look.

**Comment by jessegreenberg** [comment]
I see that the grid uses a `clipArea`, that has often been a source of performance burden for me. Ill see if removing that improves things.

**Comment by jessegreenberg** [comment]
The grid was reimplemented for #205 and I wonder if it will be faster now. It is no longer using clipping.

**Comment by jessegreenberg** [comment]
Testing on macOS Catalina 10.14.4, I don't notice too much of a slowdown when the grid is enabled, but overall the sim performance is generally pretty choppy. I think I would like to investigate https://github.com/phetsims/energy-skate-park/issues/213 before narrowing in on the grid specifically.

**Comment by jessegreenberg** [comment]
In #213 I worked on performance with macOS Catalina and reported
> The profiler is reporting 50-60 fps on all screens (with/without grid and other things visible). I think this can be closed.

This issue can be closed.
