### ISSUE TITLE
Memory footprint is higher than normal

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#208]
While reviewing https://github.com/phetsims/energy-skate-park/issues/202, I noticed that the sim memory footprint on startup is around 155MB (on Mac Chrome).  Compare this to a few other sims:

ESPB: 155MB
Energy Forms and Changes: 19MB
Number Line Integers: 24MB
States of Matter: 18MB

On the other hand, I noticed Gas Properties is up around 153MB--but maybe that should be investigated too?

**Comment by jessegreenberg** [comment]
I am seeing that energy-skate-park is a bit more memory heavy, but not by such a large margin.

Built
ESP: 43.1MB on startup
EFAC: 22MB on startup
states-of-matter: 19.3
gas-properties: 37 MB

Unbuilt:
ESP: 38 MB
EFAC: 20.5
states-of-matter: 18.6MB
gas-properties: 37.8MB

energy-skate-park and gas-properties have four screens, which could explain their larger size. Checking other 4 screen sims (all unbuilt):
area-model-algebra: 36.8MB
buyancy (5 screens): 40.2 MB
equality-explorer (5 screens) 46.1MB
expression-exchange: 46.4MB

So I feel like the memory footprint is about what we would expect for this sim. Reassigning to @samreid to review.

**Comment by samreid** [comment]
That seems reasonable, thanks for checking on this.  Closing.
