### ISSUE TITLE
Should this simulation use phet-core/EventTimer?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#209]
Discovered during https://github.com/phetsims/energy-skate-park/issues/202, I noticed that several simulations use EventTimer in order to provide smoother motion.  Should we use it in this simulation as well?

@jonathanolson can you comment on general heuristics to determine when EventTimer should be used in a simulation?

**Comment by jonathanolson** [comment]
Generally if a simulation uses a fixed-time model step somewhere, it's best to use EventTimer to compensate for varying frames.

**Comment by jessegreenberg** [comment]
> if a simulation uses a fixed-time model step somewhere, it's best to use EventTimer to compensate for varying frames.

And ESP does.
```js
    // This simulation uses a fixed time step to make the skater's motion reproducible.  Making the time step fixed
    // did not significantly reduce performance/speed on iPad3.
    dt = 1.0 / 60.0;
```

Ill take a look at using EventTimer.

**Comment by jessegreenberg** [comment]
I used EventTimer in this sim and I think it is working well. The result is a different behavior on slower platforms. Rather than time slowing down, the sim looks choppier. I think this is better altogether, because it prevents the skater from looking like it slows down when there is a larger performance burden. 

@samreid would you mind reviewing this change?

**Comment by samreid** [comment]
I reviewed the implementation and compared to the implementation in Projectile Motion and it seemed reasonable.  I also tested normal mode and with 6x throttle.  This issue is probably good to close but part of me think it would be wise to run it past @jonathanolson if he has time to take a quick look.

**Comment by jonathanolson** [comment]
The commit looks good to me.
