### ISSUE TITLE
Ready 1.3-phetio branch for interaction study

### ISSUE THREAD

**Issue by zepumph** [phetsims/energy-skate-park#21]
@kathy-phet @DianaTavares are looking to do an interaction study with ESPB just like what we are doing with FAMB in https://github.com/phetsims/forces-and-motion-basics/issues/259.

Details of the study:
* First two screens only
* Data collection to start Sept 25th
* draft version ready by week of the 17th (not sure when within this)
* Same link as with FAMB (in an iframe pointing to the login wrapper)

same link means all the same query parameters, which don't exist in this branch either.

@DianaTavares please comment if there are any differences between the link you have gotten for FAMB, and what you expect for ESPB. Same login as 7 digits? Same `emitStatesInterval` about once a second?

UPDATE: this issue is in the wrong repo, it should be in basics.

**Comment by zepumph** [comment]
I was about to easily add the iframe wrapper with a cherry-pick, but things like updating the login wrapper will be a bit more extensive. (good luck me).

**Comment by DianaTavares** [comment]
Yes, with this sim is the same characteristics that with the FAMB: link that open a new window with the sim in the iframe and the login with 7 digits. 

The idea again is to get the same visualizations that we already has in the dashboard.

**Comment by DianaTavares** [comment]
and we are going to need also two links 1110_guided and 1110_exploration

**Comment by zepumph** [comment]
Was able to retrofit 1.3-phetio branch basically by following the commits done for FAMB in phetsims/forces-and-motion-basics#259. I recorded a few testing sessions. From there I will (a) look how to playback recordings, and (b) testing the preprocessing for the Interaction Dashboard.

**Comment by zepumph** [comment]
- [ ] We will want to cherry-pick https://github.com/phetsims/phet-io/commit/ec2f338191895b6d5d167d7038c5676c1583b562 into this release as well.

**Comment by zepumph** [comment]
QA has finished, I updated the qa credits. It is time to publish the sim now.

**Comment by zepumph** [comment]
@DianaTavares @kathy-phet here are the final links for ESPB:

```
final links:
Exploration:
<a href="https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.6-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=1,2&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=energy-skate-park-basics-1110_exploration-0925 &phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&metacog" target="_blank">link to the simulation Energy Skate Park: Basics</a>

Guided:
<a href="https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.6-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=1,2&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=energy-skate-park-basics-1110_guided-0925 &phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&metacog" target="_blank">link to the simulation Energy Skate Park: Basics</a>

test:
<a href="https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.6-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=1,2&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=energy-skate-park-basics-finaltest&phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&metacog" target="_blank">Test with this link</a>

**Comment by DianaTavares** [comment]
Perfect! thanks everybody! I use the test-link and its working very well. Ready to put the links in the activity :D
