### ISSUE TITLE
Should model.md describe more parts of the model?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#210]
Discovered during https://github.com/phetsims/energy-skate-park/issues/202.  It seems model.md only has the following equations:

> Ff = μ * N
> KE = 0.5 * m * v2
> PE = m * g * h
> TE = Ff * d
> T = KE + PE + TE

Should we describe some or all of the following?

* The Tracks are modeled via cubic splines (this is mentioned in the implementation notes though)?
* The equation for motion F=ma, and the integration algorithm?
* How it is determined whether the skater "goes off a jump" or falls when upside down? (Circular motion approximation)?
* Energy is conserved unless the user is dragging the skater or a track the skater is on, or dragging the potential energy reference point?
* Mention how the skater is treated as a point mass?  Where is the centroid of the mass?
* Mention that rotations and rotational inertia are not modeled?

**Comment by jessegreenberg** [comment]
I tried to summarize each of these in model.md, @samreid could you take a look? The only one I didn't try to add was
>How it is determined whether the skater "goes off a jump" or falls when upside down? (Circular motion approximation)?

I am not familiar with the "circualr motion approximation".

**Comment by samreid** [comment]
For the circular motion approximation, we treat the part of the track as if it is a circle (where we compute the radius of curvature based on local estimation), then we use a=v^2/r like in http://farside.ph.utexas.edu/teaching/301/lectures/node91.html

Other changes look great, thanks!

**Comment by jessegreenberg** [comment]
Cool, I added a note about the circular motion approximation in the section about skater motion. CLosing.
