### ISSUE TITLE
Several links in implementation-notes are broken

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#211]
While reviewing #202, I noticed that many links in the implementation-notes.md are broken.  For instance:

https://github.com/phetsims/energy-skate-park/blob/master/js/common/model/EnergySkatePark.js
https://github.com/phetsims/energy-skate-park/blob/master/js/common/model/Skater.js
https://github.com/phetsims/energy-skate-park/blob/master/js/common/model/Track.js

are all hyperlinked, but they are showing up as "Page not found".

**Comment by jessegreenberg** [comment]
I was going to update links, but realized that proceeding with https://github.com/phetsims/energy-skate-park/issues/222 would break them all again. Any similar move or rename would break all of these. So they are something else to maintain and I don't think they are all that helpful. I am going to remove the links and just give information about where to find more information in implementation-notes.md.

**Comment by jessegreenberg** [comment]
Links referencing types in this sim have been removed.
