### ISSUE TITLE
GaugeNode.updateNeedle is called and taking up CPU even when the GaugeNode is not displayed

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#212]
Discovered during #202, I noticed this code in the profile running even when the GaugeNode was not selected:

![image](https://user-images.githubusercontent.com/679486/75703388-9ab90580-5c74-11ea-930c-405de181921d.png)

I wonder if we can avoid that cost when the GaugeNode is not displayed?  A reminder to additionally call updateNeedle when it is shown so it is correct right away without waiting for another delta.

**Comment by jessegreenberg** [comment]
The gauge in this sim is using the feature `enabledProperty` feature of GaugeNode
```js
    // {BooleanProperty|null} Determines whether the gauge will be updated when the value changes.
    // Use this to (for example) disable updates while a gauge is not visible.
    // If null, BooleanProperty(true) will be created.
    enabledProperty: null,
```

And I confirmed that when the gauge is not visible we are not doing any of the work in `updateNeedle`, so I think this can safely be closed.

**Comment by samreid** [comment]
Thanks, I also confirmed that `updateNeedle` is not being called when that checkbox is deselected.  Not sure what I saw before, sorry for the false alarm.  Closing.
