### ISSUE TITLE
Should checkbox icons be clickable?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#214]
Discovered in the "usability" section of #202.  I noticed that some PhET simulations allow you to click on the icon next to checkbox text, such as Gas Properties:

![image](https://user-images.githubusercontent.com/679486/75804037-a66fff00-5d3c-11ea-9644-e5b84b7d9306.png)

However, in Energy Skate Park, clicking on the icons next to checkbox text does nothing:

![image](https://user-images.githubusercontent.com/679486/75804078-b4258480-5d3c-11ea-951a-0aa8b8890fd2.png)

Wouldn't it be more user-friendly and easy-to-use if you could click on the icons?

**Comment by jessegreenberg** [comment]
Something similar to https://github.com/phetsims/energy-skate-park/issues/214#issuecomment-595505403 was done in the above commit.

**Comment by jessegreenberg** [comment]
Hmm, some of the icons still aren't clikcable.

**Comment by jessegreenberg** [comment]
I think this is happening because icons text and icon AlignBoxes are created then immediately used for checkbox content before the rest of the boxes are created.  AlignGroup supports this by resizing, but Checkbox makes things pickable by adding a Rectangle around content on construction then making icons unpickable.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/energy-skate-park/issues/214#issuecomment-607916921 is correct, and the above commit fixes this by creating all checkbox icons and labels in their alignboxes before creating checkboxes. It seems that checkboxes do not support icons with variable dimensions. This is working well now, closing,.
