### ISSUE TITLE
The pointer area shows incorrectly for the meter node

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#215]
From #202, it looks like this:

![image](https://user-images.githubusercontent.com/679486/75804444-2f873600-5d3d-11ea-980e-7317b4a7bf9c.png)

Is there an issue for that?

**Comment by arouinfar** [comment]
See https://github.com/phetsims/scenery-phet/issues/488

**Comment by samreid** [comment]
Thanks!  It makes sense to place this issue on hold pending a fix in the scenery-phet issue.

**Comment by arouinfar** [comment]
I noticed that the scenery-phet issue had been closed, but it the fix is being tracked in https://github.com/phetsims/kite/issues/77.

**Comment by samreid** [comment]
I pushed a fix for https://github.com/phetsims/kite/issues/77.

**Comment by samreid** [comment]
Fix confirmed in https://github.com/phetsims/kite/issues/77, closing.
