### ISSUE TITLE
Why is the mouse cursor a "right arrow" when I can drag the chart slider to the left?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#216]
From #202 in the "Usability" section.  Why is the mouse cursor a "right arrow" when I can drag the chart slider to the left?

![image](https://user-images.githubusercontent.com/679486/75805845-cfde5a00-5d3f-11ea-88e6-72330b338379.png)

**Comment by arouinfar** [comment]
@jessegreenberg let's use a double-headed arrow (like Neuron).

**Comment by jessegreenberg** [comment]
Interesting, ESP uses the same cursor as neuron ("e-resize") and on my machine it looks like a double headed arrow:
![image](https://user-images.githubusercontent.com/6396244/78307803-ca2d8d00-7514-11ea-833d-e8bb08a332ea.png)

**Comment by jessegreenberg** [comment]
I think what we want to be doing is "ew-resize" which indicates bidirectional resize.

**Comment by jessegreenberg** [comment]
Change made to griddle's XYCursorPlot above, @arouinfar @samreid can you verify it looks better?

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks for checking @arouinfar. Since you were able to verify the cursor on a Mac I am going to go ahead and close.
