### ISSUE TITLE
Why do the scissors sometimes point toward the control point and sometimes point away?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#217]
From #202 in the Usability section.  Why do the scissors sometimes point toward the control point and sometimes point away?

![image](https://user-images.githubusercontent.com/679486/75805982-17fd7c80-5d40-11ea-82c6-665f5d0136d8.png)

![image](https://user-images.githubusercontent.com/679486/75806038-2f3c6a00-5d40-11ea-9da6-41d147f82295.png)

It would be nicer if the scissors always pointed toward the control point.

**Comment by arouinfar** [comment]
This exists in the latest version of ESPB, but was not present in the [1.0.0 ](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.0.0/energy-skate-park-basics_en.html) release. The preferred orientation would be for the scissor blades to point toward the control point:

![image](https://user-images.githubusercontent.com/8419308/75808287-15048b00-5d44-11ea-94cc-f6e4ae906b32.png)

**Comment by jessegreenberg** [comment]
I don't know why this stopped pointing to the control point, as this line and seemingly the code supporting it has been the same since the 1.0.0 release. But I don't think it is worth more time to investigate why behavior changed. The above commit fixes this.
