### ISSUE TITLE
Some pointer areas seem too small

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#218]
From #202.  For instance, the "clear thermal" button in the pie chart legend and bar chart, and the zoom in/out buttons in the bar chart.

![image](https://user-images.githubusercontent.com/679486/75806357-bab5fb00-5d40-11ea-9007-4faf49ec7844.png)

**Comment by jessegreenberg** [comment]
I increased the touch areas for these buttons. There isn't a ton of space for the zoom buttons, so I shifted horizontally to make them larger:
![image](https://user-images.githubusercontent.com/6396244/78187829-28873c80-743d-11ea-8150-aa4f7a4d8a42.png)

**Comment by jessegreenberg** [comment]
I inspected other bottons in the sim looking for small touch areas and the other buttons are either larger anyway or already have dilated touch areas.

@arouinfar can you make sure these touch areas are sufficient?

**Comment by arouinfar** [comment]
@jessegreenberg the dilated touch areas look good to me.
