### ISSUE TITLE
Planet names not i18nized

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#219]
From #202, the planet names are not i18nized:

![image](https://user-images.githubusercontent.com/679486/75806495-fbae0f80-5d40-11ea-8ede-01717099fc2c.png)

**Comment by jessegreenberg** [comment]
Thank you, fixed in the above commit
![image](https://user-images.githubusercontent.com/6396244/78189559-3ee2c780-7440-11ea-8a13-2fe8778620e5.png)
