### ISSUE TITLE
Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published.

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#220]
From #202 
Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published.

I'm seeing a lot of keys that have dots in them:

```
  "properties.speed": {
    "value": "Speed"
  },
  "small": {
    "value": "Small"
  },
  "controls.mass": {
    "value": "Mass"
  },
  "energy-skate-park.title": {
    "value": "Energy Skate Park"
  },
  "slow.motion": {
    "value": "Slow Motion"
  },
  "energy.thermal": {
    "value": "Thermal"
  },
  "energy.total": {
    "value": "Total"
  },
```

Perhaps this would be a good opportunity to exercise the new "structured strings" paradigm we introduced.

**Comment by jessegreenberg** [comment]
The above commit uses nested string keys. I don't feel like every file touched needs to be reviewed, but reassigning to @samreid to review the structure, if you wish. Otherwise this can just be closed.

**Comment by samreid** [comment]
I skimmed the strings file and the new structure looks great, thanks!  Closing.
