### ISSUE TITLE
Translated strings shouldn't contain mass values

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#221]
During #202 I saw this:

```
  "controls.skater1Mass": {
    "value": "Skater 1 (60 kg)"
  },
  "controls.skater2Mass": {
    "value": "Skater 2 (35 kg)"
  },
  "controls.skater3Mass": {
    "value": "Skater 3 (40 kg)"
  },
  "controls.skater4Mass": {
    "value": "Skater 4 (65 kg)"
  },
  "controls.skater5Mass": {
    "value": "Skater 5 (80 kg)"
  },
```

Putting mass values in the translated strings will make it difficult or impossible for us to change those values in the code.  The masses should be removed from the strings using `{{}}` pattern.

**Comment by jessegreenberg** [comment]
That is a really good point, thank you. Done in the above commit.
