### ISSUE TITLE
Extraneous "js/energy-skate-park" subdirectory

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#222]
From #202 the "Is the js/ directory properly structured?" section indicates directory structure like this:

```
   my-repo/
      js/
         common/
            model/
            view/
         introduction/
            model/
            view/
         lab/
            model/
            view/
         my-repo-config.js
         my-repo-main.js
         myRepo.js
```

However, energy skate park has an extra "energy-skate-park" directory above everything.

Will renaming this now make it difficult to track `// REVIEW` comments across versions?  If so, this change should be done "last".

**Comment by samreid** [comment]
Same problem in energy-skate-park-basics.

**Comment by jessegreenberg** [comment]
Thanks to WebStorm this was a very easy refactor. Done in the above commits, closing.
