### ISSUE TITLE
Is there a file in assets/ for every resource file in sound/ and images/? 

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#223]
From #202, the code review checklist says:

> Is there a file in assets/ for every resource file in sound/ and images/? 

There are lots of new skater images in the images directory, but no commits to assets/ since May 2018.

**Comment by jessegreenberg** [comment]
Assets for all the new skaters have been added, and the artwork for original skater has been removed since it is no longer used in the sim.
