### ISSUE TITLE
Is the LICENSE file correct? (Generally GPL v3 for sims)

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#224]
From #202: Is the LICENSE file correct? (Generally GPL v3 for sims)

ESP specifies MIT, but it looks like it should be GPLv3

**Comment by jessegreenberg** [comment]
The MIT license is correct, sources of funding for this sim required that it be MIT license instead of GPL, see https://github.com/phetsims/energy-skate-park/issues/15.
