### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#225]
From #202 

> In GitHub, verify that all non-release branches have an associated issue that describes their purpose.

These branches are listed, they should probably be deleted before we publish 1.0?

1.0-deprecated
1.2-phetio
1.4-phetio
1.4-deprecated
1.3-phetio

**Comment by jessegreenberg** [comment]
Looks like these branches came from energy-skate-park-basics when we mirrored the repository. Over slack @samreid said that the "deprecated" branches can be deleted.

**Comment by jessegreenberg** [comment]
Furthermore, the phetio branches from energy-skate-park-basics may be used by partners, so those should remain in the basics repository. But all can be deleted from energy-skate-park.

**Comment by jessegreenberg** [comment]
Branches have been pruned, and only master remains in energy-skate-park. phetio branches remain untouched in basics.

**Comment by jessegreenberg** [comment]
These branches need to be re-deleted after manually deleted branches were restored accross the project/

**Comment by jessegreenberg** [comment]
These were re-deleted.
