### ISSUE TITLE
Get rid of all * @constructor annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#226]
The `* @constructor` annotations are no longer necessary now that we have a `constructor` keyword in ES6.  From #202

**Comment by samreid** [comment]
CRC says:

> ES5 (inherit) constructors should be annotated with @constructor. ES6 (class) constructors should not be annotated with @constructor.

**Comment by jessegreenberg** [comment]
Thanks, they have all been removed.
