### ISSUE TITLE
Too many separators

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#231]
Discovered in #202 ESPB has too many separators in the 1st screen:

![image](https://user-images.githubusercontent.com/679486/75821474-94518900-5d5b-11ea-8740-06b7d9c07a2b.png)

**Comment by jessegreenberg** [comment]
Thanks! Fixed in the above commit so that the layout works for the controls used in basics.

![image](https://user-images.githubusercontent.com/6396244/78812222-12c3cb00-7999-11ea-84a0-d6b093dbefac.png)
