### ISSUE TITLE
Should modifyBarHeight be rolled into each Property?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#232]
Discovered during #202, we saw that BarNode has an option `modifyBarHeight` and were wondering why this isn't a part of the `barEntry` Property--perhaps as a derived Property.  @jessegreenberg can you please take a look?

Also related to #160

**Comment by jessegreenberg** [comment]
`modifyBarHeight` was added to griddle for this case. It could potentially be removed to simplify the `barEntry`. Right now EnergyBarGraph works by modifying bar height if the height is less than some threshhold in *view coordinates*. By rolling into the Property, the modification would change to a *model coordinate* cut off. 

We could change the behavior, with DerivedProperties like
```js
    // NOTE: Not dependent on bargraph scale
    const derivedKineticEnergyProperty = new DerivedProperty( [ skater.kineticEnergyProperty ], energy => {
      return energy < THRESHOLD ? 0 : energy;
    } );
```

Keep the current behavior with DerivedProperties like 
```js
    const derivedKineticEnergyProperty = new DerivedProperty( [ skater.kineticEnergyProperty ], energy => {
      const resultantHeight = hideSmallValues( energy, barGraphScaleProperty.value );
      return resultantHeight === 0 ? 0 : energy;
    } );
```

Or leave as is.

**Comment by jessegreenberg** [comment]
I think I am leaning toward the second option to remove `modifyBarHeight` from griddle.

**Comment by jessegreenberg** [comment]
This was done, reassigning to @samreid to take a look. If this seems best, I will remove `modifyBarHeight` from griddle's BarNode.

**Comment by samreid** [comment]
This looks like the right way to accomplish it for now.  In the future if lots of several sims use this functionality, then we may come up with a nice way to do this across sims (perhaps through a common code DerivedProperty derivation or an API on griddle).  But for now this seems great.  Back to @jessegreenberg for discussion and/or to remove `modifyBarHeight` from griddle.

**Comment by jessegreenberg** [comment]
Sounds good, the optional modifyBarHeight option has been removed.
