### ISSUE TITLE
Rename floatInterface function

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#237]
A review comment for the `floatInterface` function of energy-skate-park ScreenViews is 
>// REVIEW: this should be named "layout"

`layout` is already a function of the ScreenView supertype so we cannot use that.  "float" seems like a conventional choice to describe what this layout function is doing.

Alternatives could include `floatLayout`, `floatControls`, `layoutControls`? @samreid do you have a preference or other ideas?

**Comment by samreid** [comment]
`ScreenView.layout` is called when the window resizes.  In the case of Energy Skate Park, `EnergySkateParkScreenView` extends `ScreenView` and overrides `ScreenView.layout` with its own implementation.  Would it work to put the body of `floatInterface` into the body of `EnergySkateParkScreenView.layout`?

Some other thoughts as a reference for when we discuss this further.  @jonathanolson and I discussed a dynamic layout strategy in https://github.com/phetsims/joist/issues/608 where we discussed a general function like `layout()` but I had forgotten that was already overloaded in ScreenView.  Thanks for pointing that out, I'll make a note of it there.

**Comment by samreid** [comment]
To elaborate more on the reason for recommending changes here: there are currently 2 channels for updating the layout.  `EnergySkateParkScreenView.layout` and `EnergySkateParkScreenView.floatInterface`.  The goal is to see if these can be combined and simplified.

**Comment by jessegreenberg** [comment]
OK that makes sense. In the above commits I move the work of floatInterface into layout so there is only one function that manages layouts for the screen views. Back to @samreid to review.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
