### ISSUE TITLE
Change how tracks are added to the EnergySkateParkPlaygroundModel from the toolbox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#239]
Related to #238, as this function is the usage of that field. From #202,
```js
    // REVIEW: Let's use the standard pattern of showing an icon in the control panel, then creating the model component
    // REVIEW: in the corresponding model location when dragged.
    const offset = this.initialTracksOffsetVector;
    const controlPoints = [
      new ControlPoint( offset.x - 1, offset.y, { tandem: controlPointGroupTandem.createNextTandem() } ),
      new ControlPoint( offset.x, offset.y, { tandem: controlPointGroupTandem.createNextTandem() } ),
      new ControlPoint( offset.x + 1, offset.y, { tandem: controlPointGroupTandem.createNextTandem() } )
    ];
    this.tracks.add( new Track( this, this.tracks, controlPoints, null, this.availableModelBoundsProperty, merge( {
        tandem: trackGroupTandem.createNextTandem()
      }, Track.FULLY_INTERACTIVE_OPTIONS )
    ) );
```

**Comment by jessegreenberg** [comment]
The track toolbox is currently just a rectangle that contains a TrackNode for each modelled track in https://github.com/phetsims/energy-skate-park/issues/239#issue-579560068. We should create a new class called TrackToolboxPanel that is responsible for creating the icon, input listeners, creating the new Track, new TrackNodes, then forwarding the input to the new TrackNode.

**Comment by jessegreenberg** [comment]
I would like for the icon to use TrackNode but currently the input listeners on the TrackNode make it so that the icon itself cannot forward a listener to a new TrackNode because the  Pointer becomes attached. Also, the TrackNode control points are only displayed if they are `draggable`, and therefore have listeners attached to them. I considered making a new icon Node that doesn't use TrackNode, but then it would need special logic  to update the icon when the skater can detach from the track.

I think we need to decouple `draggable` from `visible` on the ControlPoints so that we can have this visible icon use TrackNode, but not have any input listeners attached.

**Comment by jessegreenberg** [comment]
I am running into https://github.com/phetsims/energy-skate-park-basics/issues/205 again because our pattern for forwarding creates the new object on press rather than on drag.

**Comment by jessegreenberg** [comment]
Also related to phetsims/energy-skate-park-basics#282, current implementation of dragging has the Track model with a reference to the TrackDragHandler

**Comment by jessegreenberg** [comment]
This is done in the above commits. but was a fairly large change to ESP. @samreid can you please review the new TrackToolboxPanel and its usage of the Creator pattern?

**Comment by samreid** [comment]
The changes look really nice and match what is done in a number of other sims.  One potential change would be to make it so the forwarding listener communicates to the `trackNode` via the model, say, through emitters.  @jonathanolson and I used this pattern in https://github.com/phetsims/circuit-construction-kit-common/blob/22ac3ed217eefd1132383bbf9249364fb243de03/js/view/CircuitElementToolNode.js#L57-L80

I'm not sure whether it would be better here or not (and like I said there are several sims that are implemented the way you have it), but I thought I'd mention it in case you were looking for a way to get rid of `trackNode` usages in that function and a way to delete `getTrackNode()`.

**Comment by jessegreenberg** [comment]
I really like that, thanks! `EnergySkateParkView.getTrackNode` was added just for this, so that function could be removed entirely. This was done in the above commit. I think this issue can be closed.
