### ISSUE TITLE
What should happen to reference height when reference height line is invisible?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#24]
Should the control just disappear without modifying the reference height or should the reference height revert to y=0?  @arouinfar what do you think?

**Comment by arouinfar** [comment]
Good question @jessegreenberg. I think it should revert to y=0. 

While a PE reference point is arbitrary, the natural assumption is that it corresponds to y=0.  I think we would want to avoid the situation where the reference point is y > 0, but not visible.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, that makes sense to me. Ill proceed with that.

**Comment by jessegreenberg** [comment]
Done in the above commit, the line is resetting when scene changes, that should be fixed.

**Comment by jessegreenberg** [comment]
Closing.
