### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#240]
@jessegreenberg here are the recommended pixel polishes. Where applicable, the changes would also affect ESPB.

- [x] Use consistent corder radii for all panels/accordion boxes/legends, let's try 8 px
- [x] Use 14 pt font for checkboxes
- [x] Size of checkboxes is generally too large and should match the text height 
- [x] Left-align checkboxes with "Friction" in the main control panel.
- [x] Increase padding between checkbox and corresponding icon, so the appearance is more like the published version of ESPB. (Not sure if this possible with alignBox implementation, feel free to push back.)
<img src="https://user-images.githubusercontent.com/8419308/76468273-305d3f00-63b1-11ea-9c50-30e407adc422.png" width=200>

- [x] Add thin gray stroke (`#ababab`) to main control panel, toolbox, Energy AccordionBox (Graphs screen), grid panel. (All gray panels should have this stroke.)
- [x] Change fill/stroke color of Bar Graph AccordionBox to match pie chart legend.
- [x] Change fill/stroke of Grid/Ref Height panel to match main control panel.
- [x] Remove dilation from PlayPauseButton
- [x] Reduce size of PlayPauseButton and StepForwardButton by 10%. Relative sizes look good in this screenshot, just a bit too large overall.
![image](https://user-images.githubusercontent.com/8419308/76469031-0c026200-63b3-11ea-90ac-4889ad5259c3.png)
- [x] Change color of ProbeNode to match Measure tool body color.

**Comment by jessegreenberg** [comment]
When I increased the font size of checkboxes I noticed that the grid/reference height panel becomes wide enough to occlude grid labels. @arouinfar what should we do?

![image](https://user-images.githubusercontent.com/6396244/77650945-72a28680-6f42-11ea-8f0e-ba7c28d5ae5f.png)

**Comment by arouinfar** [comment]
> When I increased the font size of checkboxes I noticed that the grid/reference height panel becomes wide enough to occlude grid labels. @arouinfar what should we do?

Can we move the `0 m` marker to the lower right corner of the first grid square (just above ground level)? It looks like all the other height measurements are in the lower right corner, just above the line they are measuring.

<img width="90" alt="Screen Shot 2020-04-01 at 10 18 17 PM" src="https://user-images.githubusercontent.com/8419308/78210208-b75c7f00-7466-11ea-9c0d-e2ed657708d0.png">

**Comment by jessegreenberg** [comment]
> Can we move the 0 m marker to the lower right corner of the first grid square

Good idea! Done.

**Comment by jessegreenberg** [comment]
This list of changes is done @arouinfar. Reassigning to you to review.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! The sim is definitely looking cleaner, but I found a few more pixels to polish.

- [ ] Increase font size of `Height = 0` label on the reference line to 14 pt.
- [ ] The graphic return skater buttons still have the old skater artwork on them. Can you use Skater 1 instead?
- [ ] The background of the Energy bar graph AccordionBox and the pie chart legend should be white. (Please leave the Energy AccordionBox on the Graphs screen gray since the graph itself has a white background already.)
- [ ] Reduce corner radii to 5 pt.

**Energy Graph AccordionBox, Graphs Screen**
- [ ] Energy type checkbox labels: size 14 pt font, bold. (Part of me worries that the color contrast is too poor, maybe we should consider alternatives. I'll open a separate issue.)
- [ ] Reduce size of energy type checkboxes to match the smaller size used elsewhere in the sim.
- [ ] Increase padding on left side of panel by a few px. Currently the ExpandCollapseButton and the energy type checkboxes are really close to the edge of the AccordionBox. ExpandCollapseButton's top padding looks reasonable, so increase left padding to match.
- [ ] Vertically center the Erase button between the top boundary of the AccordionBox and the graph. It's currently very close to the top border of the AccordionBox.
- [ ] Increase size of font used in Position/Time ABSwitch to match the size used for the graph axis labels. (Looks like it could be 14 pt, maybe?)

**Comment by jessegreenberg** [comment]
> Change color of energy type strings (Potential, Kinetic, etc.) to black in the Pie Chart legend and in the Bar Graph labels.

Hmm, it turns out that griddle forces these labels to match the bar color so Ill need to make changes there to do this.

**Comment by arouinfar** [comment]
> Hmm, it turns out that griddle forces these labels to match the bar color so Ill need to make changes there to do this.

I would be fine with doing this universally across all energy graphs. I suspect that the colors do not have sufficient contrast against light gray or white backgrounds to pass at the WCAG AAA level. https://webaim.org/resources/contrastchecker/

**Comment by jessegreenberg** [comment]
Oh I see - in that case other sims that use BarChartNode are masses-and-springs and pendulum-lab. I would change default behavior in griddle to have black label text, but you could optionally pass in a different color. @arouinfar can you please confirm that you are OK changing labels to black in all three sims?

**Comment by jessegreenberg** [comment]
Questions in https://github.com/phetsims/energy-skate-park/issues/240#issuecomment-622060414 will be moved to https://github.com/phetsims/griddle/issues/49.

The labels are now black. @arouinfar re-assigning to you to review.

**Comment by arouinfar** [comment]
@jessegreenberg the updated labelColor looks good in master. I've also commented in https://github.com/phetsims/griddle/issues/49.

**Comment by arouinfar** [comment]
I just realized that all items in https://github.com/phetsims/energy-skate-park/issues/240#issuecomment-618200193 were checked off, so I reviewed those in master. 
Everything's looking great @jessegreenberg! 

I don't think there's any remaining work for this issue, so I'll go ahead and close.

**Comment by arouinfar** [comment]
So sorry to re-open so quickly, but it seems appropriate to group this last set of requests in with this issue.

The font sizes in the Energy Sensor on the Measure screen all seem a bit too small compared to other text in the sim.
![image](https://user-images.githubusercontent.com/8419308/80828377-68f3ea80-8ba2-11ea-8956-d6418100ab05.png)

- [ ] "Energy" title: 16 pt
- [ ] All other labels/values (including height/speed): 14 pt

**Comment by jessegreenberg** [comment]
OK, text sizes were increased. @arouinfar can you review again?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I think the data will be much more readable when the sim is being projected in a classroom. 
![image](https://user-images.githubusercontent.com/8419308/80843987-d9126880-8bc2-11ea-9b12-9ab65b27c233.png)
