### ISSUE TITLE
Rename "Lab" screen "Playground"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#241]
This was discussed some time ago at a design meeting, but it looks like it never made it onto GitHub. There are a few reasons to change the name to "Playground"

* Playground is the name used in ESPB
* Playground is a more fun/inviting name
* "Lab" is usually means that the screen includes all the features of previous screens (e.g. Lab screen in Pendulum Lab), which is not true for this sim.

**Comment by jessegreenberg** [comment]
There is already an EnergySkateParkPlaygroundScreenView, which is extended by EnergySkateParkLabScreenView, so the rename will take a little thought. This list is for myself to think through steps.
- [ ] Rename the `lab` directory to `playground`, update relative paths used by modules
- [ ] Move EnergySkateParkPlaygroundScreenView from `common` to `playground` directory
- [ ] Delete LabScreenView, its options and settings should be default for EnergySkateParkPlaygroundScreenView
- [ ] Rename LabScreen to PlaygroundScreen
- [ ] Delete EnergySkateParkPlaygroundModel, it does nothing, use an EnergySkateParkPlaygroundModel directly in PlaygroundScreen.
- [ ] Update the EnergySkateParkPlaygroundScreenView of basics after these changes.

**Comment by jessegreenberg** [comment]
Done in the abvoe commits
![image](https://user-images.githubusercontent.com/6396244/78208160-acf3b280-7471-11ea-9317-a5341e46904f.png)
