### ISSUE TITLE
Delete temp production deploy

### ISSUE THREAD

**Issue by mattpen** [phetsims/energy-skate-park#242]
Per request from @kathy-phet, there was a temporary dev version deployed to the production location. This must be removed from phet-server before version 1.0 is deployed with the build server.

It can be removed by running the following on phet-server:

`rm -rf /data/web/static/phetsims/sims/html/energy-skate-park/`

Contact me if there are any questions.

**Comment by jessegreenberg** [comment]
@mattpen deleted this before we published a prototype today on 8/27/20. Closing.
