### ISSUE TITLE
Review comment: BackgroundNode performance

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#243]
A review comment related to BackgroundNode layout was added
```js
  /**
   * Exactly fit the geometry to the screen so no matter what aspect ratio it will always show something.
   * Perhaps it will improve performance too? // REVIEW: How might this improve performance?
   * @public
   *
   * @param {Bounds2} bounds
   */
```
The original comment related to performance was carried from ESP:B. Perhaps this came after changing from a different implementation that may have been slower? @samreid do you recall? Alternatively, we could remove this comment.

**Comment by samreid** [comment]
I don't recall offhand.  Would it simplify it to hardcode the dimensions (rather than fit it each time) and run a performance check?
