### ISSUE TITLE
Add zoom feature to bar graph

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#25]
Should be pretty straight forward, there is a scalar in the BarGraphForeground that transforms the physical values to heights in the graph. This could be changeable. So remaining question is how many levels of zoom should we support?

**Comment by jessegreenberg** [comment]
I tried to add the arrows that show up when the graph goes out of scale to the BarGraphForeground with renderer: barRenderer (webgl, usually), but I am seeing an error in the console like
"Too many WebGL rendering contexts." I am not sure I understand why, but we can add these to the background instead and not use webgl since they don't animate.

**Comment by jessegreenberg** [comment]
This feature has been added. How many levels of zoom should we have @arouinfar? Default zoom right now is the zoom used in ESP:B. There are currently 8 levels, that is probably too many.

**Comment by jessegreenberg** [comment]
Also, the total energy arrow needed to be shifted up around the zoom buttons, here is what it looks like

![capture](https://user-images.githubusercontent.com/6396244/47245423-353ddf00-d3c7-11e8-80af-7e4a2fea8532.PNG)

**Comment by arouinfar** [comment]
@jessegreenberg the default zoom level looks good! Zoom level 1-5 seem the most useful to me, so I think we can remove the 3 most zoomed-in levels. 

I don't think I had taken negative total energy into account when mocking up the bar graph, so I have a few suggested pixel polishes:

* Move the x-axis up 20 px so there's more space to show negative energies
* Move zoom buttons to lower left corner so Potential and Total energies can have the same height below the x-axis
* Bottom of off-scale arrows should be above zoom buttons
* Add a stroke around the bars (we've done this in other sims to improve contrast)
* Make the off-scale arrows a bit wider, similar to Masses and Springs/Capacitor Lab: Basics. 
![image](https://user-images.githubusercontent.com/8419308/47312278-25a5dc80-d5f9-11e8-9eb3-207b82349b6f.png) ![image](https://user-images.githubusercontent.com/8419308/47312288-2b032700-d5f9-11e8-989f-edbc45aae143.png)


Here's an updated mockup:
![image](https://user-images.githubusercontent.com/8419308/47312442-98af5300-d5f9-11e8-8c1b-dc79fa96c786.png)



One question I have is whether it's possible (and feasible) to position the remove heat button with respect to the start of the `Thermal` string. I like the idea of keeping the button close to the string, but allow it to shift down so until it's bottom-aligned with the off-scale arrows for i18n. If the remove heat button is always bottomed-aligned with the off-scale arrows, it feels quite far from the `Thermal` string, especially when there aren't any negative energies.

![image](https://user-images.githubusercontent.com/8419308/47312474-b381c780-d5f9-11e8-8808-827ffb7d00eb.png)

**Comment by arouinfar** [comment]
@jessegreenberg on second thought, let's keep all 8 zoom levels for now. I hadn't taken the variable gravity into account.

**Comment by jessegreenberg** [comment]
Everything in https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-431936789 is pretty much done except for the stroke around the bars.

> whether it's possible (and feasible) to position the remove heat button with respect to the start of the Thermal string.

This is actually how it worked before, I changed the max width of labels so that it allows for space for the arrows, and aligns the thermal button with them.

I ran into problems with the strokes because the transparent effect is produced by using two rectangles stacked on top of each other, so stroking them created a line in the middle of the bar. Also, the bars jiggled up and down a bit when I added the stroke and I am not sure why. Maybe because the bars are using webgl? Or maybe something else.

**Comment by arouinfar** [comment]
@jessegreenberg I was looking at Masses and Springs, and I noticed that the transparency is (inadvertently) different from my mockups of ESP. In MAS, the transparency is a rounded rectangle that sits within the bar. Perhaps you can try that instead?

![image](https://user-images.githubusercontent.com/8419308/47443629-041c3080-d772-11e8-85b3-ad0dfec4b954.png)

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, Ill give it a shot! There would be an overall improvement if we change to use Griddle here anyway, Ill investigate that.

**Comment by jessegreenberg** [comment]
I took a look at using griddle but won't be able to use it without a number of changes because of the layering this sim uses for tablet performance/memory performance. I made https://github.com/phetsims/griddle/issues/32 to discuss further.

In the meantime, the look of https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-432714812 may be a more simple solution for the bar graph, but we will need a new layer for the text so that it is on top of the bars and the webgl layer in the screen view.

@arouinfar do you have a preference for the look of the labels, and which one we should continue to work on?

**Comment by jessegreenberg** [comment]
If in https://github.com/phetsims/griddle/issues/32 we decide to change griddle so it can be used here, it will end up looking like https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-432714812, so maybe it makes most sense to continue with that one?

**Comment by jessegreenberg** [comment]
I also think it doesn't make sense to continue working on this until a decision is made in https://github.com/phetsims/griddle/issues/32.

**Comment by arouinfar** [comment]
@jessegreenberg please let me know if you have any design questions after https://github.com/phetsims/griddle/issues/32 wraps up!

**Comment by jessegreenberg** [comment]
This is working pretty well, but it means that the labels are on top of the skater which looks pretty weird.
![capture](https://user-images.githubusercontent.com/6396244/48566296-76db8000-e8c8-11e8-8257-1e1b4c02f233.PNG)

**Comment by jessegreenberg** [comment]
I found the generated images in dev tools, I don't see any artifacts around the image. Wondering if this is from the SpriteSheet then.
![capture](https://user-images.githubusercontent.com/6396244/48651461-07998500-e9c9-11e8-9361-4a153938151f.PNG)

**Comment by arouinfar** [comment]
@jessegreenberg I have one minor pixel-polishing request. Can you change the zoom button colors to `LIGHT_BLUE` (see https://github.com/phetsims/sun/blob/master/js/ColorConstants.js#L28). This is the color used for zooming in other graphs, such as Masses and Springs (see https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-432714812), Pendulum Lab, and Wave Interference.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/energy-skate-park/issues/40, I had to revert the look from "griddle-esqu" to the mockups in https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-431936789. Putting the label on top of the bar caused layering issues with with the skater node or performance issues with WebGL. But in #40 we found a way to stroke the bars that is performant.

**Comment by jessegreenberg** [comment]
OK, the zoom buttons are light blue in the above commit. @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by arouinfar** [comment]
Not sure if there's still remaining work on this issue, so reassigning @jessegreenberg.

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar! I think this issue can be closed, any other pixel polishing or changes can have a new issue. Closing.
