### ISSUE TITLE
"Custom" is in combobox twice

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#251]
Just noticed, not sure if its always been like this or regressed:
![image](https://user-images.githubusercontent.com/6396244/80011850-6efb1480-849a-11ea-8ca1-ab88aeeaed97.png)

**Comment by arouinfar** [comment]
@jessegreenberg I think the first "Custom" is probably supposed to be the Moon.

**Comment by jessegreenberg** [comment]
Ah thanks! You are correct,

**Comment by jessegreenberg** [comment]
Fixed above.
