### ISSUE TITLE
ReferenceHeightLine dragPositionProperty

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#252]
This section was flagged for review.

```js
    // a Vector2Property for DragListener so we can update the NumberProperty ReferenceHeightProperty with dragging
    // REVIEW: Shouldn't this be a DynamicProperty?  It seems odd to have another independent properly related to the
    // REVIEW: reference position
    const dragPositionProperty = new Vector2Property( new Vector2( 0, referenceHeightProperty.value ) );

    this.addInputListener( new DragListener( {
      transform: modelViewTransform,
      positionProperty: dragPositionProperty,
      tandem: tandem.createTandem( 'dragListener' )
    } ) );

    dragPositionProperty.link( dragPosition => {
      referenceHeightProperty.set( referenceHeightProperty.range.constrainValue( dragPositionProperty.get().y ) );
    } );
```

This was necessary because DragListener requires a Vector2Property, but the model uses a NumberProperty for the reference height. I am not sure yet how DynamicProperty would be better here.

**Comment by samreid** [comment]
@jonathanolson is best suited to recommend how to proceed here.  @jonathanolson can you please take a look?

**Comment by jonathanolson** [comment]
The advantage of DynamicProperty is that the dragPositionProperty would update if the model referenceHeightProperty updates. I'm not sure how relevant that is here.

I'm fine to leave it as-is for now, and if we run across this more often then it would make sense to find a better pattern.

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson - I changed it to use DynamicProperty in the above commit, it seems like the right thing to do since DynamicProperty supports this exact case with `map` and `inverseMap` (see usage in 29829fefb8aa4c4d7324b7aea8d7203c8671b063). Closing.
