### ISSUE TITLE
Change scene implementation in this sim?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#253]
From #202 Review comment in EnergySkateParkTrackSetModel for updateActiveTrack:

>      // REVIEW: other simulations have a pattern for switching between scenes, where each EnergySkateParkScene
>      // REVIEW: would contain its own list of Tracks. Would that pattern work here?  If not, why not?  If yes, should
>      // REVIEW: we use that strategy?

It seems like this could work. But each "scene" is just one active track and so switching scenes updates the active track. We could create an abstraction for EnergySkateParkScene but I don't think it would bring much benefit.

Assigning to @samreid for further discussion.

**Comment by samreid** [comment]
Yes, it seems the design is just to change the track.  Other sims might keep track of the skater position as part of the scene, but it looks like that is not part of the design here.  So perhaps this is best to leave as it is.  But perhaps rename `scene` to `sceneIndex`?

> * @param {number} scene - index identifying the scene

**Comment by jessegreenberg** [comment]
OK sounds good, ill rename so that it is clear it isn't taking a "scene" object but the index for the scene.
