### ISSUE TITLE
Should the reference height change when track scene changes?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#256]
Just noticed that changing the premade track in the first three screnes resets the reference height. Is this as it should be?

**Comment by arouinfar** [comment]
Good catch @jessegreenberg. It seems a bit odd to me, actually. I think it would make more sense for the reference height to stay in place. What do you think?

**Comment by jessegreenberg** [comment]
OK thanks @arouinfar that makes sense to me.

**Comment by jessegreenberg** [comment]
Changed in the above commit.
