### ISSUE TITLE
SkaterState overrides

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#259]
Two review comments were added related to SkaterState and the way things can be set by using optional overrides

In `updateThermalEnergy`
>     // REVIEW: Why is this not done through the options object and overrides?

And for `getValue`, which is used to implement SkaterState overrides.
>  * REVIEW: Why is this needed?

And I am not sure for either!  SkaterStates are almost never constructed with overrides. The only place is in two usages of `SkaterState.update`

```js
newState.update( { thermalEnergy: newState.thermalEnergy - dE } );
```
but then other places `updateThermalEnergy` is used which does not use overrides
```js
return updated.updateThermalEnergy( newThermalEnergy );
```

I am not sure if `update` and the overrides can be removed from SkaterState, but it seems like it would be beneficial to have just one way to update/create new states.

**Comment by jessegreenberg** [comment]
This review comment:
> // REVIEW: Why is this not done through the options object and overrides?

Presumably also applies to all of the `update*` functions. @samreid I am curious if you have thoughts about this. I am tempted to remove overrides from SkaterState. Does this make sense to you? Is it worth the effort?

**Comment by samreid** [comment]
Yes, SkaterState constructor and usages should be cleaned up.  These should just say `new SkaterState()` without having to pass `EMPTY_OBJECT`.

![image](https://user-images.githubusercontent.com/679486/80282220-7bb37e80-86cd-11ea-922a-9ac5a8c91cd0.png)

And the places you identified about the thermal energy should use a simpler approach.

**Comment by jessegreenberg** [comment]
OK thanks. In the above commit overrides have been removed from SkaterState.

**Comment by jessegreenberg** [comment]
The sim has been fuzzing successfully for a while, and I have been playing with the sim as well and behavior is looking correct. Closing htis issue.
