### ISSUE TITLE
Measure tool data visible after path dot disappears

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#260]
Procedure
1. Release skater on the track
2. Place probe over one of the path dots
3. After the dot disappears, the data is still visible. 

![image](https://user-images.githubusercontent.com/8419308/80063231-b4e3c700-84f2-11ea-8237-996e8c69b2e3.png)

@jessegreenberg I think the data should clear once the dot's opacity reaches zero.

**Comment by jessegreenberg** [comment]
Thanks for pointing out @arouinfar, that makes sense. Should be fixed in the above commit, can you please verify?

**Comment by arouinfar** [comment]
Looks good in master, thanks @jessegreenberg!
