### ISSUE TITLE
Gravity NumberControl tweaker increment should be 0.1 m/s^2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#264]
Noticed during the 4/23/20 design meeting.

The tweakers should increment/decrement the value in steps of 0.1 m/s^2. Currently, the tweaker step size matches the constrainValue increment which snaps the thumb in 1 m/s^2 steps which prevents users from setting precise g values.

**Comment by jessegreenberg** [comment]
This is done, over to @arouinfar to verify or just close

**Comment by arouinfar** [comment]
👍
