### ISSUE TITLE
Updates to Mass NumberControl

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#265]
Discussed in 4/23/20 design meeting

- [x] Change minimum to 5 kg
- [x] Use `constrainValue` to snap thumb in 5 kg increments.
- [x] Tweaker increment should be 1 kg.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, this is done. Can you please review?

**Comment by jessegreenberg** [comment]
NOt quite ready, over slack we discussed that the mass slider (in ESPB) should snap to 5kg as well.

**Comment by jessegreenberg** [comment]
OK, ready again.

**Comment by arouinfar** [comment]
👍
