### ISSUE TITLE
SkaterState pooling

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#267]
SkaterState says:

> Pooled to avoid allocation problems, see #50.

and also:

```js
  // NOTE: Consider Pooling support for SkaterState?
  // @protected
  // @override
  freeToPool() {}
```

Which is correct?

**Comment by jessegreenberg** [comment]
Hmm, there are other references to pooling in comments too. That issue is https://github.com/phetsims/energy-skate-park-basics/issues/50, and it looks like pooling was added but has since been removed?

**Comment by jessegreenberg** [comment]
According to phetsims/energy-skate-park-basics@ca6a554 pooling was removed in phetsims/energy-skate-park-basics#252

**Comment by jessegreenberg** [comment]
The stubs were added to short-circuit pooling to test and see if performance / GC impacts were actually reduced with pooling.  In https://github.com/phetsims/energy-skate-park-basics/issues/252 it was determined that pooling did not improve performance and so it was removed.

I will remove stubs and documentation referencing pooling.

**Comment by jessegreenberg** [comment]
I removed old documentation about pooling, but added some content referencing this issue and https://github.com/phetsims/energy-skate-park-basics/issues/252 showing that pooling was used but determined to be ineffective.
