### ISSUE TITLE
Prepare new prototype version

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#268]
To update the link currently on the website. I think this could be done after these are finished:

- [x] #263
- [x] #176 
- [x] #101
- [x] #240

**Comment by arouinfar** [comment]
@jessegreenberg if it'd be quick to do, can you also address https://github.com/phetsims/energy-skate-park/issues/195#issuecomment-620753651? I think it would be nice to have the updated screen icons in the prototype, but not necessary.

**Comment by arouinfar** [comment]
@jessegreenberg we're good to go!

**Comment by jessegreenberg** [comment]
A new prototype was deployed, latest is using https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.11/phet/energy-skate-park_en_phet.html
