### ISSUE TITLE
Add a tape measure and its toolbox panel

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#27]

**Comment by jessegreenberg** [comment]
Measuring tape has been added @arouinfar!

**Comment by arouinfar** [comment]
Toolbox size and placement looks great, though the tape measure icon is quite aliased @jessegreenberg.

This is in latest Chrome:
![image](https://user-images.githubusercontent.com/8419308/47312127-bcbe6480-d5f8-11e8-844b-444a59d2c0e4.png)

**Comment by jessegreenberg** [comment]
Hmm, I agree. Ill take a look.

**Comment by jessegreenberg** [comment]
After the above commit it looks better for me in Chrome, @arouinfar can you please verify?

**Comment by arouinfar** [comment]
Looks much better @jessegreenberg. Thanks!
