### ISSUE TITLE
SkaterSamples need to save more state

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#271]
Was discussed at a recent design meeting that the SkaterSamples need to include more information so that when scrubbing back the simulation state is fully restored. For instance, Skater mass, sim friction, sim gravity, and Track (control points) need to be saved.

**Comment by jessegreenberg** [comment]
This is now saving more than Skater data, maybe this needs to be a SimSample or something.

**Comment by jessegreenberg** [comment]
Track and renames done in the above commit.

**Comment by jessegreenberg** [comment]
OK, now track control points, friction, gravity, and mass are part of sample data that get restored when scrubbing through data on the Graphs screen. @arouinfar can you please review and make sure this is correct?

It looked a little strange to me to see the values change on sliders when scrubbing through data, I am not sure why. Im probably just not used to it.

**Comment by arouinfar** [comment]
@jessegreenberg this is looking good in master!

> It looked a little strange to me to see the values change on sliders when scrubbing through data, I am not sure why. Im probably just not used to it.

I think it's because we're not used to it, but it's important for the gravity/mass/friction to sync up with the data in the graph.
