### ISSUE TITLE
How should the StopwatchNode behave when scrubbing  back through data?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#274]
I noticed that time is not tied to plot time on the graphs screen.  And so going back  in time with the cursor on the plot does not change time on the StopwatchNode either. At first I found this strange.  But then I realized it could be correct because the Stopwatch has its own play/pause functionality so it may be totally different from plotted time anyway.

@arouinfar do you think  the current behavior of the StopwatchNode on the Graphs screen is correct or does it need to change.

**Comment by arouinfar** [comment]
@jessegreenberg I think the StopwatchNode should be its own independent thing, so the current behavior is good.
