### ISSUE TITLE
Track radio buttons should have more bold icons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#276]
Was mentioned recently that the icons on the radio buttons for track are too thin and difficult to see. They should have a "thicker stroke". That doesn't really apply at the moment because the icons are actually images rasterized from the track Nodes themselves.

So we may have to do some new drawing or other things to make the tracks look more prominent.

**Comment by jessegreenberg** [comment]
I made it so we can change the thickness of the track and modify other things for icons:
![image](https://user-images.githubusercontent.com/6396244/86294108-edbead00-bbc1-11ea-8344-b958faadc02c.png)

But see how the slope track looks thicker because it isn't scaled down as much to fit in the button. We need another way to draw these so that none of the tracks get scaled down.

**Comment by jessegreenberg** [comment]
Each track in the icon group needs the same dimensions so they scale similarly. PremadeTracks can be modified to support this.

**Comment by jessegreenberg** [comment]
This ended up as a pretty massive change because doing this made me think of a better way for the models to request their custom tracks. But the result is that the track selection buttons can have their own custom tracks so that their shapes are of identical bounds. @arouinfar could you please take a look at master and review? Shapes can be changed, paths can have different thickness, or anything else that could change, let me know.

![image](https://user-images.githubusercontent.com/6396244/86315562-67718d80-bbf8-11ea-86ab-1ea9df8f53e2.png)

**Comment by jessegreenberg** [comment]
Also, all the icons have their control points removed now.

**Comment by arouinfar** [comment]
Reviewed in the 7/16/20 design meeting. The team likes the bolder icon without the control points. Closing.
