### ISSUE TITLE
Sim should use default layout bounds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#279]
@ariel-phet noticed that this sim is using custom layout bounds, as they were copied from energy-skate-park-basics.
```js
    super( {
      layoutBounds: new Bounds2( 0, 0, 834, 504 ),
      tandem: tandem
    } );
```

In https://github.com/phetsims/joist/issues/542 we decided that new sims should use the default layout bounds. At this point it could be difficult to make this change. Ill investigate and see how difficult it may be.

**Comment by jessegreenberg** [comment]
Overall, the changes for this don't seem too difficult. Sim behavior is still correct and things are generally aligned in model coordinates.

Most changes will be front-end things like making panels larger, making Text a bit larger, making checkboxes larger so that the UI looks similar to what it did with the custom layout bounds. Constants for these things should be factored out and shared between screens so this doesn't seem like a huge task.

**Comment by jessegreenberg** [comment]
For the transform, the default layout bounds and the custom layout bounds have almost the same aspect ratio, so the scale should be the only thing that needs to change. 834 / 504 uses scale of 50, so 1024/618 should use a scale of 50 * 1024 / 834  for the same model area to be within view bounds.

**Comment by jessegreenberg** [comment]
In general, things in view coordinates need to be 1024/834 ~= 1.228 times larger to look the same.

**Comment by jessegreenberg** [comment]
Initial commit for this is done in the following commit. I still need to review the other screens but things are looking pretty identical for the "Intro" screen. Left is after change, right is before change:
![image](https://user-images.githubusercontent.com/6396244/87612742-62710b80-c6d9-11ea-9580-893c608840c5.png)

**Comment by jessegreenberg** [comment]
After the above commits, the sim is using default layout bounds. I went through UI components and compared each screen as in https://github.com/phetsims/energy-skate-park/issues/279#issuecomment-659083811 until everything looked the same. But tweaks can be made in any pixel polishing review. Closing this issue.

**Comment by jessegreenberg** [comment]
Hmm, actually this should be reopened and reviewed separately. @arouinfar can you please review the latest sim layout? Almost everything in the UI had potential to change in placement/sizing from prior to https://github.com/phetsims/energy-skate-park/commit/c9c06a5e7b2f122d0a5a14b0f8e683e34a1e4bc2, but I did my best to keep things as they were.

This also means that some buttons (TimeControlNode, ResetAllButton) are slightly *larger* than they usually are in default layout bounds, but they should be close/identical to what they always were in ESP/ESP:B.  If it is better for these buttons to be more conventionally sized for PhET sims we can change them, but I prioritized changing as little as possible relative to ESP.

**Comment by arouinfar** [comment]
@jessegreenberg I think everything looks good in master. Unless I'm toggling between master and the latest prototype, it's very hard to notice any differences.
