### ISSUE TITLE
Support changing gravity

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#28]

**Comment by jessegreenberg** [comment]
@arouinfar I added a control to change gravity. I have barely had to touch the model for this so far, @samreid thanks for making things so easy :)

@arouinfar Would you like to review? What should the range be for gravity? Right now it ranges from -1 to -15 m/s^2. Or should it have same range as original sim?

**Comment by arouinfar** [comment]
Great questions @jessegreenberg. Let's make the range 1-20 m/s^2, and change the "none" label to "tiny".

While the Java sim deals with zero gravity, I'm not sure if we'll go there or not. There are still a lot of design discussions/decisions to be made around zero gravity.

**Comment by jessegreenberg** [comment]
Sounds good @arouinfar I changed the label and modified the range.

**Comment by arouinfar** [comment]
Looks good @jessegreenberg!
