### ISSUE TITLE
Change behavior for clearing saved data

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#280]
It was requested that the behavior for clearing data on the energy plot of the graphs screen needs to change. Currently, the data gets cleared when the cursor drag ends. Instead it should behave as follows:
- The data should not clear but remain on the plot for playback from where the cursor is dropped.
- Data will begin recording again once the cursor reaches the last saved data point.
- If at any time during this playback a physical Property changes (gravity, mass, friction - anything that would change plotted values), saved data newer than the cursor point will be cleared.

**Comment by jessegreenberg** [comment]
During playback, we need a way to distinguish whether the user is controlling change of the physical Property. For example, say that during playback the frictionProperty is changed to match the value at the saved EnergySkateParkDataSample at that time. That change should NOT clear samples. But dragging the slider should.

I think in some sims I have seen `userControlled` flags to distinguish whether change came from user input vs other sim changes.

**Comment by jessegreenberg** [comment]
We are almost there, but I found a bug where changing between plotting position and time can stop all plotting. Haven't figured out exactly what is causing it yet,.

**Comment by jessegreenberg** [comment]
Also, the "Return Skater" buttons need to work with this feature. It is sort of like a short cut to drag the skater to its original position, so I am going to clear any saved data to the right of the cursor when these buttons are pressed.

**Comment by jessegreenberg** [comment]
Ok, this is done. @arouinfar @kathy-phet @ariel-phet can you please review this new behavior? Should be as we discussed in design meeting. But please take a look at the following in this version:

https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.15/phet/energy-skate-park_en_phet.html

- The "Energy vs Time" plot now plays back recorded data instead of clearing data when the cursor is released.
- If the **user** changes "Stick to Track" checkbox, friction, gravity, mass, track shape, reference height, or skater position, recorded data to the right of the cursor is cleared. But if any of these things change during normal playback data is NOT cleared. 
- The "Gravity" ComboBox display now reads its value if the value is one of the ComboBox items when gravity is changed with the NumberControl or during playback. It used to just read "Custom" when changed by anything other than the ComboBox. I thought this was important because otherwise it would read "Custom" when playing back, even if gravity was one of the ComboBox selections in the "initial" playthrough.
- Try out the sim playing back changes to lots of things like reference height, friction, and mass. Playback will change all the controls in the UI, is this OK?

Questions:
- "Stick to Track" checkbox will clear data to the right of the chart cursor, but it is not yet saved as part of the data restored during playback. I think it needs to be, right?
- Try out play back with changes to lots of things in one recording, like reference height, friction, and mass. Playback will change all the controls in the UI, does this seem OK?

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed this, and it's looking really nice!

> The "Gravity" ComboBox display now reads its value if the value is one of the ComboBox items when gravity is changed with the NumberControl or during playback. It used to just read "Custom" when changed by anything other than the ComboBox. I thought this was important because otherwise it would read "Custom" when playing back, even if gravity was one of the ComboBox selections in the "initial" playthrough.

@jessegreenberg the pattern we usually follow for a NumberControl/ComboBox group is that the ComboBox displays "Custom" if the value is set by the slider thumb or tweaker buttons, regardless of the value. For example, if the user sets the gravity to 9.8 with the slider/tweakers, the ComboBox reads "Custom" not "Earth".

> "Stick to Track" checkbox will clear data to the right of the chart cursor, but it is not yet saved as part of the data restored during playback. I think it needs to be, right?

Yes, the Stick to Track state should be restored during playback.

> Try out play back with changes to lots of things in one recording, like reference height, friction, and mass. Playback will change all the controls in the UI, does this seem OK?

This is all looking good, with the exception of the point above. The UI components I expect to change during playback (because they affect the data) do so, but more global/view controls (such as the Grid checkbox) are unaffected by playback.

**Comment by arouinfar** [comment]
@jessegreenberg and I discussed the gravity NumberControl/ComboBox issue, and decided to leave the behavior alone.

During playback, the sim adjusts the model property for gravity and doesn't know if the values it restores were originally set by the NumberControl or ComboBox. Previously, the ComboBox would only read "Custom" during playback. It now shows "Earth", etc. during playback, but the side effect is that the ComboBox will display the benchmark if the corresponding value was set using the NumberControl.

The slider snaps in steps of 1.0 m/s^2, so the user will never slide through a benchmark. They will need to use the tweakers to precisely set the value to a benchmark. For example:
* Slide to 10.0 m/s^2, ComboBox displays "Custom"
* Tweak down to 9.8 m/2^2, ComboBox displays "Earth"

**Comment by jessegreenberg** [comment]
> Yes, the Stick to Track state should be restored during playback.

I think this was the last thing for this issue and it has been done in the above commits. @arouinfar can you please review the behavior of "Stick to Track" with saved data on the Graphs screen?

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!
