### ISSUE TITLE
Add a double headed arrow to the cursor in the Graphs screen

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#284]
Discussed with @arouinfar on 7.24.20 -

Would like to add a double headed arrow to the chart cursor. Should be near the bottom of the cursor. Has the color of the grippy dots of the cursor.

**Comment by jessegreenberg** [comment]
@arouinfar can you please add the mockup images you showed while we met?

**Comment by jessegreenberg** [comment]
Also discussed - the arrow should disappear when user successfuly drags the cursor. Should come back on "Reset All".

**Comment by arouinfar** [comment]
Here are the mockups:
![image](https://user-images.githubusercontent.com/8419308/87834229-20fe6e80-c847-11ea-85c3-70a1b3c597fe.png)

**Comment by jessegreenberg** [comment]
This has been added. @arouinfar can you please review?

**Comment by arouinfar** [comment]
@jessegreenberg this looks really good in master, thanks!
