### ISSUE TITLE
Graph gridlines no longer aligned to play area grid

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#285]
For https://github.com/phetsims/QA/issues/523

In the [latest dev](https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.17/phet/energy-skate-park_en_phet.html?screens=3), the graph and grid are slightly misaligned. The gridlines in the play area are slightly to the right of the vertical gridlines in the graph.
![image](https://user-images.githubusercontent.com/8419308/89352948-9e611600-d672-11ea-8026-0bbfaa06fb53.png)

Previously, grid and graph were aligned. The change happened somewhere between [dev.10](https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.10/phet/energy-skate-park_en_phet.html?screens=3) and dev.11, so the pixel polishing in #262 is the likely culprit.
![image](https://user-images.githubusercontent.com/8419308/89353453-a66d8580-d673-11ea-968d-21d5f624cc1a.png)

@jessegreenberg can you shift things around a bit to restore the alignment?

**Comment by jessegreenberg** [comment]
Hmm, interesting - I am not sure why this is happening. The plot uses the modelViewTransform to position grid lines, it should align just like the other grid in the view. I will take a look.

**Comment by jessegreenberg** [comment]
I see that going back to old builds they have always slightly off of grid lines.

**Comment by jessegreenberg** [comment]
Resolved with the above commit, which positions the accordionbox so that the right edge of the accordion panel falls on the grid line.
![image](https://user-images.githubusercontent.com/6396244/90655517-ad69cb80-e20f-11ea-81c8-6c7a7e6a87c9.png)
