### ISSUE TITLE
Generate screenshots

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#286]
From https://github.com/phetsims/energy-skate-park/issues/1 and now that we are preparing a RC, we are ready for screenshots.

@arouinfar can you please create the look you would like for these images? I think the process is then for myself or @KatieWoe to generate them.

**Comment by arouinfar** [comment]
@jessegreenberg I've added the screenshot and alternates in the above commit.

**Comment by jessegreenberg** [comment]
Oh awesome! Thanks @arouinfar!
