### ISSUE TITLE
Verify credits for 1.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#287]
Here are the current credits, taken from ESP:B HTML5.

![image](https://user-images.githubusercontent.com/6396244/90658938-210cd800-e212-11ea-8821-778a4ca54eb5.png)

I could add @arouinfar and myself. @ariel-phet @arouinfar are there any other additions to make to this list? The QA list can be updated after we complete the RC process.

**Comment by jessegreenberg** [comment]
In the above commit I added myself, @arouinfar and @DianaTavares to credits as requested over slack convo.

**Comment by ariel-phet** [comment]
Please move Amy to lead design, and just put me in "Team"

**Comment by arouinfar** [comment]
Diana should also be alphabetized by Lopez, not Tavares.

**Comment by jessegreenberg** [comment]
OK, https://github.com/phetsims/energy-skate-park/issues/287#issuecomment-676527059 and https://github.com/phetsims/energy-skate-park/issues/287#issuecomment-676571698 were done with the above commits.

**Comment by jessegreenberg** [comment]
Updated to reflect 1.1 release. Credits will be finalized after QA.

**Comment by jessegreenberg** [comment]
In the rc task @KatieWoe said
> Megan Lai, Jaspe Arias, Devon Quispe, Brooklyn Lash, and Kathryn Woessner should be added to credits. I also saw AR in the testing matrix, and am not sure who this is. @loganbraywork and @muedli I didn't see you in the RC1 template. Let me know if you worked on rc2 or 3 and should be added as well.

**Comment by muedli** [comment]
I don't think I did any RC testing for this sim.

**Comment by loganbraywork** [comment]
No recent RC testing from me

**Comment by jessegreenberg** [comment]
Over slack @KatieWoe said 
> Megan Lai, Jaspe Arias, Devon Quispe, Brooklyn Lash, Kathryn Woessner Should be added to the ESP credits before publish.

**Comment by jessegreenberg** [comment]
Credits have been updated, closing
