### ISSUE TITLE
[Measure Screen] Round height and speed readouts to the hundredths place

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#291]
Tangential to https://github.com/phetsims/QA/issues/544

A user wrote into phethelp:
>Hello,
>
>I am currently a physics lecturer at Indonesia. I try this simulation but I don’t quite understand the value for the energy measured in the simulation.
>
>As you can see below that the potential energy is 2385.3 J and the height is 4.1 m, but if I use mgh it will give 2587.2 J (mass is 60 and g is 9.8). Same thing happen for kinetic energy.
>![image](https://user-images.githubusercontent.com/8419308/93399598-1f4b2a00-f83b-11ea-892e-c23427f458a7.png)
>
>Can you explain? I might miss something here.

The discrepancy is due to the rounding of the height and speed readouts. Calculating the height from the PE results in  4.0566 m, which rounds to 4.1 m. Similarly, calculating the speed from the KE results in 7.2613 m/s which rounds to 7.3 m/s.

It is not unreasonable for users to calculate the PE/KE from the height/speed readouts. With only one decimal place, the calculated energies are often off by ~25 J. Adding a 2nd decimal place reduces the discrepancy to ~1-2 J which I think is more acceptable.

@jessegreenberg please update the height and speed readouts to round to the hundredths place.

**Comment by jessegreenberg** [comment]
Rounded to the hundredths place in the above commit. Will also cherry-pick into release branch.

**Comment by jessegreenberg** [comment]
cherry-picked into 1.0 (protoytpe branch) and 1.1 (rc branch). @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master, thanks @jessegreenberg!
