### ISSUE TITLE
TimeSpeedProperty valid values don't match Time Speed radio buttons

### ISSUE THREAD

**Issue by Denz1994** [phetsims/energy-skate-park#292]
Discovered during phetsims/scenery-phet#607:

In the studio view of ESP, searching for "TimeSpeedProperty" shows `Valid Values: Fast, Normal, Slow`. However, the radio buttons are limited to only "Normal" and "Slow". Selecting the "Fast" option in the studio view will deselect both radio buttons in the sim view and seems like it sets the sim in the "Slow" mode.

I would expect the "Fast" option to not be present in the studio view as a valid value. Assigning responsible dev to investigate.

See this [comment](https://github.com/phetsims/scenery-phet/issues/607#issuecomment-634230315) under the "Studio" content for more context and a potential solution.

**Comment by jessegreenberg** [comment]
Thanks @Denz1994, fixed in the above commit and speed options arecorrect in studio:
![image](https://user-images.githubusercontent.com/6396244/93913597-4db18500-fcd3-11ea-8350-e1a45b94a262.png)
