### ISSUE TITLE
Performance issues on Firefox

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/energy-skate-park#294]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/544
While on the "Energy Graphs" section of the Skate Park sim, both while using query parameters (including string tests), in the iframe, and in the Legends of Learning harness all produce performance problems. The skater and the graph lag quite a bit and my computer is also very warm as a result. 

**Steps to reproduce**
1. Click the "Graphs" section
2. Put the skater on the ramp and let it go back and forth. 
3. Move some buttons around
Below are examples using the stringTest=X and stringTest=double parameters.

**Visuals**

![espstring1](https://user-images.githubusercontent.com/72031637/95778099-a34ed100-0c84-11eb-9562-76fe1c53792d.gif)
![espstring2](https://user-images.githubusercontent.com/72031637/95778220-e610a900-0c84-11eb-9e19-b887cabae6b4.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.1.0-rc.1 2020-09-02 16:48:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
I tested out on my windows 10 machine. The sim is not as smooth as on Chrome. But I wasn't able to get it to stutter like in the above gifs. Also, this RC is quite a bit faster for me in Firefox than the  published sim, probably because of changes in #209.

@brooklynlash or @KatieWoe can you please compare performance of this RC on Windows FF with the published version? That may inform how we investigate this.

**Comment by jessegreenberg** [comment]
I noticed that this sim mentioned poor performance with `?stringTest` and in iframes. I tried it with `?stringTest` and didn't notice a difference in performance. I actually saw *better* performance in an iframe, perhaps because the rendering area is smaller?

**Comment by jessegreenberg** [comment]
We reviewed this during meeting today - @kathy-phet tried on her windows 10 firefox machine and said performance was acceptable. And since performance seems a bit better in this version relative to published ESP:B, we agreed it was OK to close this issue.
