### ISSUE TITLE
Skateboard loses contact with track at high speeds

### ISSUE THREAD

**Issue by DevonQui** [phetsims/energy-skate-park#295]
**Test device**
MacBook Pro

**Operating System**
Catalina 10.15.1

**Browser**
Safari 13.0.3

**Problem description**
This is for https://github.com/phetsims/QA/issues/544
At high gravity and at cusps near the ground, the skateboard will lose contact with the track and continue on the ground. In the video, I show it happening on the Measure section of the simulation but I have also been able to reproduce it in Graphs and Playground as well. 

**Steps to reproduce**
1. Open the simulation
2. Click on the Measure section of the simulation
3. Set the gravity to its max value and place the skateboard at the top of the track to allow for maximum speed and let go
4. Wait until the skateboard reaches its maximum height and then (before it reaches the bottom) adjust one side of the track to be either its right or leftmost position and also at its lowest position within the touch area. 

**Visuals**
https://drive.google.com/file/d/1fzbXgq2FSQ_SIXocrkIE2MCs6N1pTaAJ/view?usp=sharing

//Apologies for not uploading a GIF, I'll come back and add it in once I figure out why neither Kap or EzyGif are working

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.1.0-rc.1 2020-09-02 16:48:45 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Language: en-US
Window: 1440x812
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
@jessegreenberg I'm feeling a bit of deja vu here, but I couldn't find the original issue.

I'm fairly certain this occurs because the bottom control point temporarily dips underground while the right control point is being dragged. When the right control point is released, the bottom control point will bump itself above ground.

**Comment by jessegreenberg** [comment]
That is correct @arouinfar, that is what is happening here. This is the decision we made in https://github.com/phetsims/energy-skate-park/issues/45#issuecomment-522398634, and finalized in https://github.com/phetsims/energy-skate-park/issues/45#issuecomment-557624363. I still think this is correct at this time. @arouinfar assigning to you to review, if you agree can you please close?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I agree, let's close.
