### ISSUE TITLE
Legends of Learning moves forward when paused

### ISSUE THREAD

**Issue by DevonQui** [phetsims/energy-skate-park#296]
**Test device**
MacBook Pro

**Operating System**
Catalina 10.15.1

**Browser**
Safari 13.0.3

**Problem description**
This is for https://github.com/phetsims/QA/issues/544
The Legends of Learning pause button doesn't work. When the simulation is paused and you open the Message Logs, the simulation will move forward by approximately 0.5 seconds. 

**Steps to reproduce**
1. Open the Legends of Learning game harness and mount the game
2. Start the game by pressing the start button
3. Play with the simulation as normal to create movement and then press pause
4. Press Open Message Logs and notice how the game moves forward

**Visuals**
https://drive.google.com/file/d/1TgaeKNCYq8HzPYszr4642NrrWSWdxn7Q/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html?legendsOfLearning
Version: 1.1.0-rc.1 2020-09-02 16:48:45 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Language: en-US
Window: 1440x812
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by DevonQui** [comment]
EDIT: This was also an issue found in Collision Lab when testing Legends of Learning functionality. It's starting to seem like this might be affecting more than one sims. I'll be on the lookout for this issue in other sims.

**Comment by brooklynlash** [comment]
Reproduced on all Windows 10 browsers. I will also be on the lookout in the future.

**Comment by DevonQui** [comment]
This was also an issue for Capacitor Lab Basics. Even when paused, when clicking on Message Logs tab on the side of the Legends of Learning screen, the simulation will increment forward usually by half to a full second.

**Comment by arouinfar** [comment]
Looks like this issue should be moved to a common repo. 

@DevonQui thanks for reporting this in other sims. I edited your comments to add links to the appropriate QA issues. Please remember to tag the QA issue, otherwise the developers are unlikely to be aware of this issue (especially since it's in a sim-specific repo for now).

**Comment by jessegreenberg** [comment]
OK, verified by following the above steps. This sort of seems like an issue with the LoL testing harness rather than PhET code so I suspect we will just need notify LoL of the bug. But I am going to poke around a bit more in a common code issue.
