### ISSUE TITLE
Timing of path dots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#298]
Discovered in #297. A user wrote in about the repeatability of the path dots, and my initial thought was that using the Restart Skater button would alleviate the issue. However, it does not.

1. Measure Screen
2. Select slow motion (just makes things a bit easier to see), and drag skater onto track
3. Place probe on a path dot <img width="1019" alt="Screen Shot 2020-10-14 at 6 19 55 PM" src="https://user-images.githubusercontent.com/8419308/96059070-308f5280-0e4a-11eb-9245-9c3a8c9449a8.png">
4. Press Restart Skater. When the skater repeats the journey, there will no longer be a path dot in the crosshairs of the probe. <img width="1017" alt="Screen Shot 2020-10-14 at 6 20 24 PM" src="https://user-images.githubusercontent.com/8419308/96059073-338a4300-0e4a-11eb-8242-6a33f254205f.png">
5. Press Restart Skater a few more times. Notice that the path dots shift slightly each time. (It's most noticeable if you focus on the first few dots that are drawn.)

I would expect that the instant the skater is released is 0.0 s, and then the path dots would be drawn at 0.1 s intervals after that. However, it seems like there is a universal clock running in the background. When the skater is released, path dots will start drawing at the next 0.1 s time step, and continue in 0.1 s intervals, which leads to the slight inconsistencies in the position of the dots.

@jessegreenberg is it possible/reasonable to time the dots relative to the release time of the skater?

**Comment by jessegreenberg** [comment]
I think I fixed this by resetting EnergySkateParkSaveSampleModel.timeSinceSampleSave in this case. @arouinfar can you please review the behavior to verify?

The sensor doesn't detect a hit with a data point unless it is being dragged. So when the new data point goes under the crosshairs it's information is not displayed. Is this something that needs to change?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I'll tag for design meeting to get feedback from the team.

**Comment by arouinfar** [comment]
We discussed this in the 11/5/20 design meeting, and decided not to make any further changes. 

The only caveat is that we should make sure state is properly saved/restored when it comes time for the phet-io design. It sounds like that shouldn't be an issue, though.
