### ISSUE TITLE
Narrow screens can have unexpected overlap of track drag points and tool box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#302]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/544
The measure screen has pre-built tracks that have drag points on their ends. For these tracks it is possible for the drag points to overlap the tool box or go behind the tool on the left if the window is narrow enough. seen on iPad in landscape mode. Can also be seen by adjusting the window size on a computer.

**Visuals**
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/96639391-e50ff500-12de-11eb-97d0-f83fed11fc26.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/96639395-e6412200-12de-11eb-8470-4dae5c765390.png)

**Comment by arouinfar** [comment]
This is really strange. We design things at the iPad aspect ratio, so this should not be happening at all. @jessegreenberg it looks like the sims layoutBounds are a bit off from the standard, see https://github.com/phetsims/joist/issues/542. Could that be the issue?

**Comment by jessegreenberg** [comment]
Hmm, I am not sure - the sim *is* actually using default layout bounds now after https://github.com/phetsims/energy-skate-park/issues/279.

**Comment by jessegreenberg** [comment]
I suspect this is related to changes after #279. It actually doesn't have to be a narrow screen, just any screen using default layout. This isn't a problem for wider screens because the components float out.
![image](https://user-images.githubusercontent.com/6396244/97602063-402da000-19e1-11eb-8cab-1a378dd0d989.png)

**Comment by jessegreenberg** [comment]
@arouinfar would you be willing to reduce the available width of the control point so that overlap isn't possible when the sim is constrained to normal dev bounds?

**Comment by jessegreenberg** [comment]
I made the change to reduce bounds of control points so that it is not possible to overlap. Changed both left and right most control points so they are symmetric. @arouinfar can you please review and give thoughts on whether this change is OK? You can see all control point bounds with ?showPointBounds.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! The updated bounds look great.

**Comment by jessegreenberg** [comment]
OK, thanks! Will pull https://github.com/phetsims/energy-skate-park/commit/00f524afbf1aef4a2c0d92d37c41eb2be2c36844 into release branch.

**Comment by jessegreenberg** [comment]
Cherry-picked into 1.1 release branch.

**Comment by KatieWoe** [comment]
There's still some overlap. @arouinfar is this acceptable?
![Screen Shot 2020-11-09 at 4 21 52 PM](https://user-images.githubusercontent.com/41024075/98608111-c4b4d400-22a7-11eb-9c71-7f7a96044981.png)

**Comment by KatieWoe** [comment]
Only seems to be on first scene

**Comment by arouinfar** [comment]
I think the overlap is fine. In situations like https://github.com/phetsims/energy-skate-park/issues/302#issuecomment-724341372 it is still easy to select the Speed checkbox.
