### ISSUE TITLE
Unexplained errors in debug sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#303]
For https://github.com/phetsims/QA/issues/544.
On Mac 10.15.7 Chrome. When doing the fuzz test on the debug version of the sim, two errors came up immediately. I didn't notice any ill effects and I was in incognito mode, so I don't know if any extensions could do it. I also checked the debug sim in the last rc for EFAC, and didn't see this occur.
![Screen Shot 2020-10-20 at 2 35 57 PM](https://user-images.githubusercontent.com/41024075/96646586-97e55080-12e9-11eb-8410-b131c91ed147.png)

**Comment by jessegreenberg** [comment]
OK I am seeing similar things when running debug build with ?fuzz on Windows 10 Chrome.
![image](https://user-images.githubusercontent.com/6396244/97590273-d3140d80-19d4-11eb-9f84-4c925ad39838.png)

I would be surprised if this is specific to ESP.

**Comment by jessegreenberg** [comment]
I am not seeing this in a debug build of MAL.

**Comment by jessegreenberg** [comment]
I am starting to suspect it is from the numeric library, used in this sim, ESP:B, and fluid-pressure-and-flow. The error is showing up in all three sims in the debug version only.

**Comment by jessegreenberg** [comment]
I created https://github.com/phetsims/sherpa/issues/80 to investigate further, though the issue may move to chipper. Closing issue here.
