### ISSUE TITLE
User request: individual track piece friction

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#304]
> Set friction by track (allow portions of the track to be frictionless and other portions have friction). Allow adjusting the friction for each piece of track added.
> 
> This would allow teachers to develop a virtual lab connecting potential energy to work done by friction based on the distance it took to stop on the piece of track with friction.

**Comment by arouinfar** [comment]
This a cool idea, but I think it would really belong in a sim that focuses on work. Can you move this to the sim request/ideas doc @oliver-phet?

**Comment by oliver-phet** [comment]
Done, closing!
