### ISSUE TITLE
Gravity slider resets with red button to bring back skater

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#306]
**Test device**
MacBook Air
**Operating System**
Mac 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/577
When you press the red button to bring the skater back to the ground after it has gone off screen, the gravity slider resets to 9.8, no matter what it was before. Does not seem to happen with the green button to bring the skater back in its drop position, and only seems to happen with the gravity slider from what I've seen so far. Does not seem to be a new issue, as it was there in the last few QA tests it seems. Not possible to do in Basics as there is no gravity slider.
**Steps to reproduce**
1. Go to any of the screens (this was recorded on measure screen
2. Send the skater off screen and make sure it has a gravity value that is different from default 9.8
3. Press red button and observe gravity slider

**Visuals**
![gravityreset](https://user-images.githubusercontent.com/41024075/98716999-af908180-2349-11eb-9216-a5277245b3ae.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.2/phet/energy-skate-park_all_phet.html?altAccelerationUnits
Version: 1.1.0-rc.2 2020-11-09 18:28:13 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
Language: en-US
Window: 1297x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
It looks like this is also an issue when changing tracks - changing the track will reset the gravity as well.

**Comment by jessegreenberg** [comment]
Fixed in the above commit - @KatieWoe would you mind reviewing master before I merge into the release branch?

**Comment by KatieWoe** [comment]
Looks ok on master

**Comment by jessegreenberg** [comment]
Moved to RC branch.

**Comment by phet-steele** [comment]
This looks fixed to me in 1.1.0-rc.3 👍
