### ISSUE TITLE
Lines on probe box in Measure section with Long string test squish together

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/energy-skate-park#308]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Chrome and Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/578
When doing the long string test on either Firefox or Chrome, in the Measure section, if you put the probe on a point, all the lines in the purple box squish together. Not seen with rtl or double string tests, just long so far. 
Not sure if actually an issue that will appear in real translation, what do you all think?

**Steps to reproduce**
1. Open Measure
2. Place the skater on the ramp
3. Observe when putting the probe on one of the circles

**Visuals**
![espprobe](https://user-images.githubusercontent.com/72031637/98996195-b3f69f00-24ef-11eb-89a1-3245ed9fada8.PNG)
![espporbe2](https://user-images.githubusercontent.com/72031637/98996196-b48f3580-24ef-11eb-8e6e-22e5bd05cdf0.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.3/phet/energy-skate-park_all_phet.html?stringTest=long
Version: 1.1.0-rc.3 2020-11-10 22:44:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Noting that normally, only one letter would maybe be translated in the number box (which seems to cause the oddity above) and it is unlikely to get larger, as it is a unit.
![Screen Shot 2020-11-12 at 5 03 52 PM](https://user-images.githubusercontent.com/41024075/99012183-02fdfd80-250b-11eb-8f6f-d0e677ee9395.png)
![Uploading long.gif…]()

**Comment by arouinfar** [comment]
Nice find @brooklynlash. 

> Noting that normally, only one letter would maybe be translated in the number box (which seems to cause the oddity above) and it is unlikely to get larger, as it is a unit.

Agreed @KatieWoe. In this case, I don't think the stringTest is representative of how these strings will be translated. We can probably blame the layout issues on the long strings in the readout, which isn't realistic. 

@jessegreenberg unless you see something obvious that needs to be fixed here, I'm fine with closing this issue.

**Comment by jessegreenberg** [comment]
Hmm, this does seem a little strange. I would not expect layout to change like this. Ill investigate why it is happening at least.

**Comment by jessegreenberg** [comment]
The spacing between them is a fixed value, so the layout with values is the layout I would expect. So I think the question is why it looks more spaced out when displaying the '-' dash.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, moving to release branch.

**Comment by brooklynlash** [comment]
Looks fixed on Windows 10 Chrome for rc4.

**Comment by jessegreenberg** [comment]
Thanks!
