### ISSUE TITLE
Mouse moves faster than playground track

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#309]
For https://github.com/phetsims/QA/issues/578. On Lovelace ChromeOS device. Did not seem to happen on Mac 10.15 Chrome. I did see this on Basics, so it doesn't seem to be new.
When dragging the playground tracks out of their box, the mouse seems to move faster than the track. So if you move slowly, nothing seems amiss, but if you move quickly, or even at a normal pace, a gap seems to develop between your mouse and the track you are dragging.
(Sorry for the sound. Tried to make a gif, but website was failing)
https://drive.google.com/file/d/1pGWjEagNago3ETlABctuNU2DaMSdzpox/view?usp=sharing

**Comment by arouinfar** [comment]
Since the behavior matches the published version of Basics, I'm inclined to do nothing here, but I'll let @jessegreenberg review and make the final decision.

**Comment by jessegreenberg** [comment]
I am seeing this happen on my laptop, but only when I try to move the track *really* fast, like I have to flick my trackpad to move my finger quick enough. I think that indicates it may be related to sim performance, like on a slower machine it may be more likely to happen.

I am also able to get it to happen when dragging the existing tracks, so I don't think it is related to the toolbox, but just the track drag handler itself.

**Comment by jessegreenberg** [comment]
Indeed, it is way easier to have happen with the phet.chipper.makeEverythingSlow().

**Comment by jessegreenberg** [comment]
It has to do with calculation of the startOffset for the drag handler code.
```js
    if ( !this.startedDrag ) {
      track.draggingProperty.value = true;

      // we may not have determined point offset if first down hit toolbox
      this.calculateStartOffset( event );
      console.log( this.startOffset );
      this.startedDrag = true;
    }
```

This is always called, even if the track wasn't pulled from the toolbox. And if the mouse is moved very quickly in that first drag, the offset is incorrect creating the distance between mouse and track. This is the only cause of separation, after the initial drag it doesn't separate further.

**Comment by jessegreenberg** [comment]
Simply removing the `this.calculateStartOffset` in the snippet above (currently line 123 in TrackDragHandler) seems to fix this issue. Every time I try to remove the track from the toolbox, we always call `calculateStartOffset`, so I am wondering if the comment 
> // we may not have determined point offset if first down hit toolbox

Maybe it was important before we began to use the current event-forwarding pattern for the drag listener? So I am curious about removing that line and all of the `startedDrag` related code in TrackDragHandler.

But this could be destabilizing, and is something to pick up after the release since @arouinfar didn't find this too offensive.

**Comment by jessegreenberg** [comment]
The forwarding pattern was only recently added in #239, so it seems reasonable that the `startedDrag` related code can now be removed. I will do this, but won't merge it into the release branch.

**Comment by jessegreenberg** [comment]
This should be fixed by the above commit, @KatieWoe would you mind testing to make sure this is fixed in master?

**Comment by KatieWoe** [comment]
This looks fixed on master

**Comment by jessegreenberg** [comment]
Great, thanks! We are not going to move this to the release branch, so closing this issue.
