### ISSUE TITLE
Use griddle for the bar graph?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#31]
It would be nice if the bar graph could use griddle, the common repo for graphs. Common code may already have a solution for the challenges I am facing in #25 with respect to stroking the bars and transparent rectangles.

The challenge is that ESP has a separate layer for bar graph foreground/background, because the foreground must use webgl for performance while the background must not. But maybe I can still use portions of griddle.

**Comment by jessegreenberg** [comment]
For these reasons, I don't think we can use BarChartNode, but maybe we can still use BarNode for the bars

**Comment by jessegreenberg** [comment]
I don't think we can use griddle with the current setup. Here is one potential way we could get this to work with the setup in ESP. But here is one way, changing the structure slightly.
- BarGraphBackground contains the axis and buttons and arrows, added behind the EnergySkateParkScreenView webgl layer.
- BarGraphForeground contains the bars, added on top of the foreground in the EnergySkateParkScreenView webgl layer.
- BarGraphLabelTopLayer contains the labels, added on top of the foreground and on top of the webgl layer in EnergySkateParkScreenView.

I am hesitant to use griddle still, because BarNode has other nodes that we do not want in the webgl layer of EnergySkateParkScreenView, like the arrow nodes.

**Comment by jessegreenberg** [comment]
Whether or not we can use griddle in this sim depends on https://github.com/phetsims/griddle/issues/32.

**Comment by jessegreenberg** [comment]
Now that we have a decision in #42, we can try to use griddle again. That will be done next as part of #66

**Comment by jessegreenberg** [comment]
The other portion that is unsuported by griddle is
```js
        // Floor and protect against duplicates.
        // Make sure that nonzero values
        // For thermal and total energy, make sure they are big enough to be visible, see #307
        // For kinetic and potential, they must go to zero at the endpoints to reach learning goals like
        //   "The kinetic energy is zero at the top of the trajectory (turning point)
        var smallValueThreshold = showSmallValuesAsZero ? 1 : 1E-6;
        var answer = absResult > 1 ? Math.floor( result ) :
                     absResult < smallValueThreshold ? 0 :
                     1;
```

**Comment by jessegreenberg** [comment]
@samreid @arouinfar here is what published sim looks like when skater is at track endpoint:
![image](https://user-images.githubusercontent.com/6396244/56774749-0cd9d780-6792-11e9-8dab-d1429b9b47d5.png)

Compared to master using griddle:
![image](https://user-images.githubusercontent.com/6396244/56774794-30048700-6792-11e9-96eb-00d7441fcb16.png)

Setting `borderWidth` to 0 in griddle/BarNode it looks like
![image](https://user-images.githubusercontent.com/6396244/56774852-66da9d00-6792-11e9-8bfe-c0914e516c27.png)

Though it was more difficult for me to reach an invisible KE bar (I had to use step button), and bar strokes were requested in #25.

Is this sufficient or should we add support to griddle to hide bars if values are too small. Maybe more generally we could add support to griddle to hide bars for any reason.

**Comment by samreid** [comment]
It seemed important during design that those bars would disappear completely.  I like your idea to investigate doing that in griddle.

**Comment by jessegreenberg** [comment]
OK, thanks! Ill take it over there.

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/griddle/issues/35

**Comment by arouinfar** [comment]
> It seemed important during design that those bars would disappear completely. I like your idea to investigate doing that in griddle.

Agreed! Seems like a good addition to griddle.

**Comment by jessegreenberg** [comment]
Griddle is now being used for the bar graph in this sim. BarGraphForeground and BarGraphBackground have been collapsed into EnergyBarGraph. At this point I think BarGraphForeground and BarGraphBackground can be removed for #66
