### ISSUE TITLE
Slider pixel polishes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#311]
@KatieWoe reported in https://github.com/phetsims/QA/issues/578#issuecomment-728427972:

>On MacOS 11 Safari, I noticed a bit of overlap with longer strings and the thumbs of sliders.
><img width="254" alt="Screen Shot 2020-11-16 at 4 35 37 PM" src="https://user-images.githubusercontent.com/41024075/99321450-12db5180-282b-11eb-93fa-8b796a1734a6.png">

This issue is not limited to macOS/Safari or i18n. The slider thumb is a bit too big, and the tick mark length is a bit too short. The result is that the thumb touches letters that descend below the baseline. This affects both ESP and ESPB.
![image](https://user-images.githubusercontent.com/8419308/99325622-ff80b400-2833-11eb-929b-67b9795929b1.png)
![image](https://user-images.githubusercontent.com/8419308/99325633-060f2b80-2834-11eb-8bfa-9c21a03e0d9b.png)

Luckily, the slider options are factored out into [EnergySkatParkConstants.js](https://github.com/phetsims/energy-skate-park/blob/master/js/common/EnergySkateParkConstants.js#L39-L43) which made it really easy to test out a few options locally.  I reduced the `thumbSize` height to 23 and increased the `majorTickLength` to 11. This removes the overlap between the slider label and thumb, but does not change the overall height of the panel on the Intro Screen (where vertical space is tight).

| Before | After |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/8419308/99326199-107df500-2835-11eb-8d1d-107d078023e3.png) | ![image](https://user-images.githubusercontent.com/8419308/99326146-f3e1bd00-2834-11eb-9aca-d5264e02db2a.png) | 

This is honestly quite minor, so I'm hesitant to do anything so close to the finish line. @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
@arouinfar I think that is a pretty "low risk" change and it does seem worth doing as that overlap is not quite up to our normal standards in terms of aesthetics.

**Comment by arouinfar** [comment]
Thanks @ariel-phet. Let's go ahead and proceed @jessegreenberg.

**Comment by jessegreenberg** [comment]
I changed the slider values to the ones you used in https://github.com/phetsims/energy-skate-park/issues/311#issue-744324575, can you please review @arouinfar? If all looks OK I will put the change in the release branch.

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by jessegreenberg** [comment]
Moved to release branch.

**Comment by phet-steele** [comment]
This looks great in 1.1.0-rc.4! 🥳
