### ISSUE TITLE
Should this sim use ZoomButtonGroup?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#313]
In https://github.com/phetsims/scenery-phet/issues/645 it was mentioned that ZoomButtonGroup may be replacing ZoomButton. The ZoomButtonGroup looks like 

![image](https://user-images.githubusercontent.com/6396244/100015103-66a6e700-2da5-11eb-95a8-33d54a902471.png)

But it is being used in all new charts and in things that used to use ZoomButton, like SeismographNode.

@arouinfar should the ZoomButtons in this sim be replaced with ZoomButtonGroup? Not for imminent release, but near future and PhET-iO work?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I commented in https://github.com/phetsims/scenery-phet/issues/645 for clarification about future support for buttons with the magnifying glass icon.

We're definitely not going to make this change for the upcoming release, and any decision we make about the appearance of the zoom buttons can be deferred until we work on the phet-io design of this sim.

**Comment by samreid** [comment]
To clarify, after https://github.com/phetsims/circuit-construction-kit-common/issues/620 ZoomButtonGroup supports magnifying glasses or +/- icons.  This issue is more about eliminating the duplicated code in Energy Skate Park that creates separate buttons, applies touch areas, puts them in a VBox, wires up listeners, etc.  I agree this will be important for PhET-iO or a11y but we don't necessarily need to hold off until then.  (Also, I understand if an imminent deadline prevents making this refactor in the near future).

**Comment by pixelzoom** [comment]
Further clarification... 

This does not necessarily mean changing the look of the zoom buttons.

There are 2 subclasses of ZoomButtonGroup.  A primary motivation for changing to one of these subclasses it that you will get consistency of PhET-iO implementation, and not have to instrument sim-specifiic code. 

MagnifyingGlassZoomButtonGroup uses the same magnifying glasses currently used in this sim. If you want this sim to look the same, use this class. 

PlusMinusZoomButtonGroup is the more moderning looking +/- buttons that @jessegreenberg showed above.  Use this class if you want to change to buttons that look like this:

![image](https://user-images.githubusercontent.com/6396244/100015103-66a6e700-2da5-11eb-95a8-33d54a902471.png)

**Comment by pixelzoom** [comment]
Here are the 2 subclasses of ZoomButtonGroup shown on the Buttons screen of the scenery-phet demo. PlusMinusZoomButtonGroup on the left, MagnifyingGlassZoomButtonGroup on the right.

<img width="398" alt="screenshot_882" src="https://user-images.githubusercontent.com/3046552/109216237-80274880-7771-11eb-87c3-195a3fc31805.png">

**Comment by jessegreenberg** [comment]
This sim is now using MagnifyingGlassZoomButtonGroup.  Behavior is the same and a side-by-side comparison of the sim before and after shows no change in look or layout. EnergyGraphZoomButton could be deleted.

Since MagnifyingGlassZoomButtonGroup exists there is no need to discuss changing the look in this sim so this issue can be closed.
