### ISSUE TITLE
Strings are not translatable in Energy Skate Park 1.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#317]
@oliver-phet received notice that it wasn't possible to translate strings in this sim. I checked in with @jbphet who said this is probably because "nested" strings are not yet supported by rosetta. I incorrectly thought that "nesting" was the new way to organize strings moving forward, but that is not the case yet. The change to nest strings was made around the time of code review in https://github.com/phetsims/energy-skate-park/issues/220.

See https://github.com/phetsims/rosetta/issues/215 for status of rosetta and nested strings.

For now, should we change strings back to a flat structure and then redeploy in a maintenance release of energy-skate-park?

**Comment by jbphet** [comment]
> For now, should we change strings back to a flat structure and then redeploy in a maintenance release of energy-skate-park?

Yes, that would be my recommendation.

**Comment by jessegreenberg** [comment]
OK sounds good - I think the best way would be to turn the nested list into dot separated entries in the strings file. This way we don't have to change anything at the usages of these strings in the sim.

```
  "physicalControls": {
    "gravityControls": {
      "gravity": {
        "value": "Gravity"
      },
```

should become
```
  "physicalControls.gravityControls.gravity": {
    "value": "Gravity"
  },
```
and the usage will still be 
```
const controlsGravityLabelString = energySkateParkStrings.physicalControls.gravityControls.gravity;
```

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/QA/issues/586 was created to spot check this change to the strings file before deploying again.

**Comment by jessegreenberg** [comment]
The sim was redeployed with this change here: https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_en.html.  @oliver-phet can you please check and see if the strings look better with the translation utility? If so, can you please let the trusted translator that reported this know that this is fixed?

**Comment by oliver-phet** [comment]
It looks like 4 other translations were already submitted that only contain the title. I'll ping those translators, too.
