### ISSUE TITLE
Add mass combo box

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#32]

**Comment by jessegreenberg** [comment]
@arouinfar the design document indicates that this sim will use a grid-like box for controlling masses (at least in intro screen). Is that still true? If so, here is the relevant issue for generalizing this component:
https://github.com/phetsims/sun/issues/363

**Comment by arouinfar** [comment]
@jessegreenberg it's quite possible we'll use the grid-like combobox, but let's not worry about generalizing it until it's been discussed further in design meeting.

For now, can you use a standard combobox with the options from Java. I'll open an issue to work on skater artwork, but in the meantime, I think you can go ahead and simply scale the ESPB skater artwork.

**Comment by jessegreenberg** [comment]
Sounds great @arouinfar. I added a basic combo box for now, it just shows values of masses. Right now, it is layered on top of everything, I will work on getting it layered at the same level as the control panel and under the skater.

**Comment by jessegreenberg** [comment]
The combo box has been added, and I added the ability for nodes to be inserted into the right layer by subtypes of EnergySkateParkScreenView.

**Comment by jessegreenberg** [comment]
Removing assignment until there is further discussion.

**Comment by jessegreenberg** [comment]
Closing, this will get folded into other work.
