### ISSUE TITLE
User suggestion: add a limited 'Lab' screen

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#320]
> Have a 'Lab' tab that doesn't show direct energy measurements in the setting but still gives measuring tools such as the height, speedometer, and track. This is a little more like how we would do it in the lab (directly measuring height and speed) and would allow using the skatepark setting as a virtual lab to find the relationships between those things and be able to make observations about what is happening without the abstract concept of energy being on screen.

**Comment by arouinfar** [comment]
> Have a 'Lab' tab that doesn't show direct energy measurements in the setting but still gives measuring tools such as the height, speedometer, and track.

Removing energy representations is antithetical to the goals of the simulation. That said, if the user's concerns are more about the quantitative energy measurements, I would advise them to use the `screens` query parameter to use only the 1st or 4th screens.  On these screens, the energy representations are qualitative and are off by default.

**Comment by oliver-phet** [comment]
Replied back to user, closing.
