### ISSUE TITLE
Sim may freeze when mouse leaves iframe

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#322]
**Test device**
Dell and Mac
**Operating System**
Win 10 and MacOS 11
**Browser**
Chrome and Safari
**Problem description**
For https://github.com/phetsims/QA/issues/642. Wasn't able to recreate on published, so it seems connected to the fix. When dragging an object (or even dragging nothing) outside the iframe and letting go, the sim freezes and throws a console error.

**Visuals**
<img width="413" alt="error" src="https://user-images.githubusercontent.com/41024075/117067022-b986b200-ace6-11eb-9362-1ce1ff73cf9f.png">
![releaseoutofiframe](https://user-images.githubusercontent.com/41024075/117067025-ba1f4880-ace6-11eb-9202-d8e9a8484b14.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.2-rc.1/phet/energy-skate-park_en_phet.html
Version: 1.1.2-rc.1 2021-04-23 18:39:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Matthew-Moore240** [comment]
I was also experiencing this exact issue on Win 10 chrome.

**Comment by jonathanolson** [comment]
I believe this is handled with the above commit (using master's copy of interrupt inline), can you try https://phet-dev.colorado.edu/html/energy-skate-park/1.1.2-rc.3/phet/energy-skate-park_en_iframe_phet.html

**Comment by KatieWoe** [comment]
Looks ok in the above link

**Comment by jonathanolson** [comment]
Sounds good, closing this issue.

**Comment by KatieWoe** [comment]
This is back in https://github.com/phetsims/QA/issues/649
<img width="960" alt="comebackagain" src="https://user-images.githubusercontent.com/41024075/118547950-f30fe200-b716-11eb-884e-3df8c8c3f2ae.png">

**Comment by jonathanolson** [comment]
Looks like this is mainly due to me not updating it to rc.3 in the maintenance internals, should be handled. Will verify with next test.

**Comment by jonathanolson** [comment]
Closing, handled in maintenance release deployment.
