### ISSUE TITLE
Fonts in Arabic translation

### ISSUE THREAD

**Issue by issamali67** [phetsims/energy-skate-park#324]
@jbphet Fonts in the Arabic translation of Energy Skate Park appear smaller. Could live with some. Exception is the translation for Gravity and Friction, which is more subtle. See the attached for explanation. Also the Arabic translation to mass is small. I attach the Arabic and English screen shots.

<img width="996" alt="EnergySkateParkArabic" src="https://user-images.githubusercontent.com/64868917/122098787-83048280-cdce-11eb-8325-d763c6bfca7f.png">
<img width="996" alt="EnergySkateParkEnglish" src="https://user-images.githubusercontent.com/64868917/122098792-84ce4600-cdce-11eb-848b-d9cfe1876eae.png">

**Comment by jbphet** [comment]
@issamali67 and I reviewed this, and there aren't any straightforward fixes in this case because these can't be altered with max width values.  I'm going to close.
