### ISSUE TITLE
User request: zero gravity

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#331]
> In the old version of Energy Skate Park, zero gravity is available.  The new version is lacking that.   In my lab, I ask the students to make a crazy roller coaster.  The students are delighted to make a space coaster.  Can't do that in the new version.  Can't sneak in a Newton's First Law learning opportunity.

**Comment by arouinfar** [comment]
Zero gravity is difficult. In Java, the skater wears a rocket pack that students use the arrow keys to apply a thrust. The current model does not support this at all, and it would likely cause issues for supporting alt input in the future. We would also need to update the artwork.

It's trivial to set g=0, but without the rocket pack, the sim is boring. Yes, it demonstrates Newton's First Law, but that isn't a learning goal of this sim. Newton's Laws are much better supported by other sims.

Zero gravity is a fun gimmick, but it would be costly to implement and is not central to the learning goals.
