### ISSUE TITLE
This sim uses buggy GaugeNode option `updateWhenInvisible`.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#334]
While porting scenery-phet.GaugeNode to TS, I noticed a bug that affects this sim.   In GaugeNode constructor, the option is `updateWhenInvisible`,  but the logic checks for `updateOnlyWhenVisible`:

```js
    options = merge( {
      ...
         updateWhenInvisible: true,
      ...
    }, options );
...
    if ( options.updateOnlyWhenVisible ) {
      this.visibleProperty.link( visible => {
        visible && updateNeedle();
      } );
    }
```

In EnergySkateParkScreenView, it's using `updateWhenInvisible`:

```js
this.speedometerNode = new ValueGaugeNode( model.skater.speedProperty, 
  ...
      updateWhenInvisible: false,
```

This was fixed in https://github.com/phetsims/scenery-phet/commit/164b7e05d771cc4edf2cc429fb15b1bd4de4dbe1 as part of TS conversion.  I ran the sim, and it looks OK to me, but I'm not very familiar with it.  So I wanted to alert you in case there's some change in behavior to this sim.

**Comment by jessegreenberg** [comment]
This is working well, thanks. I tested the GaugeNode in this sim with the GaugeNode visible/invisible in various states and saw that the value was always correct. I verified that the needle is not being rotated in GaugeNode when it is in invisible in this sim.

CLosing.
