### ISSUE TITLE
Add skater choice to all ESP screens and ESPB

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#335]
Discussed in design meeting 4/28/2022. Currently, we are creating localized character sets in sims and noticed that the skater choice isn't available on all screens/flavors of ESP, and it would be nice to add support for this.

We would like to add the skater choice RadioButtonGroup to the Measure and Graphs screens of ESP, as well as all screens of ESPB. Basically, the mass control will always look like this:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/8419308/166068315-83b441d5-ff7c-4a4a-8faa-c1df2f22a847.png">.

Previously, the skater choices were only available on the Playground screen of ESP, but we later decided to add it to the Intro screen as well, see https://github.com/phetsims/energy-skate-park/issues/263. I don't think we had a documented reason for omitting the skater choice controls on the middle two screens, and there is enough room in the control panel to include the skater choice.

**Comment by jessegreenberg** [comment]
OK added to all ESP/ESP:B. I think its looking good everywhere except the "Measure" screen where there isn't quite enough space. @arouinfar what do you think we should do on that screen?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! 

> @arouinfar what do you think we should do on that screen?

The overlap on the Measure screen looks pretty small, and I could live with it the way it is. 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/8419308/166830614-59210ff5-1c3d-4289-9cfa-1552b755f703.png">

If we want to remove the overlap with the ground, there are a few things we could try (would universally apply to all screens):
* Reduce the size of the tool icons to shorten up the toolbox (could probably be 10-20% smaller and still look ok)
* Reduce the max height of the icons next to the checkboxes and then tighten up the space between the checkboxes
* Reduce the height of the gravity ComboBox (seems to be some extra padding above/below the text)

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! Everything looks good in master, and I think the toolbox is appropriately sized.
