### ISSUE TITLE
Update screen icon to include new skaters

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#340]
The Intro and Playground screens include skater artwork that should be updated before republishing.

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/8419308/175144872-730e33e5-e8de-4c1a-91f0-0ec91f497a3b.png">

Questions:
* Which skater(s) should we include in the screen icons?
* How should the screen icons adapt to the skater set?

**Comment by jessegreenberg** [comment]
During design meeting today we discussed that the first two screen icons could be drawn so that the skater images are easily replicable with drawing code and would update with character set preferences.

**Comment by jessegreenberg** [comment]
We would want this for all screens of basics as well.

**Comment by jessegreenberg** [comment]
It is turning out to be difficult to draw track icons. TrackNodes require the model and the model is not constructed until after the sim is constructed. The screen icons need to be available before the sim is constructed.

Perhaps another way to do this is to use the images that we have without the skaters and with code draw just the skater over the image. This would take less time to implement anyway. The drawing code required to create each screen icon would have been significant.

@arouinfar would this work for you, would you be able to produce screenshot images without skaters?

**Comment by arouinfar** [comment]
Thanks for the investigation @jessegreenberg. 

> Perhaps another way to do this is to use the images that we have without the skaters and with code place the skater over the image. 

This approach sounds reasonable to me. I'll work on creating the images.

**Comment by arouinfar** [comment]
@jessegreenberg here are the updated assets for the screen icons without skaters. I deleted the pie chart from the Intro Screen, but let me know if you want me to add it back in.

Only the Intro Screen and Playground Screen icons feature skaters, so those were the ones I re-exported from Illustrator. 

[energy-skate-park-updated-screen-icons.zip](https://github.com/phetsims/energy-skate-park/files/9048562/energy-skate-park-updated-screen-icons.zip)

**Comment by jessegreenberg** [comment]
Awesome, thanks @arouinfar - If it is easy, would you mind adding the pie chart back in? I could draw it but it is not associated with the image in code.

**Comment by arouinfar** [comment]
@jessegreenberg I added the pie chart back in, so here are the updated set of screen icon assets:
[esp-screen-icons.zip](https://github.com/phetsims/energy-skate-park/files/9066988/esp-screen-icons.zip)

**Comment by jessegreenberg** [comment]
@AgustinVallejo would you mind working on this? The idea was to make the screen icons update with the localization selection. @arouinfar provided new screen icons in https://github.com/phetsims/energy-skate-park/issues/340#issuecomment-1178162452 without skaters so that we can put the skater image in the right place and then update the image when the `EnergySkateParkPreferencesModel.skaterCharacterSetProperty` changes.

Let me know if you have any questions!

**Comment by arouinfar** [comment]
@AgustinVallejo the icons look good in master. Feel free to close if there isn't anything else remaining for this issue.

**Comment by jessegreenberg** [comment]
Changes look great @AgustinVallejo, thanks!
