### ISSUE TITLE
Rectify slider and controls names

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#344]
https://github.com/phetsims/tandem/issues/267 revealed that there are places where a NumberControl is being instantiated but called a Slider.  I renamed the tandem, but the class hierarchies should be renamed to update it as well.  I'll add 2 TODOS showing the entry points for the problems.

**Comment by marlitas** [comment]
Re-assigning to myself for the new character set publication.

**Comment by marlitas** [comment]
@samreid The TODO's you highlighted are actually sliders. This is what the documentation in `PhysicalSlider.ts` says:
```
This is just a slider with a label and labeled tick marks. It extends
NumberControl to leverage the layout of the label and slider so that it conveniently matches the layout
with other NumberControls used in this sim.
```

I think the tandems should be renamed to use "slider" instead of numberControl to match the implementation strategy. At the least, the classes should not be renamed, since they clearly describe what is actually being used and displayed for the sim. What are your thoughts here?

**Comment by samreid** [comment]
PhysicalSlider extends PhysicalNumberControl which extends NumberControl. So it is more of a "has a" slider rather than "is a" slider, since it doesn't extend HSlider, VSlider or Slider. That's why the `tandemNameSuffix: 'Control',` was in play. I'm not sure what's best. I'm not really sure why the sim wants to use NumberControl to create a slider instead of just creating a slider.  Not sure how much time you want to spend here.

**Comment by marlitas** [comment]
@samreid and I talked and we decided that things are fine as-is. We are closing this issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by Luisav1** [comment]
Removed the unnecessary TODO left over. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by Luisav1** [comment]
Sorry, missed removing a TODO referencing this issue. Closing.
