### ISSUE TITLE
Add the UI for swapping out skater images for localization work

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#345]
From https://github.com/phetsims/joist/issues/814, but this issue is just for the skater character control.

**Comment by arouinfar** [comment]
@jessegreenberg @AgustinVallejo @marlitas 

Can we move the Region and Culture control so that it appears before the locale selections? It's easy to overlook when it's at the bottom of the dialog.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/8419308/204860597-9fb01b70-1739-4075-87d2-debb99d82723.png">

**Comment by arouinfar** [comment]
Thanks @marlitas!

Other remaining design questions:
* Verify the names of the skater sets, in particular "Africa - Conservative"
* Decide which skater headshot to use in the ComboBox. Currently, we use skater 1, but both African sets have the same skater 1. 
  <img width="246" alt="image" src="https://user-images.githubusercontent.com/8419308/204862793-c790a233-41f1-40a5-b228-7e61d315849a.png">

Neither of these issues should block dev testing, but they should be finalized before we go to RC.

**Comment by marlitas** [comment]
@arouinfar That switch has been made and is pushed up to master. Let me know if there's any feedback or additional changes.

**Comment by arouinfar** [comment]
Looks great, thanks @marlitas!

I'll leave this open and self-assigned since there are still some open design questions.

**Comment by kathy-phet** [comment]
Regarding the names, here are some options 

- Africa (Modest Dress)
- Africa (Modest Clothing) 
- Africa (Modest Apparel) 
- Africa (Modest)

I think "Conservative" is too loaded of a term - it could mean political, religious, etc. We are focused here just on clothing specifically. What do you think, @arouinfar? Should we ask our PhET Fellows in Arabic-speaking Africa?

**Comment by kathy-phet** [comment]
@arouinfar - 

- Regarding the initial skater, I think "Skater 1" is fine for both sets. 
- We are assuming that the younger girl is young enough not to need more covering, which I think is fine. We can see if we get any feedback on that in the future.

**Comment by arouinfar** [comment]
Discussed with @kathy-phet and we decided:

* Let's use "Africa (Modest)". I will reach out to @solaolateju and @zamb6873 to consult with their network or appropriate PhET Fellows to get input on the term. 
* We can use skater 1 for the ComboBox icon, no change is necessary.

@jessegreenberg @AgustinVallejo @marlitas let's update the language to "Africa (Modest)" before RC. The term may change again before publication, but a string change should be a fairly safe cherry-pick later.

**Comment by marlitas** [comment]
@jessegreenberg and @AgustinVallejo, let me know if you need any help or changes on the preferences side for this.

**Comment by AgustinVallejo** [comment]
Names have been changed!

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo looks good. This issue no longer blocks RC testing.

Here's what it currently looks like:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/8419308/208531702-8d358c33-d60b-44f8-a956-04d76742f720.png">

I'll leave this self-assigned, and report back when there are updates from Sola and Zach.

**Comment by solaolateju** [comment]
Hi, @arouinfar works with most people. It is popular across the fashion industry, religion, and geography.

**Comment by arouinfar** [comment]
Thanks @zamb6873 @solaolateju! Let's proceed with "Africa (Modest)", closing.
