### ISSUE TITLE
Skater position changes when switching from people to animals while paused

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#353]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/862, this is minor, but when I cycle through the skaters while paused, the animals positions are different from the people positions. The elephant changes position the most. 

Also seen in the published version. 

**Steps to reproduce**
1. On any screen and with any character set, place the skater on the track and then press Pause.
2. Cycle through all of the skaters--the animals won't be in the same spot as the people. 

**Visuals**

https://user-images.githubusercontent.com/87318828/205972959-efac80ab-33ff-4b85-b059-6ac96807bc0d.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-dev.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-dev.1 2022-12-02 17:27:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1417x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, good catch!

So when the skater has no rotation the red dot for the skater position for animal characters aligns well with human characters. So there must be something off around here, like maybe the order of the multiplyMatrix calls:

```js
      // Rotate about the pivot (bottom center of the skater)
      const rotationMatrix = Matrix3.rotation2( angle );
      matrix.multiplyMatrix( rotationMatrix );
      rotationMatrix.freeToPool();

      const scale = massToScale.evaluate( mass );
      const scalingMatrix = Matrix3.scaling( scale );
      matrix.multiplyMatrix( scalingMatrix );
      scalingMatrix.freeToPool();

      // Think of it as a multiplying the Vector2 to the right, so this step happens first actually.  Use it to center
      // the registration point
      const translation = Matrix3.translation( -imageWidth / 2, -imageHeight );
      matrix.multiplyMatrix( translation );
      translation.freeToPool();
```

**Comment by jessegreenberg** [comment]
OK, should be fixed in the above commit @Nancy-Salpepi can you please confirm?

**Comment by jessegreenberg** [comment]
Excellent, thanks!
