### ISSUE TITLE
Dot below skater has red outline at max mass

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#354]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/862, when I set the Mass to max, with the Path checkbox checked, there is a red outline around the lavender dot. Seen on the Intro and Measure screens. 
Also happens in published. 

**Steps to reproduce**
On the Intro Screen:
1. Check the Path checkbox
2. Increase the Mass to max value

**Visuals**
<img width="224" alt="Screenshot 2022-12-06 at 3 44 22 PM" src="https://user-images.githubusercontent.com/87318828/206020976-1016f5fc-dcb6-42b9-944e-e672449305be.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-dev.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-dev.1 2022-12-02 17:27:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1524x772
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Fixed by making the red dot invariant to mass changes.

**Comment by Nancy-Salpepi** [comment]
FYI @AgustinVallejo when zoomed in, the dot at ANY mass looks like this:
<img width="391" alt="Screenshot 2022-12-19 at 12 23 19 PM" src="https://user-images.githubusercontent.com/87318828/208484356-6f06d64e-5533-4504-9c37-5062a33a6a26.png">

**Comment by AgustinVallejo** [comment]
Looking into it, it seems to have happened even before this change. The website version also has it. Should we open an independent issue regarding this? @arouinfar

**Comment by AgustinVallejo** [comment]
It is not an issue of the red dot, but the path. It seems to clip through the ground when the Sim is zoomed.

![image](https://user-images.githubusercontent.com/37052186/208486390-8538e3d6-303a-46c1-8718-7568597dcb50.png)
