### ISSUE TITLE
Return Skater Icon out of view after changing window size

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#355]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
This is definitely an edge case, but thought I would report:

For https://github.com/phetsims/qa/issues/862, on the Playground Screen, if I set up track on the left side of the play area and then change the window size using 'Full Screen' in the PhET Menu or by grabbing the corner, the green Return Skater Icon will no longer be on the screen. 

**Steps to reproduce**
1. On the Playground Screen, set up a piece of track on the left side of the screen so that the skater will jump off the right side
2. Let a skater skate off the track
3. Select 'Full Screen' or manually change the window size

Also seen in published. 

**Visuals**

https://user-images.githubusercontent.com/87318828/206213173-efdc00f2-ba03-4b79-9146-68d8ea8013bf.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-dev.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-dev.1 2022-12-02 17:27:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1524x772
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, seems good to fix. The button is pushed back into view around here: https://github.com/phetsims/energy-skate-park/blob/66f6b2cd6d1ea2c48fa472f18a58d195affd32b9/js/common/view/EnergySkateParkScreenView.js#L432-L443

But we probably need to do similar work in the `layout` function if a re-layout makes the button go off screen. @AgustinVallejo can you look into this as part of the localization work? Let me know if I can help!

**Comment by AgustinVallejo** [comment]
Working on this... Curious of the following: The logic is to set the top to 5 if it goes off bounds... Should it do the same for the left attribute? 

Is the following overlap allowed? (Look at the green return skater button overlapping with Energy accordeon)
![image](https://user-images.githubusercontent.com/37052186/207084224-87f35510-a2d6-4e4c-90ee-6b6f2b2b95b1.png)

**Comment by AgustinVallejo** [comment]
The overlap also happens when it's inside the play area (with control panel as well), so I guess it's not part of this issue.
Closing.

**Comment by Nancy-Salpepi** [comment]
I can't verify that this is fixed because the Reset All button seems to be broken now.
