### ISSUE TITLE
Drag interactions aren't interrupted with Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#357]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 16

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/862, if I am holding the track or skater with one finger and I press Reset All with another,  the positions aren't reset. 

All seen in published. 

**Steps to reproduce**
Here is an example:
1. On the Intro Screen, grab the skater and hold them high above the track. 
2. Press Reset All with another finger.
3. Lift your finger off where the skater was--the skater will reappear there.

**Visuals**

https://user-images.githubusercontent.com/87318828/206273889-639cf4d2-1fd7-47cb-84bd-756aea45986b.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-dev.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-dev.1 2022-12-02 17:27:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1524x772
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, this would be good to fix. This class of problems is usually resolved by adding an `interruptSubtreeInput()` call to the reset listener like in BAMScreenView.js. I think @AgustinVallejo is going to be working on this and new localization features, so assigning to him.

**Comment by AgustinVallejo** [comment]
Don't have way of testing this as it relies on multitouch. Reassigning to @Nancy-Salpepi, feel free to re-open if this hasn't been fixed.

**Comment by Nancy-Salpepi** [comment]
I can't verify that this is fixed because the Reset All button seems to be broken on master now.

**Comment by Nancy-Salpepi** [comment]
Looks good on my end!
