### ISSUE TITLE
Should skater selection be maintained when switching region?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#359]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/862
When switching between different regions for the skaters, the skater selected is switched back to the 1st box. It would make more sense to me if the same box was selected (such as the 4th box staying selected). This is especially the case when switching between the two African sets, as most of the skaters are the same.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-dev.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-dev.1 2022-12-02 17:27:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Good thought. We did this first because it was easiest, and there is code specifically resetting it to the first character of the set. I am not sure if this is what design intended. @arouinfar can you comment on what you would like? Also @AgustinVallejo FYI.

**Comment by arouinfar** [comment]
@jessegreenberg @AgustinVallejo I think it would be a nice touch if the radio button selection (e.g. 5 of 8) could be maintained when switching sets, but it's not a design requirement. I don't think it's worth significant development time/refactoring to achieve. 

If it's a change you'd like to make, but it's not feasible within the current milestone, feel free to defer. If it introduces too much complexity, I'm also fine closing as wontfix.

**Comment by arouinfar** [comment]
Tagging for the 1.2 milestone since we need to decide if this issue needs to be addressed or not. We can untag it from the milestone if we decide to defer.

**Comment by kathy-phet** [comment]
@arouinfar - There is some design logic to being back at Skater 1 if you change the region, so I don't see this as a design requirement.

**Comment by arouinfar** [comment]
Thanks @kathy-phet. I agree, it's not a design requirement. Let's go ahead and punt on this, closing.
