### ISSUE TITLE
Skater path is clipped by the ground when the sim is zoomed

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/energy-skate-park#360]
Initially noticed in https://github.com/phetsims/energy-skate-park/issues/354

![image](https://user-images.githubusercontent.com/37052186/208486613-457cce45-8888-4e83-ac2a-fe997f6c1d65.png)

**Comment by jessegreenberg** [comment]
When the skater is resting on the ground, half of the circle will actually be below ground and get clipped. If we dilate the bounds of the CanvasNode drawing the samples, this problem goes away.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, thanks for finding @Nancy-Salpepi and @AgustinVallejo.
