### ISSUE TITLE
Friction and Gravity slider are not quite aligned

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#364]
During QA test https://github.com/phetsims/qa/issues/870, while testing https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html, I observed that the Friction and Gravity sliders are almost but not quite aligned.  Same with the mass slider.  I'm not sure if this is easy to fix or not

<img width="203" alt="image" src="https://user-images.githubusercontent.com/679486/211083529-dace59f2-0585-4b99-85a2-24f40b15cae5.png">

Testing on MacOS 13.0.1 on Chrome 108.0.5359.124.

**Comment by arouinfar** [comment]
Good find @samreid! The alignment looks correct in latest, so the misalignment is a new-ish problem.

Here's latest:
![image](https://user-images.githubusercontent.com/8419308/211099851-76be0063-4742-4aff-9451-2bbcde020f71.png)

@AgustinVallejo this would be good to address for the current release.

**Comment by AgustinVallejo** [comment]
@arouinfar After discussing this with SR, it's likely the alignment was never intended, more like a happy accident, and that fixing this might not be worth the trouble.

I think the x position of the slider depends more on its labels, as you can see 'None' and 'Tiny' are actually aligned...
![image](https://user-images.githubusercontent.com/37052186/211660989-a34dce26-20be-47db-a854-7aa7b1042097.png)

So I'd advice to close the issue. Assigning back to you.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo. I agree, let's close.
