### ISSUE TITLE
Skater sometimes changes direction when coming to rest due to friction

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#365]
During QA test https://github.com/phetsims/qa/issues/870, while testing https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html, I observed that nearly 30% of the time, when a character lands from the track on the ground with friction enabled, they will switch direction.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/679486/211086986-282b158b-70f9-4383-bd46-8125c23571a5.png">

This seems potentially related to https://github.com/phetsims/energy-skate-park/issues/168

We are not sure how important this is to fix.

**Comment by arouinfar** [comment]
Thanks @samreid.

I compared to latest, and the behavior exists there too, but the direction change isn't as frequent. It's definitely more noticeable in the RC. @AgustinVallejo I think this is worth some investigation to better understand the problem.

**Comment by arouinfar** [comment]
I've tested this a bit further and given it some thought, and I don't think we need to investigate.

Getting the skater to flip direction is VERY position dependent. Moving the track to a slightly different place or dropping the skater from a slightly different height will yield different results. After more comparison with the published version, I do not think the behavior has changed all. 

The behavior itself does not post any serious UX or pedagogical issues so I'm going to close as wontfix.
