### ISSUE TITLE
Character headshots extend slightly below gray outline

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#367]
**Test device**
Mac 

**Operating System**
macOS 10.15.7 and 13.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/870, the characters in all character sets extend slightly below the gray border with the dog and cat having the most obvious issue. 
Not seen in the published version. 

**Steps to reproduce**
On any screen, zoom in on the character head shots

**Visuals**
<img width="546" alt="Screenshot 2023-01-09 at 3 20 54 PM" src="https://user-images.githubusercontent.com/87318828/211402078-f8c19b0b-68d1-40dc-8a68-772e655ae6ba.png">

<img width="680" alt="Screenshot 2023-01-09 at 3 24 23 PM" src="https://user-images.githubusercontent.com/87318828/211402098-4aacc0db-ce23-479a-a9b7-4e841356db92.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-rc.1 2022-12-22 16:17:42 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
This is looking so much better. I do notice that some of the characters have a thicker black stroke across the bottom, but it is very minor. @arouinfar thoughts?
<img width="291" alt="Screenshot 2023-01-12 at 5 18 10 PM" src="https://user-images.githubusercontent.com/87318828/212193848-9cc01ef9-ba9d-4bee-a303-d8c61a6d98f2.png">
<img width="364" alt="Screenshot 2023-01-12 at 5 19 46 PM" src="https://user-images.githubusercontent.com/87318828/212193900-9d911c92-db6a-4746-bfa1-007ef2df1a39.png">

**Comment by arouinfar** [comment]
> This is looking so much better. I do notice that some of the characters have a thicker black stroke across the bottom, but it is very minor. @arouinfar thoughts?

Agreed, it's way better in rc.2! I don't notice the black stroke unless I zoom in and actively look for it, so I think we can go ahead and close.
