### ISSUE TITLE
Slight overlap with some touch areas

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#368]
**Test device**
Mac

**Operating System**
10.15.7 + 13.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/870, I see a slight overlap with the touch areas for the Gravity slider and combobox below it on screens 2-4. There is also a slight overlap with the mass slider and characters. This wasn't an issue for me when testing with the iPad. 

Also seen in published. 

**Visuals**
<img width="264" alt="Screenshot 2023-01-09 at 3 47 03 PM" src="https://user-images.githubusercontent.com/87318828/211405807-d22da236-39bf-4b51-8d18-49329cf21bf6.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-rc.1 2022-12-22 16:17:42 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
I believe this should be fixed now, assigning back to you

**Comment by Nancy-Salpepi** [comment]
Looks fixed on master 🙂
I wasn't sure if I should close, so assigning back to you.

**Comment by arouinfar** [comment]
@AgustinVallejo this will need to be cherry-picked into the 1.2 branch.

**Comment by Nancy-Salpepi** [comment]
Looks good in 1.2.0-rc.2. Closing.
