### ISSUE TITLE
May be possible for skater to land on other side of a track

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#371]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/870
This is reproducible in the published version. It also can be a bit luck based when reproducing.
It is possible for a skater to land on the opposite side of the track than it approached from.
**Steps to reproduce**
1. Go to the Playground screen
2. Set up a circular track with a gap at the top as shown in the gif below. The gap should be such that a skater will land inside the circle
3. Set the skater on the outside of the track.
4. The skater should land inside the track when it goes over the gap, but at certain angles it may land on the outside

**Visuals**
![gothrough](https://user-images.githubusercontent.com/41024075/211620788-64c92858-20ea-4565-8938-f1d4d168ba61.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-rc.1 2022-12-22 16:17:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe. I think we should definitely continue to catalog issues like this so we have a paper trail. 

However, this is a somewhat tricky-to-reproduce edge case that is also present in the published version. While it looks a little weird, I don't think the behavior is harmful. @AgustinVallejo I'm going to close this as wontfix.
