### ISSUE TITLE
Inconsistent graph behavior when reference height is moved

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#372]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
For https://github.com/phetsims/qa/issues/870
Also occurs in published.
On the graph screen, in the position scene, the dots of a stationary skater start out making a trail when the reference height is moved (since potential energy and total energy are changing). However, after a few seconds the trail disappears and no new trail is made when the reference height is moved.
**Problem description**
1. Go to the graph screen
2. Turn on reference height and move the height up and down
3. Wait a few seconds
4. Move the height again

**Steps to reproduce**
![inconsis](https://user-images.githubusercontent.com/41024075/211627486-785a6eef-fdda-4d82-9ce3-cd58c89f53ad.gif)

**Visuals**

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-rc.1 2022-12-22 16:17:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

> However, after a few seconds the trail disappears and no new trail is made when the reference height is moved.

The trail will re-appear if you use the graph's erase button.

@AgustinVallejo this behavior is exactly the same as the published version of the simulation. Unless the cause of this behavior is obvious and trivial to address, I'm fine with closing.

**Comment by AgustinVallejo** [comment]
@arouinfar I was thinking we could trigger a graph erase when the reference height is moved, as keeping the moving trace wouldn't be an inertial frame of reference. 

Would you agree on that?

**Comment by arouinfar** [comment]
Sounds reasonable @AgustinVallejo, let's try it.

**Comment by AgustinVallejo** [comment]
Done, ready for review!

**Comment by KatieWoe** [comment]
It looks nice to me after a quick look.

**Comment by arouinfar** [comment]
Looks good @AgustinVallejo

**Comment by KatieWoe** [comment]
Looks good in rc.2
