### ISSUE TITLE
Add Asia, Latin America, and Oceania character sets

### ISSUE THREAD

**Issue by marlitas** [phetsims/energy-skate-park#374]
The Asia and Latin American character sets are ready to be added in. First step will be getting the artwork exported as pngs. Sending over to @amanda-phet.

**Comment by marlitas** [comment]
I received pngs from @amanda-phet. Over to me to drop them in.

**Comment by marlitas** [comment]
I mixed this issue up with https://github.com/phetsims/number-line-integers/issues/110. NLI is ready, not ESP.

**Comment by marlitas** [comment]
We just need some images from @amanda-phet. Once those are uploaded, go ahead and assign to @Luisav1 to add them all in.

**Comment by amanda-phet** [comment]
@Luisav1 all characters are uploaded! Over to you.

**Comment by Luisav1** [comment]
The Asia, Latin America, and Oceania character sets are integrated. @amanda-phet could you review them to make sure it all looks good? Thanks!

**Comment by marlitas** [comment]
@Luisav1 I took a look at the sim and noticed that the Latin America set doesn't have any of the skater headshots you can choose from in the control panel. I haven't had a chance to look into it yet so not sure if it is a larger problem or just something small that got missed.



![Image](https://github.com/phetsims/energy-skate-park/assets/42476338/858659d3-b351-4352-af4a-1c07c22d0d32)

**Comment by Luisav1** [comment]
Sorry! I forgot to add the Latin America controls to the control panel. This should be fixed in the above commit now.

**Comment by marlitas** [comment]
Awesome thanks!

**Comment by amanda-phet** [comment]
I modified some files after reviewing and they are all in now. Over to @Luisav1 to make sure they are in the sim ok.

**Comment by Luisav1** [comment]
The images are all in good! @amanda-phet could you review them to make sure they're looking good? Thanks.

**Comment by amanda-phet** [comment]
They all look good to me! So glad I was able to fix those little things.
