### ISSUE TITLE
Designs in clothing are reflected when character changes direction

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#375]
For https://github.com/phetsims/qa/issues/1006:
This is similar to what I saw in Number Line: Distance. When a character changes direction, clothing details (ex. pocket location) get flipped. Since the characters are moving, I'm not sure how noticeable it would be to users, but thought I would let you know. 

<img width="474" alt="Screenshot 2023-11-29 at 11 16 15 AM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/c6a60fb0-c4dc-4812-a002-d1c0d69996fd">
<img width="474" alt="Screenshot 2023-11-29 at 11 16 46 AM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/8304cde0-532d-4b1d-93cc-3a18c076af66">

The boy in Oceania is also in the Asia character set.

<img width="474" alt="Screenshot 2023-11-29 at 11 18 05 AM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/6b60c021-b2e4-4e5e-8df4-670b2c6904e9">

**Comment by amanda-phet** [comment]
@arouinfar I reflected the images to do the left/right orientations, so I'm wondering how serious this issue is to you. 

I'll look into the character set concern separately.. it's possible I mixed someone up.

**Comment by amanda-phet** [comment]
@Nancy-Salpepi I didn't notice before, but this character does in fact appear in both Asia and Oceania, and I didn't notice at all. It's possible it is intentional, so I reached out to the artwork channel. 
<img width="338" alt="image" src="https://github.com/phetsims/energy-skate-park/assets/7852916/2a840394-d0db-48a1-8f88-6f95f96e0094">

Hopefully @arouinfar has an answer about the reflected clothing. I'm not sure how we'd address that without redrawing people, so my best guess is that we won't address it.

**Comment by amanda-phet** [comment]
I confirmed that the character IS supposed to repeat in Asia and Oceania, so nothing to do there.

**Comment by Nancy-Salpepi** [comment]
@amanda-phet I figured that the character in both sets was intentional. I wrote that in case the artwork was going to be changed. Thank you for confirming though!

**Comment by arouinfar** [comment]
> @arouinfar I reflected the images to do the left/right orientations, so I'm wondering how serious this issue is to you.

That's also the strategy I've used for the skater artwork. In general, I don't think there's an issue with mirroring clothing patterns/features. The only exception I recall is for characters with a prosthetic leg, where we instead created specific left/right artwork.

**Comment by Nancy-Salpepi** [comment]
OK. So we can close this then.

**Comment by Nancy-Salpepi** [comment]
Sorry--reopening this for https://github.com/phetsims/qa/issues/1012.
@arouinfar commented: 
>That's also the strategy I've used for the skater artwork. In general, I don't think there's an issue with mirroring clothing patterns/features. The only exception I recall is for characters with a prosthetic leg, where we instead created specific left/right artwork.

I didn't realize there were 2 characters with a prosthetic leg in this sim. 
The one that appears in the Africa character set has the correct artwork:
<img width="291" alt="Screenshot 2023-12-13 at 10 20 37 AM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/12bfc25f-4d4d-4be3-b36b-c35fedcc1fd5">

But the one that appears in the US character set doesn't:
<img width="291" alt="Screenshot 2023-12-13 at 10 21 14 AM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/799fb552-b289-43f8-a9dc-96cee70d4d38">

**Comment by Nancy-Salpepi** [comment]
Also, I was wondering if it is OK that we are using the same character with a prosthetic leg in the Africa character set and without the prosthetic leg in the US character set? 
<img width="297" alt="Screenshot 2023-12-13 at 3 58 15 PM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/e727fe04-c526-4f6b-a087-11b99caeb5f7">
<img width="297" alt="Screenshot 2023-12-13 at 3 58 39 PM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/4d5dd3bf-edff-4b83-9298-b2883c678e81">

**Comment by amanda-phet** [comment]
That's my mistake, I will redo the American guy. 

While I'm in here I can also move the pocket on that one boy and a few other types of clothing that shouldn't be reflected.

**Comment by amanda-phet** [comment]
OK I just updated 4 artwork files. 

I think it would also make sense to delete oceania/skater5 and just use asia/skater3 in that spot, since they are essentially the same and I don't want a duplicate artwork file to maintain.

**Comment by Luisav1** [comment]
All the artwork is now integrated.

I renamed Asia's skater3 for skater5 since there was an issue with having two skater3's in Oceania (Oceania's and Asia's files). Now the previously duplicate files are all referencing asia/skater5 and the previous asia/skater5 is now called asia/skater3.

Assigning back to @amanda-phet to review.

**Comment by amanda-phet** [comment]
OK I think the rearrangement is fine. The artwork all looks good to me. @Nancy-Salpepi do you want to confirm as well?

**Comment by Nancy-Salpepi** [comment]
I don't know exactly which files you changed (not sure how to figure that out), but I'm guessing it is these and all looks good:
-The pocket looks good on the boy in the Africa/Africa modest character sets
-The design on the shirt looks good for the boy in the Asia/Oceania character sets
-The prosthetic leg has been fixed for the American guy.

**Comment by amanda-phet** [comment]
Yup! There was also a girl in the Latin America set. Thanks Nancy!

**Comment by Nancy-Salpepi** [comment]
She looks good too! Thanks Amanda!

**Comment by marlitas** [comment]
Looks like this is ready to cherry pick. Marking as such.

**Comment by Luisav1** [comment]
Reopening for RC spot check.

**Comment by Nancy-Salpepi** [comment]
Characters look good in rc.2!
