### ISSUE TITLE
dialog text wraps prematurely with ?stringTest=double

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#376]
For https://github.com/phetsims/qa/issues/1012
@marlitas @Luisav1 should this fix https://github.com/phetsims/scenery/issues/1588 have been added to ESP? 

<img width="1062" alt="Screenshot 2023-12-13 at 9 40 49 AM" src="https://github.com/phetsims/qa/assets/87318828/afdcfca5-286e-4a28-9329-c66d9f72b3cb">

**Comment by marlitas** [comment]
Yes. looks like that should get cherry-picked in. @Luisav1 let's check in on if you want to do that, or would like me to.

**Comment by Luisav1** [comment]
@marlitas and I updated the dependencies in 1.3 to include this change. This is how it looks like now.
![image](https://github.com/phetsims/energy-skate-park/assets/52978048/2382e54e-3d92-4711-9d16-73a7196f4009)

Leaving this open to review in the RC spot check.

**Comment by Nancy-Salpepi** [comment]
The Localization tab looks good, but now the Simulation tab looks odd:

rc. 2: 
<img width="611" alt="Screenshot 2024-01-04 at 12 41 34 PM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/dd5d15cf-cb9c-45d8-abea-d634a3c47ade">


rc. 1:
<img width="611" alt="Screenshot 2024-01-04 at 12 41 08 PM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/31da4dcc-86d1-4ff4-a250-096af5b74fee">

**Comment by Nancy-Salpepi** [comment]
this is what it looks like normally now (without stringTest):
<img width="637" alt="Screenshot 2024-01-04 at 1 00 42 PM" src="https://github.com/phetsims/energy-skate-park/assets/87318828/18e37972-0f5b-4c2f-b1c2-b4bb9898233d">

**Comment by marlitas** [comment]
Interesting. I'll check that.

**Comment by marlitas** [comment]
Different options needed to be defined for those labels. That has been done in the above commits and will need to be cherry-picked.

**Comment by Luisav1** [comment]
The above option changes commits have been cherry-picked in. Leaving this open to double check in the next RC. Feel free to close if it all looks good, thanks!

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.3
Closing!
