### ISSUE TITLE
Bad tandem name 'jupiterItemItem'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#381]
Discovered while working on 

In GravityComboBox.js, 'jupiterItemItem' should be 'jupiterItem':

```ts
      { label: gravityJupiterString, value: EnergySkateParkConstants.JUPITER_GRAVITY, tandemName: 'jupiterItemItem' }
```

I did not touch this because it will be a PhET-iO API change.

**Comment by jessegreenberg** [comment]
Thanks, I fixed the name. energy-skate-park isn't in phet-io-api-stable.md and pre commit hooks are passing so I assume its safe to change.
