### ISSUE TITLE
Convert to new Region and Culture approach

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#382]
For https://github.com/phetsims/joist/issues/958.

**Comment by pixelzoom** [comment]
Conversion is done.    @Luisav1 would you like to have a look?  The main commit is https://github.com/phetsims/energy-skate-park/commit/8f35ffb81e7832d86f33f23d466f623cf556b7a2.    Close if OK, let me know if you have any questions.

**Comment by Luisav1** [comment]
I've reviewed the main commit (8f35ffb) (and the other commits above too) and everything looks good to me as well. No questions from my end. Closing. Thanks!
