### ISSUE TITLE
User suggestion: Hide labels in graphs

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#4]
Unfuddle Ticket [#3600](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3600).

> I teach using Modeling Instruction, and I've used the Energy Skate Park as an introduction to the concept of energy. It's remarkably effective and tangible, but I've found that the terminology in the simulation often stands in the way of students internalizing what we mean when we talk about energy. Students have many ideas about "kinetic" "potential" and "thermal" energy coming into my course, and there's a tendency to treat the the simulation work as confirmation of these ideas, rather than a chance to explore new ones.
I've undertaken the project of creating a version of the skatepark that doesn't use any energy terminology at all - so students can develop an understanding about what factors affect "the blue bar" or "the red bar". This seems like a relatively straightforward modification using the Java code, but since you're creating an html5 version of this simulation, I thought I'd reach out to see if this might become an officially sanctioned "feature". Perhaps whether two versions of the simulation could be available for use - one with terminology and one without?
I'm including a link to a few blog posts I've written on using the Skate Park to build and test energy ideas, to help clarify how I'm using the sim.
http://observationsfirst180.wordpress.com/2013/10/02/phet-______-skate-park/
http://observationsfirst180.wordpress.com/2013/10/11/measuring-bar-lengths/
http://observationsfirst180.wordpress.com/2013/10/04/phet-skater-jet-pack/
Thanks again so very much for your excellent work!

Another user commented on the [PhET “______” Skate Park" blog post](https://observationsfirst180.wordpress.com/2013/10/02/phet-______-skate-park/)
> Funny that you bring up getting rid of the names for the forms of energy storage in the Energy Skate Park Sim- We used the Skate Park recently in class and I was thinking along the same lines. I think having them infer the meaning of the various bars would help attack some misconceptions that they otherwise hang on to (despite the evidence) because of the name.
One big misconception a lot of my freshmen bring with them is that gravitational energy only exists when an object is falling- not having the name ahead of time might help them to better describe “what that green bar means” before letting the term “gravitational” direct their thinking.

In the comments on the Unfuddle issue, I see:
> Discussed at status meeting 2/27/2014. We will certainly think about this for the HTML5 version. Maybe hide labels button – we are going to punt on this until Q4 when looking at translation utility and Moore Grant. Wrote back to user 2/28.

The users bring up some interesting points, so it might be worth having a discussion about this at design meeting.

**Comment by jessegreenberg** [comment]
@arouinfar can you please comment on the state of this issue? Anything else to do?

**Comment by arouinfar** [comment]
@jessegreenberg this really isn't a primary learning goal of ESP, and this isn't something we would need to support in the phet-brand sim. There are low-tech ways that teachers could hide these labels in the the sim, such as obscuring the pie chart legend with a post-it note. It's already possible to hide the legend in phet-io, so I'm going to go ahead and close this issue.
