### ISSUE TITLE
Performance degradation from bar graph changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#40]
From #39 and #25, I have noticed that changes to the bar graph have caused the sim to slow down quite a bit on my Windows 10 Laptop in Chrome.

If I remove this line from BarGraphForegroundNode, the sim runs much faster again
```js
      bar.children = [ solidBar, imageNode ];
```

**Comment by jessegreenberg** [comment]
The imageNode above is the label for the bar rasterized to be added for webgl. If I remove this and the stroke around the bars, performance improves quite a bit. So these two changes to these nodes using WebGL are degrading performance quite a bit.

**Comment by jessegreenberg** [comment]
I would like to understand why these changes reduced performance, but I also don't want to spend time on this until we verify that it is important for the bars to have a stroke. If the bars don't need a stroke, we can move the labels back to the background (svg layer) for improved performance.

**Comment by jessegreenberg** [comment]
I noticed that performance improves greatly when the sim view is small, further indicating a webgl issue.

**Comment by samreid** [comment]
I suspect that WebGL doesn't yet support drawing stroked rectangles.  Hence when the `solidBar` which has a stroke is added, scenery splits the view up from a single WebGL layer to:

WebGL pre-layer
SVG layer for rendering the stroked rectangle
WebGL post layer

This would allocate twice as many canvases and be a significant performance cost, as well as the additional cost of rendering to them and compositing them.  One way out may be to emulate a stroked rectangle by making a solid rectangle that has the right dimensions, then drawing the fill over it.  Another way out would be to eliminate WebGL altogether for this sim, I'll create another issue to discuss that.

**Comment by jessegreenberg** [comment]
Thanks for explaining @samreid, now I understand. Adding a rectangle behind the bar seems simple enough I will go ahead and try that regardless of #42.

**Comment by jessegreenberg** [comment]
I replaced the stroke with a background rectangle, and this helped with the stroke. But the sim was still much slower on my laptop until I removed the imageNode with the bar label. These children are slow:
```js
      bar.children = [ strokeRectangle, solidBar, imageNode ];
```

These children are fast:
```js
      bar.children = [ strokeRectangle, solidBar ];
```

Probably for similar reasons as https://github.com/phetsims/energy-skate-park/issues/40#issuecomment-443758160

**Comment by jessegreenberg** [comment]
When generating the image node, I realized I wasn't using `useCanvas` in `rasterized`. Also reducing the resolution from 8 to 1 also greatly improved performance. But the text looks blurry.

```js
      var imageNode = labelRectangle.rasterized( { resolution: 1, wrap: false, useCanvas: true } );
```

**Comment by jessegreenberg** [comment]
I tried scaling up the text manually, then scaling down the imageNode to get better quality, but I am seeing identical performance behavior to using higher value for `resolution`.

**Comment by jessegreenberg** [comment]
A different way to emulate the stroke is to use four surrounding rectangles around each bar, and this seems to perform pretty well on my slower laptop. This way, we can move the label back to the BarGraphBackground and not have to use a rasterized image of the label text.

So we will have the label in the background, then in the foreground we will have a solid rectangle for the bar, a semi-transparent rectangle for the bar over the portion covering the label, then 4 rectangles surrounding the bar emulating a stroke.

**Comment by jessegreenberg** [comment]
I went with the above approach and it is working much faster on my slower laptop. I feel comfortable closing this issue.
