### ISSUE TITLE
Scale of bar graph with small mass

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#46]
In https://github.com/phetsims/energy-skate-park-basics/issues/447 @KatieWoe pointed out the case where mass is very small while thermal and total energies are very high. In this case, there can be substantial movement, but even if the graph is zoomed in all the way, we can't see any kinetic or potential energies because the mass is so small. This was fixed in ESP:B by reverting to the mass range intended in that sim.

@arouinfar is this OK in ESP? Is it actually a good thing for students to think about why the energies are so small that they are not visible in this case? Or do we need to change some things to make sure that the bars are visible when there is movement?

![](https://user-images.githubusercontent.com/41024075/49758248-bb65fb80-fc7b-11e8-9fd2-d2eb3acc13ee.gif)

**Comment by arouinfar** [comment]
@jessegreenberg what is the value of the "Small" mass?  

In master, the 5 kg mass seems reasonable, but the Bar Graph isn't particularly useful for the 0.2 kg mass. We may consider either adding an additional zoom level to the graph, or making 5 kg the smallest possible mass (which is currently the minimum on screens 2-4).

**Comment by jessegreenberg** [comment]
Right now the mass slider spans the same range as the "Intro" screen, so "small" is 0.2 kg.

**Comment by arouinfar** [comment]
@jessegreenberg can you add one additional level of zoom in?

**Comment by jessegreenberg** [comment]
I added another zoom level @arouinfar. When mass is tiny I can see the kinetic bar now. But when mass and gravity are tiny we have a similar issue again.

**Comment by arouinfar** [comment]
@jessegreenberg I think the scaling looks good on master. When mass is 5 kg and gravity is tiny, the bars are small, but I can still see the trade-off between KE and PE which is good enough. Is the scaling ideal for the smallest possible values? Perhaps not, but it's somewhat unrealistic to expect optimal scaling for all possible values without adding tons of zoom steps.
