### ISSUE TITLE
Add text readout to gauge node

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#47]
I began to add a text readout to the gauge node for the Measure screen and realized that the same layout was requested in FAMB so I started https://github.com/phetsims/scenery-phet/issues/440.

In that issue @samreid said

>We do not have WebGL support for text rendering. The WebGL optimization for ESPB was that all animating components could be done in a single WebGL layer. If we introduce numbers which are changing every frame, it will impact the performance characteristics significantly.

So it seems our options are:
- Add text that changes every frame and test how poorly performance behaves.
- Not include the number display in ESP. Unsure how critical it is.
- Add support for rendering text in WebGL. I am not sure what this would cost.
- Stop using WebGL in this sim, see #42 

@samreid do you see any other path? Does option 1 seem worthwhile?

**Comment by samreid** [comment]
That seems like a complete set of options.  I suspect the right order of investigation would be 1, 4, 3, 2.

**Comment by jessegreenberg** [comment]
OK, thanks, assigning to me. Ill start with 1 and see how it goes. Lets cross our fingers!

**Comment by jessegreenberg** [comment]
On my iPad2 animation is noticeably faster without the change.

**Comment by jessegreenberg** [comment]
This test included the Text added from GaugeNode's new NumberDisplay, and to get it working also included animation for the default needle.

Its a very long shot but I will try text animation without the needle animation.

**Comment by jessegreenberg** [comment]
I tried with a custom NumberDisplay, without animating the the GaugeNode needle and still saw a big performance hit.

In the test I accidentally tried with 0 decimal places for the NumberDisplay and saw performance improve quite a lot because the text wasn't updating as much. So this really indicates that the rapidly changing text is causing the performance hit on iPad2.

**Comment by jessegreenberg** [comment]
This will depend on https://github.com/phetsims/energy-skate-park/issues/42, on hold until that is resolved.

**Comment by jessegreenberg** [comment]
#42 has been addressed and since the sim no longer has custom WebGL requirements ValueGaugeNode can be used.

**Comment by jessegreenberg** [comment]
ValueGaugeNode is now being used, the NumberDisplay is only visible on the Measure screen.
