### ISSUE TITLE
User suggestion: Precise time readout in Energy vs. Time graph

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#5]
In Unfuddle Ticket [#625](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/625), Trish reported
> I am writing my 4th activitiy in a series that uses Skate Park. The learning goals for the activity are as follows. Students will be able to: Calculate speed or height at a different time. Determine energy distribution relative to time. Interpret information about motion from Energy-Time Graphs  
I can't really get the time in precise enough increments for the students to answer the first goal in a variety of situations. I think this is a common learning goal and we should consider how to enable it. I think the most obvious place is on the Energy-Time graph (or the purple dots, but I like the graph better). Two things make getting the time right now difficult: if you move the vertical bar to see the time or energy the purple dot is not available and the vertical bar is wide enough to make one wonder what time is being represented by the guys red dot.

This is the activity Trish was referring to:
https://phet.colorado.edu/en/contributions/view/3134

I reviewed the above activity, but I'm not entirely sure how a precise time readout would improve/change the activity. However, it's true that time can only be estimated from the graph. 
![image](https://user-images.githubusercontent.com/8419308/30503450-7b44ee6a-9a27-11e7-8487-48c117a7aee4.png)

When discussing an Energy vs. Time graph, we should consider whether or not a time readout would be a useful feature.

**Comment by jessegreenberg** [comment]
We do have a timer in this sim now. But @arouinfar can you comment if there is anything else to do for this?

**Comment by arouinfar** [comment]
I do not think a precise time readout is within the scope of the goals for the E vs. t graph. We also now have a StopwatchNode to measure the time precisely, so I think we can go ahead and close.
