### ISSUE TITLE
non-standard energy colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#51]
From https://github.com/phetsims/scenery-phet/issues/455#issuecomment-452506314:

PhetColorScheme:

```
var RED_COLORBLIND = new Color( 255, 85, 0 );
var TAN_ORANGE = new Color( 236, 153, 55 );

HEAT_THERMAL_ENERGY: RED_COLORBLIND,
...
KINETIC_ENERGY: Color.GREEN,  // 0,255,0
...
POTENTIAL_ENERGY: Color.BLUE, // 0,0,255
...
TOTAL_ENERGY: TAN_ORANGE,
```

EnergySkateParkColorScheme:

```js
    kineticEnergy: new Color( '#00cc1a' ),
    potentialEnergy: new Color( '#3282D7' ),
    thermalEnergy: new Color( '#FF5500' ), // red colorblind
    totalEnergy: new Color( '#B4B400' ), // dirty yellow
```

@arouinfar is there any reason why EnergySkateParkColorScheme should not be using PhetColorScheme?

**Comment by arouinfar** [comment]
Thanks @pixelzoom. All PhET sims should use the same colors for the various energies, but `PhetColorScheme` is a bit antiquated. Changes to `PhetColorScheme` will be discussed in https://github.com/phetsims/scenery-phet/issues/456, so marking this as `status:on-hold` until that issue is resolved.

**Comment by arouinfar** [comment]
@jessegreenberg, in phetsims/scenery-phet#455 the colors used for energy were updated in PhetColorScheme.js. ESP should be using PhetColorScheme for the energy colors in EnergySkateParkColorScheme. I'd imagine that ESPB uses the same color scheme, but to be clear, the change should apply to both sims.

**Comment by jessegreenberg** [comment]
Alright, this sim (and therefore basics version) is using PhetColorScheme for the energies. Colors before (published version):
![before](https://user-images.githubusercontent.com/6396244/51266600-b2a6ca80-1989-11e9-8bf8-50895179e25d.PNG)

Colors after (master):
![after](https://user-images.githubusercontent.com/6396244/51266607-b76b7e80-1989-11e9-86f6-d92fd3a75887.PNG)

Closing.
