### ISSUE TITLE
Pie chart wrong color when thermal is only energy

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#52]
For https://github.com/phetsims/QA/issues/226.  @samreid noted that when webgl is false, this issue does not appear.  If thermal energy is the only energy present, then the pie chart looks as if there is negative PE.  This means the chart has a dashed border and is the color of total energy.  To see this, go to the Playground screen, turn on the graphs, and drop the skater to the ground from some height.  When she hits the ground the thermal energy will be all that is left.  Also happens in ESPB.

?webgl=false:
![image](https://user-images.githubusercontent.com/41024075/50915032-29295280-13f5-11e9-8425-0cbee000c5aa.png)
?webgl=true:
![image 1](https://user-images.githubusercontent.com/41024075/50915039-2dee0680-13f5-11e9-9a91-33cdfd4a8b2b.png)

**Comment by jessegreenberg** [comment]
This was specific to this sim after changes for representing negative energies with the pie chart. Not a general WebGL bug. Fixed in the above commit.
