### ISSUE TITLE
"Cannot read property 'createAnotherDiv' of undefined" in Wrapper Unit Tests

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#53]
Discovered in #50, the error is "Cannot read property 'createAnotherDiv' of undefined".  Not sure what is causing it.  Same problem is not occurring in Faraday's Law Wrapper Unit Tests.

**Comment by samreid** [comment]
Two problems of the same type are coming from LinkedElementIO

**Comment by samreid** [comment]
Proposed fixes are here, @jessegreenberg can you please review and close if all is well?

**Comment by samreid** [comment]
Also, after the fixes here and in #50, the ESPB "Wrapper Unit Tests" with `?phetioValidateTandems` is passing, and should be a good point for testing for future development.  Thanks!

**Comment by jessegreenberg** [comment]
I reviewed and ran the unit tests on my end, and will continue to do so. Thanks @samreid!
