### ISSUE TITLE
Use NumberDisplay for the skater path sensor

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#56]
I was changing the skater path sensor to use NumberDisplay, but noticed that with NumberDisplay (as it currently is), it will look different than the mockups when the sensor is not over a sample point.

Here is the mockup:
![image](https://user-images.githubusercontent.com/6396244/51777708-38362300-20cc-11e9-808e-12f4b84bce4a.png)

And here is what it will look like with NumberDisplay:
![image](https://user-images.githubusercontent.com/6396244/51777734-54d25b00-20cc-11e9-9aa4-a16d71a5715f.png)

(sorry, ignore the differences in color for now).

When the values are aligned to the right, NumberDisplay also aligns "null" value to the right. And NumberDisplay includes the units with "null" readout too.

@arouinfar is the bottom look OK? If not, we should make an issue to change NumberDisplay when displaying "null" values.

EDIT: Or we would not use NumberDisplay here, but that is not ideal.

**Comment by arouinfar** [comment]
@jessegreenberg it seems a bit weird that the null value includes units. I don't remember this being the case when I reviewed the work @pixelzoom did in https://github.com/phetsims/scenery-phet/issues/431#issuecomment-454964250.

Here are a few examples of NumberDisplays which do not show the units when the value is null.

Concentration Meter in beers-law-lab:
<img src="https://user-images.githubusercontent.com/8419308/51778319-4ed57d80-20be-11e9-975b-93896f17e2b4.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/51778311-42512500-20be-11e9-907c-f67295ef5a50.png" width=150>

Pressure Meter in under-pressure:
<img src="https://user-images.githubusercontent.com/8419308/51778347-6ca2e280-20be-11e9-9133-7796a4bf0b21.png" width=300>

**Comment by jessegreenberg** [comment]
It looks like those examples are using MathSymbols.NO_VALUE but not NumberDisplay.

**Comment by jessegreenberg** [comment]
Units are included for cases like https://github.com/phetsims/scenery-phet/issues/431#issuecomment-439565309

**Comment by jessegreenberg** [comment]
And same case explains why "no value" aligns with the value.

**Comment by arouinfar** [comment]
Thanks for the clarification @jessegreenberg. The example in https://github.com/phetsims/scenery-phet/issues/431#issuecomment-439565309 is a somewhat different context. There, the user is choosing between different units in the ComboBox (ComboDisplay?). 

I'm not sure what the advantage of using NumberDisplay would be here. It looks like other similar tools aren't using NumberDisplay. If these sorts of tools would be better off with NumberDisplay, then I think there should be a way to center the emdash in the field without displaying the units.

**Comment by jessegreenberg** [comment]
I was just trying to use a common code component rather than re-implement the Rectangle + Text + layout code + use of MathSymbols.NO_VALUE. Most examples in https://github.com/phetsims/scenery-phet/issues/431#issue-380914464 have the dash centered with no units, so I am wondering if this should actually be the default for no value.

**Comment by jessegreenberg** [comment]
Options were added to NumberDisplay so that different units and alignment can be used  when there is no value. Since it matches the mockup now this can be closed.
