### ISSUE TITLE
How to structure code for Energy Skate Park and Energy Skate Park: Basics

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#6]
@jessegreenberg and I discussed the following possibilities for how to structure repos:

(1) one main repo which has everything
 thin shell for "basics"

(2) one repo for basics
 then the "non-basics" adds whatever it needs to add above and beyond basics

(3) one common code repo that has what's common between basics and non-basics
 then basics adds what it needs
 non-basics adds what it needs

We may be able to get by with (2) because the full version is mainly adding features.  However, we want to be able to support the case where "basics" and "full" versions diverge, so this suggests we should go with (3) and have a full common code repo.

Since the existing energy-skate-park-basics code will become the new "common" code, we would like to transfer it keeping its full history, and issues.  We considered renaming the energy-skate-park-basics repo to energy-skate-park-common, then creating a new "energy-skate-park-basics" repo.  Another possibility would be to create a new energy-skate-park-common repo and initialize it with the full git history of energy-skate-park-basics, but this would not transfer the issues.

Maybe we should ask @ariel-phet and @arouinfar whether the issues from energy-skate-park-basics should transfer to energy-skate-park-common?

Also, we wanted to note that a hurdle we will face with any of these strategies (perhaps moreso with (3)) will be moving files between repos. Say a feature is developed for "full" and we want to make that feature available in "basics", then moving files to "common" should be done with keeping history (which is not easy to do).

**Comment by samreid** [comment]
Another possibility for creating the "common" repo from the "basics" repo--we could create it as a fork, this would keep all shas and code, but would not move issues.

**Comment by samreid** [comment]
@jonathanolson what do you think of the strategy of renaming the "basics" repo to "common" then immediately creating a new "basics" repo (which then depends on common)

@ariel-phet is it OK with you if we transfer 100% of the issues (open and closed) from "energy-skate-park-basics" to "energy-skate-park-common"?

@arouinfar and @ariel-phet how much will the "basics" code differ from what is provided in common code?  Will it mainly be leveraging common code (but with PE height = 0, constant gravity, etc)?

**Comment by samreid** [comment]
@jessegreenberg pointed out this possibility for cloning a repo using `--mirror`

https://help.github.com/articles/duplicating-a-repository/

**Comment by arouinfar** [comment]
> @arouinfar and @ariel-phet how much will the "basics" code differ from what is provided in common code? Will it mainly be leveraging common code (but with PE height = 0, constant gravity, etc)?

@samreid @jessegreenberg I think ESPB would largely leverage common code, with PE=0 always at ground level and constant g.

**Comment by jonathanolson** [comment]
> @jonathanolson what do you think of the strategy of renaming the "basics" repo to "common" then immediately creating a new "basics" repo (which then depends on common) either as a fork of common or initialized from its git history (so we can still do legacy builds).

Renaming a published sim repo sounds generally unacceptable. (3) sounds fine to me.

**Comment by samreid** [comment]
Raising for developer meeting to decide what's best (regarding issues and code).

**Comment by jessegreenberg** [comment]
> what do you think of the strategy of renaming the "basics" repo to "common" then immediately creating a new "basics" repo (which then depends on common) either as a fork of common or initialized from its git history (so we can still do legacy builds).

The  primary reason we wanted to rename the repo was to keep git history for these files. If we manually move files to a common repo, we will lose git history.

What if we change the order of this operation to
- Create a duplicate repository of energy-skate-park-basics called energy-skate-park-common.
- Make energy-skate-park-basics  depend on energy-skate-park-common, and remove files from energy-skate-park-basics as necessary.

Woudln't this this would allow us to keep git history without renaming a repo.

**Comment by jessegreenberg** [comment]
I forgot, another reason to rename the repo was to avoid having to  move 410 issues from energy-skate-park-basics to energy-skate-park-common. That is impossible with https://github.com/phetsims/energy-skate-park/issues/6#issuecomment-371556858.

**Comment by jessegreenberg** [comment]
@mattpen I think you have used the github API - is it possible to use that to move issues?

**Comment by mattpen** [comment]
Here is the documentation on the issues API https://developer.github.com/v3/issues/  

I have not previously worked with this, I've only used the Labels and Repos APIs.  It does not look like there is an easy way to just change the repo parameter for issues, but you can create new issues and add  comments, assignees, labels, etc.  I imagine it is possible to write a script to copy the content of all the issues over.  

I don't think this is a problem unique to us, take a look at https://github.com/holman/ama/issues/413 and https://github.com/IQAndreas/github-issues-import.

**Comment by jonathanolson** [comment]
> I forgot, another reason to rename the repo was to avoid having to move 410 issues from energy-skate-park-basics to energy-skate-park-common

But most links would use the old sim name (particularly in commit names). Are you talking about having to rename/rewrite commit names/descriptions that reference issues to point to a new repo?

**Comment by jessegreenberg** [comment]
@jonathanolson suggested that we actually **don't** want to move all issues because any links or reference to energy-skate-park-basics would be broken after the move.

We will proceed with https://github.com/phetsims/energy-skate-park/issues/6#issuecomment-371556858, and just move any issues we want in energy-skate-park-common manually.

**Comment by jessegreenberg** [comment]
Regarding the discussion of how to structure the common repo, other developers were recommending that we proceed with  option 1 in https://github.com/phetsims/energy-skate-park/issues/6#issue-303190549 because this is what has been done for other sims that have this relationship.

@ariel-phet said that we should keep thinking about it, but that energy-skate-park will not be getting any larger new features, so a "basics shell" could work well for this case.

**Comment by jessegreenberg** [comment]
Based on the 3/8/18 dev meeting,  we agree that we will use option 1 in the original  issue comment

>(1) one main repo which has everything
thin shell for "basics"

**Comment by jessegreenberg** [comment]
So the modified steps from https://github.com/phetsims/energy-skate-park/issues/6#issuecomment-371556858 will be

- Create a duplicate repo of "energy-skate-park-basics" called "energy-skate-park" (This repo!)
- Make energy-skate-park-basics dependent on energy-skate-park, and remove files from energy-skate-park-basics as necessary.

**Comment by jessegreenberg** [comment]
How will we duplicate repo and history of energy-skate-park-basics into energy-skate-park when energy-skate-park already exists? Can I delete this repo and create a new one? energy-skate-park now only has design issues and a license.

**Comment by jonathanolson** [comment]
> How will we duplicate repo and history of energy-skate-park-basics into energy-skate-park when energy-skate-park already exists?

I know it's possible to start from the clone (https://git-scm.com/docs/git-clone), and check this in as the initial setup for `energy-skate-park`. Not sure how to handle it now.

**Comment by samreid** [comment]
Perhaps make a manual copy of energy-skate-park issues, then use this strategy for pushing energy-skate-park-basics to it?  (I suspect we will need to delete it but I'm not 100% sure).

https://stackoverflow.com/questions/5181845/git-push-existing-repo-to-a-new-and-different-remote-repo-server

**Comment by jessegreenberg** [comment]
I went through the steps in https://help.github.com/articles/duplicating-a-repository/, and it seems that everything from energy-skate-park-basics was copied over to energy-skate-park correctly. No need to delete repo and all issues are intact! Looking at git log in energy-skate-park, I see all the same commits in energy-skate-park-basics with the same SHAs.

**Comment by jessegreenberg** [comment]
Location of remote look correct, comments in https://stackoverflow.com/questions/5181845/git-push-existing-repo-to-a-new-and-different-remote-repo-server made me worried --mirror might continue to point to energy-skate-park-basics.
![capture](https://user-images.githubusercontent.com/6396244/39549314-a0c3d898-4e1a-11e8-9a76-6c0ce48f2c46.PNG)

**Comment by jessegreenberg** [comment]
Renaming js/energy-skate-park-basics to js/energy-skate-park blew away history. So for reference in case we need to go searching, code of energy-skate-park will be identical to energy-skate-park-basics on **5/2/2018**.

**Comment by jessegreenberg** [comment]
We should probably document this somewhere or in many places. At least in doc/implementation-notes?

**Comment by jessegreenberg** [comment]
@samreid helped identify that history wasn't lost, but it is not as easy to find. We can still check out old SHAs and use Github UI to "Browse the repository at this point in the history" - but we cannot browse commits with our editors or use `git log` to  see history/commits on the files.

**Comment by jessegreenberg** [comment]
While looking into an unrelated issue I found `git log --follow ./path/to/file`, which shows all of the log information after the `git mv`! Nice!

**Comment by jessegreenberg** [comment]
The last step for this issue will be to turn energy-skate-park-basics into a "shell", but we will  do that once https://github.com/phetsims/energy-skate-park-basics/issues/411 is complete.

**Comment by samreid** [comment]
Now that @kathy-phet has called for putting https://github.com/phetsims/energy-skate-park-basics/issues/411 on hold, I'm wondering if we should take the time now to unify the codebases?  @jessegreenberg what do you think?

**Comment by jessegreenberg** [comment]
I think that sounds like a great idea! This should be the next thing I work on in this repo.

**Comment by samreid** [comment]
@jessegreenberg and I began working on this, and were unsure whether we wanted to keep the layout and look of Energy Skate Park: Basics exactly as it is now, or whether it should share user interface components and other similarities with Energy Skate Park.  We called @arouinfar and discussed it, and the conclusion was that it would be nice to share as much code as possible, for uniformity and consistency of the user interfaces as well as simplicity in development and maintainability.  Regarding particular components such as the scene selection buttons--they are vertically stacked and larger in Energy Skate Park: basics vs horizontally stacked and smaller in Energy Skate Park, but @arouinfar recommended that we should use the horizontal stacked/smaller in Energy Skate Park for consistency (but without the loop).

So the bottom line is: we may have deviations between the look and feel and implementation, but that will be the exception rather than the rule.

**Comment by jessegreenberg** [comment]
Alright, this is done. Almost everything has been removed from energy-skate-park-basics. All that remains in basics are screenshots in assets, basics specific constants, and a directory for each screen that has subtypes of model/view components in this repo.

@samreid is there anything else to do for this issue? Are we ready to close this?

**Comment by samreid** [comment]
Looks great @jessegreenberg, thanks!  I also made a number of minor commits above.  Reassigning to you to review & double check the changes (should be quick).  Close if all is well.

**Comment by jessegreenberg** [comment]
Reviewed above commits, thanks @samreid! Closing.
