### ISSUE TITLE
`NumberDisplay.DEFAULT_VALUE_PATTERN` is no longer defined

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#63]
From https://github.com/phetsims/sun/issues/474.  SkaterPathSensorNode contains this code:

```js
        // when there is no value, show now units
        noValuePattern: NumberDisplay.DEFAULT_VALUE_PATTERN,
```

But after work in https://github.com/phetsims/sun/issues/474, `NumberDisplay.DEFAULT_VALUE_PATTERN` is no longer defined.  @jessegreenberg can you please investigate?

**Comment by jessegreenberg** [comment]
Replaced with SunConstants.VALUE_NAMED_PLACEHOLDER, thanks!
