### ISSUE TITLE
use GaugeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#64]
Related to https://github.com/phetsims/energy-skate-park/issues/47.

Is there any reason why this sim isn't using `SCENERY_PHET/GaugeNode`?

**Comment by jessegreenberg** [comment]
In #47 we are going to use ValueGaugeNode for the gauge node with text. The GaugeNode in this sim had a custom needle that was rendered with WebGL for performance. Custom WebGL code was removed in #66.
