### ISSUE TITLE
branch: dynamic-state

### ISSUE THREAD

**Issue by zepumph** [phetsims/energy-skate-park#65]
for work being done in, https://github.com/phetsims/phet-io/issues/1442

**Comment by zepumph** [comment]
Tagging @jessegreenberg. FYI. We have these changes that are largely investigation at this point on the branch. That said once a pattern is more developed, we will be interested in committing to master.

**Comment by jessegreenberg** [comment]
@zepumph as we are approaching a code revew for this sim, can you please comment on the status of this branch?

**Comment by zepumph** [comment]
I would say we should ditch these. I forgot this existed. @samreid do you agree?

**Comment by samreid** [comment]
Yes, this branch should be deleted, thanks!

**Comment by jessegreenberg** [comment]
Great, thanks! Deleting.

**Comment by jessegreenberg** [comment]
Deleted.
