### ISSUE TITLE
Remove custom WebGL code from this sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#66]
#42 is an investigation about whether we can safely remove WebGL from ESP and keep good performance on PhET's targeted platforms. Should we see a 👍 there (which is likely), these are the immediate things that should be done (with recommendations from @samreid over slack):

- [x] Delete CircularOutlineWebGLNode
- [x] Delete PieChartWebGLNode (edited)
- [x] Remove `renderer` args from SkaterNode BarGraphForeground and others. 
- [x]  Remove custom GaugeNeedleNode solution for gauge animation in the WebGL layer
- [x] Redo some of the layering code?
  - [x] Revisit https://github.com/phetsims/energy-skate-park-basics/issues/425, https://github.com/phetsims/energy-skate-park-basics/issues/295
  - [x] Remove layering functions addToBottomLayer addToTopLayer.
  - [x] Remove bottomLayer, webGLLayer, and topLayer nodes.
- [x] Combine BarGraphForeground and BarGraphBackground into a single node? (edited) 
- [x] Use griddle for the bar graph, see https://github.com/phetsims/energy-skate-park/issues/31
- [x] ~~Remove GaugeNeedleNode custom webgl code in ESP~~ Remove GaugeNeedleNode

**Comment by jessegreenberg** [comment]
SHA and date before removing WebGL:
```text
commit 48a5a521bdbdcdbcd418bc244cfca708606b77d0 (HEAD -> master, origin/master, origin/HEAD)
Author: Jesse <jesse.greenberg@colorado.edu>
Date:   Wed Apr 17 14:28:34 2019 -0400

    use SunConstants.VALUE_NAME_PLACEHOLDER for #63
```

**Comment by jessegreenberg** [comment]
> Combine BarGraphForeground and BarGraphBackground into a single node? (edited)

Lets not do this until we try to use griddle first.

**Comment by jessegreenberg** [comment]
Bar graph is done, see #31. Ill work on the pie chart next.

**Comment by jessegreenberg** [comment]
They can just be removed at this point.

**Comment by jessegreenberg** [comment]
> Remove bottomLayer, webGLLayer, and topLayer nodes.

We still want some layering so that subtypes of EnergySkateParkSCreenView can layer things in front of and beind the skater. I will keep bottomLayer (for UI components) and topLayer (for interactive components that are draggable on top of the rest of the UI).

**Comment by jessegreenberg** [comment]
One remaining comment related to WebGL says:
```js
    // Use a separate texture for left/right skaters to avoid WebGL performance issues when switching textures
    var leftSkaterImageNode = new Image( skaterLeftImage, {
      cursor: 'pointer',
      tandem: tandem.createTandem( 'leftSkaterImageNode' )
    } );
    var rightSkaterImageNode = new Image( skaterRightImage, {
      cursor: 'pointer',
      tandem: tandem.createTandem( 'rightSkaterImageNode' )
    } );
```

@samreid would you recommend leaving this as is or should we try to do this with a single Image Node? Commit that added this was fcbe3eda6fbe5173a8196ac8910721a78c90af40, but I couldn't find an issue, do you remember what platform/context had an issue with this?

**Comment by jessegreenberg** [comment]
Otherwise, I think all custom rendering has now been removed.

**Comment by samreid** [comment]
We have to use 2 images for the skater, it contains text and cannot be flipped programmatically or "PhET" would come out backwards.  I recommend recommenting that part and leaving the code as it is.  Thanks!

**Comment by jessegreenberg** [comment]
Oh yes I see! Thanks!

**Comment by jessegreenberg** [comment]
Then this issue can be closed!
