### ISSUE TITLE
Icon for "Stick to track" checkbox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#77]
This checkbox doesn't have an icon yet, should it? Only asking because the other checkboxes all have icons associated with them.

**Comment by jessegreenberg** [comment]
Would a mini version of these work?
![image](https://user-images.githubusercontent.com/6396244/60840165-e1656700-a19c-11e9-95aa-8f9dc0d0f36a.png)

Not sure if they will work when made smaller for the checkbox.

**Comment by arouinfar** [comment]
@jessegreenberg I think an icon could be nice, though not strictly necessary. Perhaps something simple like the dashed track with the skater's dot?

Here's a quick mockup. @jessegreenberg any thoughts?
![image](https://user-images.githubusercontent.com/8419308/60841499-3306f500-a18f-11e9-9376-86b6b1566ce4.png)

**Comment by jessegreenberg** [comment]
OK, thanks! I added that as the icon.
