### ISSUE TITLE
Layout for the grid on different screens

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#78]
Grid lines are separated by 1m. In some mockup images the grid is aligned such that a grid line hits right on x=0 meters in the sim while some have the grid lines aligned on the half meter mark.  Is this difference important?

It may be that labels line up with other panels in a particular screen better with one way than another. But I wanted to make sure this difference was OK and if we eneed to support both alignments.

**Comment by jessegreenberg** [comment]
If we decide that the grid should be aligned on the half meter for all screens, can that change apply to ESP:B?

**Comment by arouinfar** [comment]
> In some mockup images the grid is aligned such that a grid line hits right on x=0 meters in the sim while some have the grid lines aligned on the half meter mark. Is this difference important?

I'm not sure I follow. Looking through the design doc the x=0 line always fall on a grid line. Can you send me a screenshot of what you're talking about?

**Comment by jessegreenberg** [comment]
Sorry, I should have said the x=0 line in the sim model, which is at the center of the screen. Its easiest to see by seeing where the grid line hits the x center of the track. In energy-skate-park-basics and mockups for "graphs" screens, grid falls along each meter at x= -2, -1, 0, x=1, x=2, .... like this:
![image](https://user-images.githubusercontent.com/6396244/62260772-261da000-b3e1-11e9-8c6e-6334e0362a6a.png)

But for the other mockups, the grid lines fall on x =-2.5, -1.5, 0.5, 1.5, 2.5, ...:
![image](https://user-images.githubusercontent.com/6396244/62260820-51a08a80-b3e1-11e9-83b8-b1043e39fee2.png)

In that intro mockup, if the alignment was different the grid y labels might not fit between the graph and pie chart legend. Sim now has grid lines falling on the half meter, so if that is OK for all screens (including basics) there may not be anythign else to do here.

**Comment by jessegreenberg** [comment]
Discussed with @arouinfar - it is nice for the grid to fall on x = 0 and every 1 meter. We are going to go with that for all screens - the Y labels of the grid need to be shifted to the right a little bit to look nice. They should align with the bottom right corners of each grid square. For example, these should be shifted a little to the right
![image](https://user-images.githubusercontent.com/6396244/69447129-d4987880-0d23-11ea-9d2f-a02b31b7887e.png)

**Comment by jessegreenberg** [comment]
Part of this was done in a5ce542

**Comment by jessegreenberg** [comment]
@arouinfar Grid shifted and label alignment changed - example between two panels
![image](https://user-images.githubusercontent.com/6396244/70163415-6cd01f00-168d-11ea-9a77-3ae441525401.png)

Closing.
