### ISSUE TITLE
Can track icons include control points?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#79]
Icons for premade track radio buttons are currently images of the track nodes themselves. So the tracks that include control points will include those in the icons. Is this beneficial/acceptable or should the be removed from the icons?

![image](https://user-images.githubusercontent.com/6396244/62251318-5eab8280-b3bd-11e9-8448-99130cb65382.png)

**Comment by arouinfar** [comment]
@jessegreenberg thanks for checking in! I like the icons they way the are now. The control points provide nice contrast between the Intro and Measure screens, too.
