### ISSUE TITLE
Control points and draggable areas for new premade tracks

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#80]
@arouinfar are you comfortable with the shape of the new loop trackin ESP?

I chose control points that roughly make the shape but didn't thing through it too carefully. Should they be changed?

Draggable control points on premade tracks are limited to specific drag bounds. I added arbitrary bounds to get the feature working but this wasn't though through carefully either. @arouinfar would you change anything with the bounds that are in the sim now?

**Comment by arouinfar** [comment]
@jessegreenberg the default loop feels a bit cramped to me, but the basic shape is nice.
![image](https://user-images.githubusercontent.com/8419308/62256072-2b68f380-b3bd-11e9-9bee-782eb83166aa.png)

Could we set the default to something more like this?
![image](https://user-images.githubusercontent.com/8419308/62256108-476c9500-b3bd-11e9-8078-d7fd96c8c789.png)

> would you change anything with the bounds that are in the sim now?

Yes, I should fine-tune those a bit, but that will take a bit more playing with the sim.

**Comment by jessegreenberg** [comment]
Sounds good, I changed the defaults to match what you have in that image.

**Comment by jessegreenberg** [comment]
A related question is which control points should be draggable? Like in the parabola track only the bottom point is draggable.

**Comment by arouinfar** [comment]
@jessegreenberg I think we'll want the draggable areas to be as large as possible without allowing the control points to overlap. At the extremes, the track may end up a bit distorted, but I think it's generally better to allow more flexible interaction. All control points are movable on the Measure screen, but only the bottom points are movable on the Graphs screen. 

Here are some mockups to show the desired drag bounds. All areas have integer dimensions, but some have a half-unit offset from the grid. Any slight misalignment between the magenta rectangles and the grid is unintentional.
![ESP-Tracks-01](https://user-images.githubusercontent.com/8419308/66594823-1647d800-eb57-11e9-90dc-7b1d345ff90f.png)
![ESP-Tracks-02](https://user-images.githubusercontent.com/8419308/66594824-1647d800-eb57-11e9-9490-ff9c38ee34c9.png)
![ESP-Tracks-03](https://user-images.githubusercontent.com/8419308/66594825-16e06e80-eb57-11e9-907c-9a3bd8591bba.png)
![ESP-Tracks-04](https://user-images.githubusercontent.com/8419308/66594826-16e06e80-eb57-11e9-9501-b215c6c371fa.png)
![ESP-Tracks-05](https://user-images.githubusercontent.com/8419308/66594827-16e06e80-eb57-11e9-9673-751e4e102bc8.png)
![ESP-Tracks-06](https://user-images.githubusercontent.com/8419308/66594828-16e06e80-eb57-11e9-9a8f-9cdcbd331948.png)

**Comment by jessegreenberg** [comment]
Alright, thanks @arouinfar - these bounds were added in the above commit. Can you please review?

The bounds can be made permanantly visible with ?showPointBounds

In particular, I noticed that the right most bounds for the well,  loop,  and double well tracks overlap the control panel. Should something be made smaller so those panels aren't as wide?

Also, I find the draggable bounds to be difficult to see with the grid visible. Should the color or thickness change for improved visibility?

**Comment by jessegreenberg** [comment]
Oops, I have to adjust points for the graphs screen.

**Comment by arouinfar** [comment]
@jessegreenberg these are all looking good. It's possible to make a few odd tracks, but I think overall flexibility of the larger drag bounds is worth it.
