### ISSUE TITLE
Prevent premade tracks  from being "pushed" when points adjusted

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#83]
After a track control point is released, the track gets smoothed. If the smoothed track was below ground, it gets pushed up. This means that tracks can "grow" if you try to move a control point to a position that puts a portion of the track below ground. This is true of all tracks. But it is quite noticeable for new premade tracks where the control points are confined to draggable bounds. It is possible the track to be pushed so far that a control point can be moved out of bounds.

**Comment by jessegreenberg** [comment]
This actually isn't so bad with the current control points on the premade tracks. It is most noticeable right now with the loop. Here is a gif that demonstrates:
![test](https://user-images.githubusercontent.com/6396244/62253568-5440b700-b3c4-11e9-89fa-2700a6640b89.gif)


We could chcange the control points and draggable boundssuch that  it is impossible to drag a section of a track  below ground. Or after  bumping a track above ground, we could make sure that all control points are within their draggable bounds. 

I like the second option best and will try that. It will solve the issue for premade tracks, but accept the behavior for all other tracks. I think that is OK, but maybe there is another way to fix this. Also assigning @arouinfar if she has any thoughts about this.

**Comment by arouinfar** [comment]
> I like the second option best and will try that.

@jessegreenberg that sounds like a reasonable approach to me!

**Comment by jessegreenberg** [comment]
Cool, thanks @arouinfar - here it is with the fix I think it is working pretty well:
![7186c4c28b2c782b125a3cae0eb8a3a7](https://user-images.githubusercontent.com/6396244/62262603-45b7c700-b3e7-11e9-95f5-21dd29aeb20e.gif)
