### ISSUE TITLE
[Measure screen] Should measurable points fade away when track changes?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#84]
Just considering this case which looks slightly odd but may be totally reasonable. If you pause the sim then move the track the measurable points don't fade away, they are still measurable.  
![869190b0100caf21f6d6b1f51fbcb126](https://user-images.githubusercontent.com/6396244/62478204-85303b80-b778-11e9-9393-46d8e28dcaf2.gif)

What should the behavior be when the track is moved? Should existing points fade away whenever the track is moved? Only when moved while paused? Something else? Or is this totally fine?

This behavior matches the Java version, but points never fade out in the java version.

**Comment by jessegreenberg** [comment]
Similar question when a new premade track is selected
![image](https://user-images.githubusercontent.com/6396244/62478511-451d8880-b779-11e9-9077-f13f34ac7c87.png)

**Comment by jessegreenberg** [comment]
My instinct is to clear points when a new track is selected because the user is changing setups, but keep the points when a control point is dragged because the user is doing a more incremental change with the same setup and may want to keep measuring the existing points. What do you think @arouinfar?

**Comment by jessegreenberg** [comment]
> clear points when a new track is selected

This was done in the above commit.

**Comment by arouinfar** [comment]
> My instinct is to clear points when a new track is selected because the user is changing setups

Yes, I agree 100%.

> keep the points when a control point is dragged because the user is doing a more incremental change with the same setup and may want to keep measuring the existing points.

@jessegreenberg this screen is intentionally constrained, and I don't think it's pedagogically useful to keep the dots when moving the control points. The dots fade pretty quickly, so I don't think we're necessarily doing harm, but I don't know useful they would be to keep around. 

@ariel-phet any thoughts here? Would you prefer to clear the dots when a control point is moved, or is the behavior in master preferable?

**Comment by ariel-phet** [comment]
@arouinfar I think I would prefer clearing the dots when the control point is moved (my guess is this will also avoid some odd situations/potential bugs)

**Comment by arouinfar** [comment]
Thanks @ariel-phet.

@jessegreenberg let's clear the dots when a control point is moved.

**Comment by jessegreenberg** [comment]
Talked with @arouinfar over slack. Samples fade away in too many cases where they should be removed instantly. As part of this issue we will change that.

Skater samples should fade away only when skater direction changes. But when a control point is dragged, or the track changes in any way, or the "Path" checkbox is checked, or the skater is grabbed samples should disappear instantly.

**Comment by jessegreenberg** [comment]
This is done in the above commit. @arouinfar anything else to do for this issue?

**Comment by jessegreenberg** [comment]
I think we are good here, any other changes can have new issues.
