### ISSUE TITLE
[Graphs Screen] Layering of skater and graph

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#87]
On the graphs screen, is it OK that the skater goes behind the graph? Generally to drop the skater over the endpoints of the track, the skater will need to under or over the graph. Should the layering change?

![0dc6aea15ecc6afdb03ffaa3414383a3](https://user-images.githubusercontent.com/6396244/62487342-8f116900-b78f-11e9-8693-61f1e420d283.gif)

**Comment by arouinfar** [comment]
Let's change the z-ordering so the skater stays on top of all UI components, as was done in ESPB.

**Comment by jessegreenberg** [comment]
Sounds good, skater is above graphs.
