### ISSUE TITLE
Slider label alignment

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#90]
Mockups have the bold slider labels aligned like this:
![image](https://user-images.githubusercontent.com/6396244/62488037-51addb00-b791-11e9-8edc-7ed2143c1236.png)

So they all match the layout of NumberControl. 

Currently slider labels are centered while NumberControl labels are left aligned.
![image](https://user-images.githubusercontent.com/6396244/62488088-73a75d80-b791-11e9-910d-c399c2cbdd1a.png)

**Comment by jessegreenberg** [comment]
`align: 'left'` on a containing VBox isn't sufficient because it needs to be aligned with other controls. So the slider will somehow need knowledge of the other controls for layout.

**Comment by jessegreenberg** [comment]
I considered handling the layout externally to PhysicalSlider, maybe assembling the slider and label in EnergySkateParkControlPanel. This sounds complicated and would require checking if one of the passed in controls is of type PhysicalSlider.

I considered using AlignGroup, putting each control in the panel in an AlignBox each with matching widths so we know the width. But this adds complexity to many places because the controls are created at each screen view, so each screen view would now have to create align groups.

Now I am wondering if the best option may be to actually make the slider a number control with no arrow buttons and no number display.

**Comment by arouinfar** [comment]
@jessegreenberg I tried to find an example where we aligned left-aligned the HSlider and NumberControl labels, but I couldn't find one. 

> Now I am wondering if the best option may be to actually make the slider a number control with no arrow buttons and no number display.

This sounds a bit like a hack that might ruffle some feathers. I'm not particularly bothered by the current alignment, so we could just leave it as-is.
![image](https://user-images.githubusercontent.com/8419308/62489203-61bebe00-b783-11e9-9ef1-550ce130ef75.png)

**Comment by jessegreenberg** [comment]
@arouinfar thanks for looking through sims - I thought it was a little hacky too 😄 But i just noticed that there is already support for this in NumberControl, there is a layout method that allows you to hide the arrow tweakers and number display which should make this layout pretty easy.

**Comment by jessegreenberg** [comment]
Well, I couldn't use the method already in NumberControl because it actually puts the label at the left of the slider rather than the tweakers if the tweaker buttons are removed which is exactly what we don't want. But I went with a custom layout function for this and I think it is looking nice, will commit soon.

**Comment by jessegreenberg** [comment]
Done in the above commit, I actually think this was an improvement to code as well as layout.
