### ISSUE TITLE
Keep Radio buttons for attach/detach in basics?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#95]
![image](https://user-images.githubusercontent.com/6396244/62582211-a3ca2b80-b879-11e9-9108-27e490738c2d.png)

Energy Skate Park full replaces these with a check box. Will that checkbox now be used in energy-skate-park-basics or should this input be kept for basics only?

**Comment by arouinfar** [comment]
Let's keep them in ESPB. I think the iconic RadioButtonGroup does a nice job of showing the two states, and it probably easier for younger students to understand.

**Comment by jessegreenberg** [comment]
Sounds good, they are used in basics.
