### ISSUE TITLE
[Lab Screen] Why does the energy bar graph appear in an AccorionBox?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#97]
In the Lab Screen, the Energy Bar Graph is displayed in an AccordionBox. Other screens have visibility controlled with a Checkbox. Should more screens use the AccordionBox? Or should the lab screen use a checkbox? Or is the difference on the Lab Screen important?

**Comment by arouinfar** [comment]
@jessegreenberg I think this is an issue of a design decision not getting properly propagated through all of the mockups.

For consistency, the Bar Chart will always be in an accordion menu, titled "Energy". We had also discussed including the Bar Chart icon when the menu is collapsed, but not sure how tricky that would be to support.

![image](https://user-images.githubusercontent.com/8419308/64465074-e6c12e00-d0c7-11e9-970c-1d6c8802d440.png)

**Comment by jessegreenberg** [comment]
That sounds good @arouinfar, and just to verify, that means that the "Bar Graph" checkbox can be removed from all visibility control panels (including basics)?

**Comment by jessegreenberg** [comment]
Icon and layout added in the above commit.

**Comment by jessegreenberg** [comment]
OK, the energy bar graph checkbox was removed and replaced by the accordion box everywhere. @arouinfar can you please review?

**Comment by arouinfar** [comment]
@jessegreenberg looks good in ESP!

I'm a bit on the fence about whether or not to apply this change to ESPB. In Basics, there are fewer checkboxes, and I think it's nice to have the Pie Chart and Bar Graph grouped together. Students also tend to explore top-down, so they would likely play with the Pie Chart first. For the Basics audience, this flow may be more important. 

What do you think @ariel-phet?

**Comment by jessegreenberg** [comment]
Alright, the panel and visibility control checkbox has been added back to basics. Closing.
