### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#99]
Related to https://github.com/phetsims/QA/issues/397, but likely won't get done until after QA is finished.

I should review the design and see if there are any inconsistencies or pixel polishing that needs to be done.

**Comment by JRomero0613** [comment]
@arouinfar When testing for https://github.com/phetsims/QA/issues/397 I noticed on the Graphs screen that the "Position" graph x-axis is labeled as "Time (s)". If I'm not mistaken it should be labeled "Position (m)".

**Comment by arouinfar** [comment]
Thanks @JRomero0613. I'm seeing the correct axis labelling in master, so I think it must have been corrected.

Pixel polishing is being handled in #240, so I'm going to go ahead and close this issue.
